### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by mbthales** [NovelCOVID/API#1]
Hey man, i want use your api for a personal project and learning, but i don't have success for CORS reasons.

**Comment by marbysneaker** [comment]
got the same issue with CORS

**Comment by jonas-thuvesson-winberg** [comment]
same

**Comment by marbysneaker** [comment]
I got it to work I downloaded an extension on chrome that allows CORS

**Comment by KBPsystem777** [comment]
Got same issue but hope this will somehow help you guys: [3 Ways to Fix the CORS Error](https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9)

**Comment by shikwambana** [comment]
I have being trying to solve this for 4 hours. I want to build an angular app that shows the number of cases in each country. Has anyone had any luck in solving this?

**Comment by decoresin** [comment]
This API service works only Server To Server service !!!

**Comment by Suraj975** [comment]
Please refer this link as it worked for me. Explanations is really good and it might work for you guys.

https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors

**Comment by javieraviles** [comment]
I forked the project, added CORS to express and deployed in Heroku, if anybody wants to use it, you should not have any CORS issues:

endpoints:
https://coronavirus-19-api.herokuapp.com/all
https://coronavirus-19-api.herokuapp.com/countries

the project is here if wanna see the code:
https://github.com/javieraviles/covidAPI

also in the root (https://coronavirus-19-api.herokuapp.com/) I added an ionic example app showing the api info, code also in the project

**Comment by javieraviles** [comment]
Will create a PR here to add CORS and see if author wants it... but also I think he modified the code under the hood, because the indexes to scrap cells from https://www.worldometers.info/coronavirus/ were broken

**Comment by sunil-sandhu** [comment]
Great work @javieraviles - I was literally considering doing the same thing, so thank you for taking the time to do this! :)

**Comment by mbthales** [comment]
Thanks man. It works! @javieraviles

**Comment by EliteDaMyth** [comment]
> Will create a PR here to add CORS and see if author wants it... but also I think he modified the code under the hood, because the indexes to scrap cells from https://www.worldometers.info/coronavirus/ were broken

I fixed it on the backend but forgot to update the code here! i have updated it so as for the CORS issues if you want you can open a pull request but its not that big of an issue because it can be fixed on the client side great work though!

**Comment by EliteDaMyth** [comment]
@javieraviles also i would totally welcome your pull request for the frontend looks dope! I can host it on my server heroku seems to be a little slower. LMK on discord im more active there EliteDaMyth#0690

**Comment by shikwambana** [comment]
> I forked the project, added CORS to express and deployed in Heroku, if anybody wants to use it, you should not have any CORS issues:
> 
> endpoints:
> https://coronavirus-19-api.herokuapp.com/all
> https://coronavirus-19-api.herokuapp.com/countries
> 
> the project is here if wanna see the code:
> https://github.com/javieraviles/covidAPI
> 
> also in the root (https://coronavirus-19-api.herokuapp.com/) I added an ionic example app showing the api info, code also in the project

Awesome. I was actually in the process of doing this as well. I am working on a web app to track cases here in South Africa https://www.corvid19numbers.com/
