### ISSUE TITLE
"States" endpoint is returning an empty array

### ISSUE THREAD

**Issue by rveitch** [NovelCOVID/API#100]
The [`/states`](https://corona.lmao.ninja/states) endpoint is currently returning an empty array. :/

![image](https://user-images.githubusercontent.com/12876929/77268077-c1b29800-6c72-11ea-9c94-2e76d9d6b0f2.png)

**Comment by RyanHarlow** [comment]
there is already a pull request with the fix but the owners are unable to merge it right now

**Comment by ebwinters** [comment]
#99 linked, will resolve itself once this is fixed

**Comment by EliteDaMyth** [comment]
Fixed
