### ISSUE TITLE
Can You Please Add Indian States?

### ISSUE THREAD

**Issue by shailandraRajput** [NovelCOVID/API#104]
Hello,
Can you please add the Indian States 
Thank You

**Comment by madhavtripathi05** [comment]
I've already asked for it. Also, provided them with my scraper(which is written in Dart). looks like they didn't take it seriously.😶

**Comment by EliteDaMyth** [comment]
Do you have a source for Indian states. @madhavtripathi05

**Comment by prateekbangre** [comment]
@EliteDaMyth you can fetch details from https://www.mohfw.gov.in/ or https://covidout.in/

**Comment by EliteDaMyth** [comment]
The second link doesn't work. Will use the official government one.

**Comment by EliteDaMyth** [comment]
Accidentally closed

**Comment by shailandraRajput** [comment]
I think this will helpful for you https://www.mohfw.gov.in/pdf/DistrictWiseList324.pdf

**Comment by EliteDaMyth** [comment]
Closed because state wise data is not at all accurate ;-;
