### ISSUE TITLE
Countries EndPoint : countryInfo returns NO DATA for many countries

### ISSUE THREAD

**Issue by 55abhilash** [NovelCOVID/API#121]
Hi,

When I hit [https://corona.lmao.ninja/countries](https://corona.lmao.ninja/countries), an array of JSON objects is returned, each element of array is information for one country in JSON.
In each JSON, there is a JSON key-value pair for "countryInfo". This information is returned for most countries. However, it is returned as NO DATA for many countries, Eg. USA, UAE, Syria, etc.
![Screenshot from 2020-03-23 22-09-58](https://user-images.githubusercontent.com/9768146/77340277-1299bd80-6d53-11ea-93d3-1b73be2fbd52.png)

**Comment by 55abhilash** [comment]
It looks like the issue is due to difference in name of countries in the https://www.worldometers.info/coronavirus/ main table which is used by us, and the ISO information statically included here: https://github.com/NovelCOVID/API/blob/master/utils/country_utils.js.
Eg. In the worldometers.info table, country is called "USA" while in our utils file it is "United States". Due to this mismatch, the call to getCountryData returns NO DATA.
I will submit a pull request with the changes if you think this analysis is right.

**Comment by buster95** [comment]
Was resolve on #117

**Comment by stoutlabs** [comment]
The country names and capitalization have been changing as well... which is quickly becoming frustrating. e.g. `Korea, South` became `korea, south` and most recently it is now `s. korea`.  ISO names would be best, and always consistent.

**Comment by buster95** [comment]
Country names haven't been changing, data is showed like `https://www.worldometers.info/coronavirus`
you can see here
![image](https://user-images.githubusercontent.com/15637669/77361907-b6fd0f00-6d15-11ea-91eb-1bda1231c6a0.png)

If you are talking about this endpoint `https://corona.lmao.ninja/countries/{country name}`, `country name` parameter have been changing

**Comment by stoutlabs** [comment]
Ah, yes... that's what I was referring to. (Timeline data as well.)

**Comment by EliteDaMyth** [comment]
already a pr trying to fix.
