### ISSUE TITLE
Version the API

### ISSUE THREAD

**Issue by ahmadawais** [NovelCOVID/API#123]
Please version the API. Y'all pushed breaking changes without any notice and it broke everything on my end. 

If the API gets versioned /v1 /v2 — we can keep publishing changes without breaking everything and can deprecate old versions by announcing it.

**Comment by apollyon600** [comment]
This is a great suggestion, although we merge PR left and right and it would be extremely tedious to keep track or even update versions of the API.

**Comment by ahmadawais** [comment]
But that would be much more responsible of you. Otherwise, you'll keep breaking all the sites and CLI based on the API. Causing people to spend more time fixing things than building things.

I say this with all the appreciation.

**Comment by EliteDaMyth** [comment]
alot of people will have to update their code if we add a /v1/endpoint format. rn the api has not changed the way it has served data since the beginning

**Comment by ahmadawais** [comment]
I believe you can start right away. Let the current API be the way it is. Fork it over and start `v1`. Those who chose to go with `v1` will be rest assured that API won't change ever. Whenever you have a breaking change, offer `v2` and move to the next version.

**Comment by ahmadawais** [comment]
Case in point you folks again broke the site and CLI since you pushed another change to the API which was not accountable for before. `casesPerOneMillion`. This is sad. :(

```sh
"casesPerOneMillion": 4,
"deathsPerOneMillion": 0
```

**Comment by EliteDaMyth** [comment]
if you are in the discord server we already have thought of versioning it. thanks for the idea

**Comment by ahmadawais** [comment]
Y'all are amazing. Thank you! 👌

>
