### ISSUE TITLE
czechia is missing in the single country endpoint

### ISSUE THREAD

**Issue by ahmadawais** [NovelCOVID/API#124]
In all countries data `czechia` exists but if you request it via single country API it does not.

https://corona.lmao.ninja/countries/czechia

**Comment by buster95** [comment]
@ebwinters you can see a lot of people looking for **_czechia_**

**Comment by ebwinters** [comment]
Will have a fix out for this within 30 min

**Comment by ahmadawais** [comment]
Awesome! 💯

>

**Comment by ebwinters** [comment]
fixed with this #125, waiting for merge

**Comment by ebwinters** [comment]
#131 fixes this now, will merge later
