### ISSUE TITLE
request: Use ISO country names and/or codes

### ISSUE THREAD

**Issue by stoutlabs** [NovelCOVID/API#127]
The timeline endpoint (and possibly others) seems to frequently change the names of countries... e.g. it went from `Korea, South` to `korea, south` and then most recently to `s. korea`.

I'm requesting that the standardized (ISO) country names and or 3-letter code be used, to keep everything consistent.  (I will happily provide a JSON of country/state codes, if needed!)

**Comment by buster95** [comment]
Ok, you can propose data about country names, I will work in that changes when you submit data file

**Comment by stoutlabs** [comment]
Awesome! 🎉

Here's a JSON file with country names and ISO codes:  https://gist.github.com/stoutlabs/060e4f864742d44ac7d3a2881cfa3255#file-countrynamescodes-json  (If you could just get the 3-letter country codes into the API output, that would be awesome!)

And here's a JSON file with the US states and (2-letter) ISO abbreviations: https://gist.github.com/stoutlabs/060e4f864742d44ac7d3a2881cfa3255#file-statenamescodes-json

**Comment by O-r-D** [comment]
It would also mean a lot if you would make the endpoint of a specific country an iso code instead of its name.

Right now, I'm having difficulty getting an entry for names like S. Korea and United States as their names are displayed differently.
