### ISSUE TITLE
Some flags come as unkown

### ISSUE THREAD

**Issue by guillermotti** [NovelCOVID/API#128]
Hi there 👋!

Calling this endpoint https://corona.lmao.ninja/countries some flags come with https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/unknow.png as value.

For example USA, but it's possible to reach the right flag making a call to: https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/us.png

Another example is UK: https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gb.png

Can you update the API for those countries. Thank you in advance and fantastic work! 😊

**Comment by buster95** [comment]
I'm sorry friend, was resolve on #117, waiting for merge

**Comment by guillermotti** [comment]
Perfect, thanks!!
