### ISSUE TITLE
Endpoint:  https://corona.lmao.ninja/*

### ISSUE THREAD

**Issue by tobiu** [NovelCOVID/API#13]
Any chance to get the endpoint more stable?

Might be too much incoming traffic.

Maybe add some basic caching.

**Comment by tobiu** [comment]
[off topic]

some cvid-demos i am working on using your api:
https://neomjs.github.io/pages/

**Comment by EliteDaMyth** [comment]
cavhing already implemented through cf. it happens when worldometers site is updating and the api updates at same time. it fixes in 10 minutes automatically

**Comment by EliteDaMyth** [comment]
also good work :)
