### ISSUE TITLE
https://corona.lmao.ninja/jhucsse Data In wrong places

### ISSUE THREAD

**Issue by SaadAsif1** [NovelCOVID/API#133]
While looking at the https://corona.lmao.ninja/jhucsse api most of the data are in the wrong places such as "country" is showing the province, "province" is showing a number, "updatedAt" is showing a state, and more.

**Comment by buster95** [comment]
Wrong fields 🤨
![image](https://user-images.githubusercontent.com/15637669/77382702-a0bb7700-6d46-11ea-98bc-fad22b9c78ba.png)

**Comment by RyanHarlow** [comment]
working on it

**Comment by SaadAsif1** [comment]
Let us know when fixed thank you.

**Comment by RyanHarlow** [comment]
@SaadAsif1   i submitted the pull request, just needs to merged and deployed

**Comment by SaadAsif1** [comment]
@RyanHarlow Thanks
