### ISSUE TITLE
The end point for china timeseries is not returning data

### ISSUE THREAD

**Issue by phptuts** [NovelCOVID/API#138]
The end point for the china timeline series is not returning data.

https://corona.lmao.ninja/historical/china
```json
{
standardizedCountryName: "china",
timeline: {
cases: { },
deaths: { },
recovered: { }
}
}

```

**Comment by ebwinters** [comment]
yeah this is part of a bigger issue which I will fix tomorrow. our data source (Johns Hopkins) discontinued certain APis and features so we need to reprogram the endpoints

**Comment by phptuts** [comment]
Thank you

**Comment by kw2019ltd** [comment]
yes same here waiting thank you

**Comment by EliteDaMyth** [comment]
closing.

**Comment by kw2019ltd** [comment]
still getting empty result

{"standardizedCountryName":"china","timeline":{"cases":{},"deaths":{},"recovered":{}}}

**Comment by ebwinters** [comment]
yesterday I said I'd fix it tomorrow and it's 10:30 AM. Give me a couple hours dude lol

**Comment by kw2019ltd** [comment]
yeah sure i just saw the issue is closed :) take your time thanks
