### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by tobiu** [NovelCOVID/API#14]
Access-Control-Allow-Origin header

would be nice, so that you can use the API via JS (client side) without using proxies.

thx & best regards,
tobias

**Comment by PolyMeilex** [comment]
It already returns ```Access-Control-Allow-Origin: *``` header
https://github.com/NovelCOVID/API/blob/f45191bab315ffff5fc401a5911ecaf11d1818d0/server.js#L158

**Comment by tobiu** [comment]
ah, perfect. just verified it and it works fine now.
