### ISSUE TITLE
States data is incorrect

### ISSUE THREAD

**Issue by sorressean** [NovelCOVID/API#151]
in the /states endpoint, the states data is incorrect; active for all states is 0, thus making recovered everything but deaths. If active could populate, the rest would likely calculate correctly.

**Comment by ebwinters** [comment]
I think we just need to rescrape

**Comment by EliteDaMyth** [comment]
seems to be fixed. lmk if you wanna reopen in future

**Comment by sorressean** [comment]
This is still not correct.
{"state":"New York","cases":25665,"todayCases":4790,"deaths":183,"todayDeaths":26,"recovered":25374,"active":0}
Active is set to 0 here still, which means that recovered is everything that's not deaths, this is incorrect.
