### ISSUE TITLE
hey i'm using this api https://corona.lmao.ninja/ but sometimes its top working

### ISSUE THREAD

**Issue by maroine888** [NovelCOVID/API#161]
hey i'm using this api https://corona.lmao.ninja/ but sometimes it stop working and  the other thing is before you add flag country this api was very fast but now a little bit slow and it take more time to get the data thank you so much and sorry for my english and pls if you can delete Not important
information and leave just country name and confirmed and dead and recovered because take to much time to parse all data and filter it

**Comment by kzkvv** [comment]
i confirm, /countries was recently unavailable. it looks like the server is overloaded

**Comment by iClusterDev** [comment]
Same issue here!

**Comment by mjdeside** [comment]
Same Issue here I can't also access https://corona.lmao.ninja/countries is there other link we can use?

**Comment by gabosdk** [comment]
Same here, I cannot access

**Comment by mjdeside** [comment]
Its already fix guys

**Comment by iClusterDev** [comment]
Nice. Thanks for the Fix
