### ISSUE TITLE
historical data (v2) doesn't contain recovered anymore

### ISSUE THREAD

**Issue by blackbagheera** [NovelCOVID/API#168]
https://corona.lmao.ninja/v2/historical holds deaths and cases but no recovered data anymore.
Can you draw the data from the daily reports? 
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports
--> Recovered

**Comment by ebwinters** [comment]
doing calculations for all those files is very intensive. JHU stopped offering recovered data, so we stopped supplying it in V2
