### ISSUE TITLE
Lat, Long wrong for some countries

### ISSUE THREAD

**Issue by EngandDeveloper** [NovelCOVID/API#169]
In, https://corona.lmao.ninja/countries?sort=%7Bparameter%7D, end-point, the USA's and several other countries lat and long are set to {0,0}. Can you please fix them?

By the way, thank you so much for a simple API with variety of variables it helps a lot for my project.

**Comment by ebwinters** [comment]
will be fixed with merge of #117, waiting for the dude to make the changes I listed in comments on P R

**Comment by EngandDeveloper** [comment]
Ok thank you so much.
Note: the countries I found with lat, long are {0,0}: 
the USA
Iran
the UK
Palestine
Turks and Caicos
S. Korea
Czechia
Diamond Princess
Channel Islands
Faeroe Islands
Tanzania
