### ISSUE TITLE
Canada province named "recovered"

### ISSUE THREAD

**Issue by PlGGS** [NovelCOVID/API#170]
When I realized the 'recovered' stats were missing from v2, I searched [here](https://corona.lmao.ninja/v2/historical) for any occurrences of the term in the API and found that Canada has a province that's improperly labelled as 'recovered'

![canada](https://user-images.githubusercontent.com/20197872/77490336-9e215600-6e08-11ea-9685-9fe5dad33055.png)

**Comment by ebwinters** [comment]
Issue on jhon's hopkins end: see issue in their repo here: https://github.com/CSSEGISandData/COVID-19/issues/1519
