### ISSUE TITLE
API stopped working at all (returns empty object)

### ISSUE THREAD

**Issue by ianpan870102** [NovelCOVID/API#175]
5 minutes ago it was still working, but now the API urls seem to have stopped completely.

**Comment by verfriemelt-dot-org** [comment]
this seems to affect only v1

**Comment by ianpan870102** [comment]
I see. However, as far as I can tell -- V2 seems to still be under development? I was making heavy use of the flag png files and ISO and all the goodies in V1....

**Comment by verfriemelt-dot-org** [comment]
its back! :D

**Comment by ianpan870102** [comment]
YAYYY!!! 
Btw, thanks all who contributed to this API -- I am practising React.js with a project built around this.
Closing issue.
