### ISSUE TITLE
can we have new rest url for historical data for  all total cases, recovery, and deaths (global)

### ISSUE THREAD

**Issue by kw2019ltd** [NovelCOVID/API#177]

**Comment by harshavmb** [comment]
I vote for this. Right now my app is performing heavy computations. If it is processed at the API end, would help many consumers. 

There are around 80k records and looping through each record to sum is a resource intensive operation.. Good if it is offered by API..

**Comment by EliteDaMyth** [comment]
The server is already overloaded. Easy to do on client side.
