### ISSUE TITLE
ISO for Czechia

### ISSUE THREAD

**Issue by siaw23** [NovelCOVID/API#180]
This ISO2 code for Czechia is "CZ"

https://corona.lmao.ninja/countries/czechia

It says "NO DATA", can this be fixed?

**Comment by JamesShelley** [comment]
Looks like this was fixed in one of the latest PR's https://github.com/NovelCOVID/API/blob/master/utils/country_utils.js. 
Should be live when the next deploy takes place.

**Comment by JamesShelley** [comment]
Just checked latest to confirm, all good! @siaw23 

`{
"country": "Czechia",
"countryInfo": {
"iso2": "CZ",
"iso3": "CZE",
"_id": 203,
"lat": 49.75,
"long": 15.5,
"flag": "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cz.png"
},
"cases": 1497,
"todayCases": 103,
"deaths": 5,
"todayDeaths": 2,
"recovered": 10,
"active": 1482,
"critical": 19,
"casesPerOneMillion": 140,
"deathsPerOneMillion": 0.5
},`
