### ISSUE TITLE
Recovered is no more available in v2 api

### ISSUE THREAD

**Issue by whoo** [NovelCOVID/API#187]
Hi Guys,

"recovered" field disapears in timeline section.

Example :  https://corona.lmao.ninja/v2/historical/Canada
{"country":"canada","timeline":{"cases":{...},"deaths":{...}}}

Regards,
Dominique

**Comment by ebwinters** [comment]
There has been like 10 other closed issues saying the same thing. Our data source discontinued it

**Comment by dahacouk** [comment]
Hi @ebwinters I'd like to lend a hand a go contact your "data source". Who are they? And got any people/references or anything for me to start with?

**Comment by ebwinters** [comment]
It's John's Hopkins. There's no reason to contact them they are swamped with thousands of issues on their repo.
