### ISSUE TITLE
Historical stop updating on March 23th

### ISSUE THREAD

**Issue by fernandocani** [NovelCOVID/API#189]
The url [https://corona.lmao.ninja/historical/brazil](https://corona.lmao.ninja/historical/brazil) has stop tracking foward 3/23/2020.

![image](https://user-images.githubusercontent.com/13990282/77602779-16f9de00-6eed-11ea-991b-7e97c326e78e.png)

**Comment by nibble-4bits** [comment]
You should use the v2 endpoint: https://corona.lmao.ninja/v2/historical/brazil

The v1 endpoints for historical data has been deprecated

**Comment by fernandocani** [comment]
It worked. thanks!
Maybe have the v1 redirect to the v2, or make a warning.

Thanks for the help!

**Comment by nibble-4bits** [comment]
No problem, happy to help! 

If you want to suggest those changes maybe you should open another issue. I'm not a contributor to this project so I don't know what they think about the changes.
