### ISSUE TITLE
US States Historic data gone

### ISSUE THREAD

**Issue by vpma2580** [NovelCOVID/API#192]
Hello,
I was working with US States historical data.
But today, i couldn't see states name when I get data.
Any changes?
Best

**Comment by vpma2580** [comment]
Someone said "please check closed issue". This is not solution.
If there are 1000 closed issue, i should check 1000?

**Comment by vpma2580** [comment]
Is there any way i can get historical data for each state of US?

**Comment by ebwinters** [comment]
No, the data source JHU discontinued it
