### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by siaw23** [NovelCOVID/API#194]
If I go to `https://corona.lmao.ninja/countries/some_gibberish` I get 

>{"message":"Country not found or dosen't have cases"}

Typo in "doesn't".

**Comment by Sanan4li** [comment]
Its not an Issue.. You can handle it yourself..

**Comment by siaw23** [comment]
Well of course. But wouldn't it be nice if it's known and fixed? :/

**Comment by buster95** [comment]
What's the correct??, excuse me english isn't my first language

**Comment by nibble-4bits** [comment]
@buster95 It should say  _doesn't_ instead of _dosen't_
