### ISSUE TITLE
Cases per million are parsed incorrectly when above 999

### ISSUE THREAD

**Issue by thalvadzhi** [NovelCOVID/API#197]
When cases per million are above 999 they are parsed as their most significant digit only. For example 1234 is parsed to 1. That's because numbers above 999 have a comma in them. I suggest removing the comma similar to the way you remove it for the other columns. The bug is also present for the deathsPerOneMillion column. 

More concretely this:
https://github.com/NovelCOVID/API/blob/890eff851b65ee81f762e2180ed6716cb75c32f0/funcs/getCountries.js#L126
should also benefit from this treatment:
https://github.com/NovelCOVID/API/blob/890eff851b65ee81f762e2180ed6716cb75c32f0/funcs/getCountries.js#L119

Furthermore casesPerMillion is an integer. For example Italy currently has a population of 60 million (according to google) and 74,386 cases, so casesPerMillion is 74386/60 = 1239 (in worldometer it is 1,230 because they probably used another value for the population), not 1.239. Meaning it is rounded to the nearest integer. So perhaps parseInt should be used instead of parseFloat.

**Comment by ben-richardson-moneysmart** [comment]
Added a PR to fix this one based on the type of data in the WorldMeteres table. Fixed the issue using the same method to remove the comma in the other columns of the table.

https://github.com/NovelCOVID/API/pull/198

**Comment by ben-richardson-moneysmart** [comment]
> Meaning it is rounded to the nearest integer. So perhaps parseInt should be used instead of parseFloat.

Countries like `Kenya` have a value of 0.5 in the casesPerMillion column. I think Float is still best here rather than integer where this would be rounded to 1.

**Comment by thalvadzhi** [comment]
> > Meaning it is rounded to the nearest integer. So perhaps parseInt should be used instead of parseFloat.
> 
> Countries like `Kenya` have a value of 0.5 in the casesPerMillion column. I think Float is still best here rather than integer where this would be rounded to 1.

Yes, you are right, I missed that before.
