### ISSUE TITLE
Captcha HTML file get returned.

### ISSUE THREAD

**Issue by tb100** [NovelCOVID/API#199]
I'm using nodejs to retrieve the data through "https.get()" from "https://corona.lmao.ninja/all". Sometimes, this returns a captcha HTML file instead of the JSON data. I tried using the "novelcovid" NPM package, but it causes an error: 
`UnhandledPromiseRejectionWarning: TypeError: Something went wrong, please try again later.`  
Can anyone help me? Thanks.

**Comment by minhtuancn** [comment]
You shoud use cron cache

**Comment by ebwinters** [comment]
@apollyon600
