### ISSUE TITLE
Method countries retrieves empty array

### ISSUE THREAD

**Issue by radun2** [NovelCOVID/API#2]
First of all nice job.

I was trying to calculate more data for example Death Percentage and Recovered percentage but it seems that something updated in the website and is not parsing properly anymore. 

BTW if someone is interested for more data: https://github.com/CSSEGISandData/COVID-19

**Comment by EliteDaMyth** [comment]
@radun2 i was moving my hosts cuz of the large amount of requests i was getting its completely fine now!
