### ISSUE TITLE
Cycle through case death and recovered by tapping 

### ISSUE THREAD

**Issue by defrt** [NovelCOVID/API#20]
Cycle through case death and recovered by tapping

**Comment by EliteDaMyth** [comment]
elaborate pls

**Comment by jetwhisperer** [comment]
There’s a tweak for iOS that utilizes this API and I believe he has confused this repo for one that maintains that tweak. This is a requested feature of that tweak

**Comment by defrt** [comment]
When you tap the number of causes on top right hand corner under the battery it will change case numbers to death number. One more tap changes to recovered cases count. Tap again total case numbers again

**Comment by defrt** [comment]
Sorry I thought this is coronacount tweak
