### ISSUE TITLE
Congo listed 2x in https://corona.lmao.ninja/countries

### ISSUE THREAD

**Issue by tobiu** [NovelCOVID/API#200]
Congo

Congo, the Democratic Republic of the

the entries have different data, did you replace a different country by accident?

**Comment by buster95** [comment]
They are differents countries

**Comment by buster95** [comment]
Congo
![Screenshot_20200326-070231_Chrome](https://user-images.githubusercontent.com/15637669/77649674-de2f2880-6f2f-11ea-8456-bb5eb9c7eedb.jpg)

Republic democratic of Congo
![20200326_070211](https://user-images.githubusercontent.com/15637669/77649771-fbfc8d80-6f2f-11ea-9c15-a12b2c53e248.jpg)

**Comment by tobiu** [comment]
thx, learned something.

so "Congo" is the official name for "Republic of the Congo" (without democratic)
