### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by vasanianil** [NovelCOVID/API#206]
Cloudflare can not reach your server, please fix
This is keep happening everyday

**Comment by MarkSablan** [comment]
Having the same issue. Was creating an application when I encountered this

**Comment by msghera** [comment]
A similar case. Response code is 522.

**Comment by vasanianil** [comment]
Please fix asap.

**Comment by jonyig** [comment]
I have the issue ,too

**Comment by buster95** [comment]
locally I have this
![image](https://user-images.githubusercontent.com/15637669/77664908-7b945780-6f44-11ea-8b31-4e117039a963.png)

This could be damaged online service

**Comment by interpegasus** [comment]
Great work with the API. I would suggest adding cache to alleviate the server load and handling more requests. Please fix ASAP. Thanks

**Comment by vasanianil** [comment]
Any developer of this API seeing this issue or not? Any update?

**Comment by raulssorban** [comment]
Great work with the API, suggestion: make it online pls

**Comment by alexerhardt** [comment]
I've also been getting 502s in the last 24 hours...

Could this be Worldometer.info doing some throttling?

I don't understand the Redis config that well yet, but I think to avoid any problems with Worldometer what I'd do is only refresh the values on Redis every so often (one hour?)

I would also give the response 30min-1h cache TTL for responses to alleviate server load (I understand this is last minute data, but it's a decent trade-off I think...)

@buster95 I think I can tell the source of that error... Johns Hopkins recently renamed their files, so it's trying to get a file that no longer exists. To clarify, this should be a different error to the 502 others and me are reporting.

**Comment by hrdunn** [comment]
@buster95 to add to that, the file getting pulled there from the johns hopkins repo has been deprecated as of last night the new file is `time_series_covid19_confirmed_global.csv` and does not include US States. They mentioned that they are going to add them back but who knows when that will happen.

For reference on their changes [Here](https://github.com/CSSEGISandData/COVID-19/issues/1250)

**Comment by dicedtomatoreal** [comment]
We are working to get it up sorry.

**Comment by dicedtomatoreal** [comment]
Please wait 5 minutes while we fix

**Comment by dicedtomatoreal** [comment]
This was unexpected, and we are doing the best we can :D

**Comment by alexerhardt** [comment]
@dicedtomatoreal 

Thank you so much, the API is great, I like it as both a consumer and a developer.

If you could please let us know what went wrong I'd greatly appreciate it. I'm thinking of forking it and hosting my own so it would be very helpful to know - thanks.

**Comment by dicedtomatoreal** [comment]
The api is now up, stay safe!

**Comment by hrdunn** [comment]
@dicedtomatoreal Any idea what caused this issue? should we decide to host it ourselves it would be helpful to know if possible.

**Comment by vasanianil** [comment]
API is great. Great work guyz. I would suggest everybody to cache data so we dont hit https://corona.lmao.ninja/ too many times.

**Comment by ebwinters** [comment]
@vasanianil how do you propose doing that, from a JS perspective? Give some psosible solutions
