### ISSUE TITLE
API is down again

### ISSUE THREAD

**Issue by vasanianil** [NovelCOVID/API#209]
Please make a permanent fix

**Comment by mjdeside** [comment]
ya its down

**Comment by rajendraprabhu** [comment]
yeah, the API is down!

**Comment by didulaj** [comment]
Any back up API available to get at least basic data when this API is down? I remember one guy posted one before but I cannot find it.

**Comment by marc-se** [comment]
> Any back up API available to get at least basic data when this API is down? I remember one guy posted one before but I cannot find it.

I use this as a backup https://github.com/javieraviles/covidAPI

**Comment by marc-se** [comment]
API is back

**Comment by vasanianil** [comment]
> > Any back up API available to get at least basic data when this API is down? I remember one guy posted one before but I cannot find it.
> 
> I use this as a backup https://github.com/javieraviles/covidAPI

Thanks for backup

**Comment by didulaj** [comment]
> > Any back up API available to get at least basic data when this API is down? I remember one guy posted one before but I cannot find it.
> 
> I use this as a backup https://github.com/javieraviles/covidAPI

Thank you very much

**Comment by interpegasus** [comment]
Great work with the APIs.  I also would suggest adding cache to reduce resource usage. 
Perhaps via: https://www.npmjs.com/package/apicache

And also contacting the hosting provider `Cloudflare` to grant more resources if possible would be ideal. Or an AWS free trial.

**Comment by ebwinters** [comment]
We are currently discussing the possibility of moving to NGINX solution and load balancing multiple servers. Please try to refrain from spamming github with issues of API being down, hopefully all issues will be fixed within the day. Thanks!
