### ISSUE TITLE
Querying country name not working

### ISSUE THREAD

**Issue by NicolaiVdS** [NovelCOVID/API#22]
When i go to https://corona.lmao.ninja/countries/Belgium

i get following response:
`Country not found`

while that country is in the countries list

**Comment by darling** [comment]
The correct endpoint is `/countries/belgium`

**Comment by NicolaiVdS** [comment]
ok a bit strange cuz the correct way to write a country name is always with a capital letter

**Comment by EliteDaMyth** [comment]
i'll add tolowercase to fix issue soon

**Comment by EliteDaMyth** [comment]
Done
