### ISSUE TITLE
API Query Issue ISO 3166

### ISSUE THREAD

**Issue by WarenGonzaga** [NovelCOVID/API#226]
This is the Issue I meant...
https://corona.lmao.ninja/countries/au

It shows Austria instead of Australia... the ISO3/ISO2 of Austria is AT or AUT while Australia AUS or AU

Same thing with Philippines... there should be a response for PHL...
https://corona.lmao.ninja/countries/phl ---> no response.

Another issue is... 
https://corona.lmao.ninja/countries/ar should be argentina not Denmark

These are the issues I'm facing...

**Comment by EliteDaMyth** [comment]
we dont serve results based on the country code.
