### ISSUE TITLE
Disable the HTTP redirect to HTTPS

### ISSUE THREAD

**Issue by meesaltena** [NovelCOVID/API#23]
I'm trying to use this API on an ESP32 microcontroller which has very little memory and power, so getting HTTPS to work is quite a challenge. If i make a request using HTTP I get a 301 redirect. I'd love for the API to support HTTP, if possible.

**Comment by EliteDaMyth** [comment]
i use cloudflare so i cannot disable the https. i used an arduino and https works on it. try finding info about it on google.

**Comment by meesaltena** [comment]
I ended up making it work with https. Thanks anyway.
