### ISSUE TITLE
Ability to pull historical World-Data

### ISSUE THREAD

**Issue by samerawada92** [NovelCOVID/API#237]
It would be sweet if there was an endpoint to pull historical data for the world numbers as well. Something like: https://corona.lmao.ninja/v2/historical/world. :)

**Comment by ThinkHattke** [comment]
can I work on this @ebwinters ?

**Comment by ThinkHattke** [comment]
@samerawada92 that link is not working, can you provide a source to scrap from.

**Comment by buster95** [comment]
I think this endpoint should be 
/all/historical

**Comment by ebwinters** [comment]
it's already done m8: https://corona.lmao.ninja/v2/historical/all
![](https://media.giphy.com/media/8FSLJapsx4c4Iv2cRF/giphy.gif)
