### ISSUE TITLE
Not sorted properly

### ISSUE THREAD

**Issue by GowthamF** [NovelCOVID/API#241]
https://corona.lmao.ninja/countries does not return the data in order.
![image](https://user-images.githubusercontent.com/40605124/77797806-b9ee5b80-7097-11ea-80b8-db339203a884.png)
![image](https://user-images.githubusercontent.com/40605124/77797852-d12d4900-7097-11ea-9c45-4ab5079ac05d.png)

**Comment by ebwinters** [comment]
that's why we have a sorting endpoint https://corona.lmao.ninja/countries?sort=cases
