### ISSUE TITLE
Incorrect country sorting

### ISSUE THREAD

**Issue by Boom-Apps** [NovelCOVID/API#246]
With https://corona.lmao.ninja/countries?sort={cases} the sorting is no longer correct.  Italy and the United States have more cases like China, but China still comes first!

**Comment by nibble-4bits** [comment]
It does work for me if I remove the curly braces from the URL: https://corona.lmao.ninja/countries?sort=cases

**Comment by ebwinters** [comment]
that's how it is supposed to be. If you would like to improve the documentation, open a PR or an issue to do that
