### ISSUE TITLE
Ecuador province data

### ISSUE THREAD

**Issue by pablocarreraest** [NovelCOVID/API#248]
Hi love your work.

Just have a question:

How can help to add Ecuador province data to your dataset?

For now I have media source (that work with the government that give us that information)

What is the format you need so I can help providing that for my country?

I'm working on Tracker website for only my country. So I end up in this beautiful API you make but our data is incomplete. I can't consume your API and show the status of our country... to our people and the world.

If is posible any approach I will glad to work help us you can take all our data.

**Comment by ebwinters** [comment]
https://corona.lmao.ninja/v2/historical/ecuador
https://corona.lmao.ninja/countries/ecuador

**Comment by pablocarreraest** [comment]
> https://corona.lmao.ninja/v2/historical/ecuador
> https://corona.lmao.ninja/countries/ecuador

I mean province data for more complete information

like this:

```json
[
    {
        "country": "EC",
        "province": "Azuay",
        "updatedAt": "27/3/2020 17:30:00",
        "stats": {
            "confirmed": 42,
            "deaths": 0,
            "recovered": 0
        },
        "coordinates": {
            "latitude": "-2.9005499",
            "longitude": "-79.0045319"
        }
    },
    {
        "country": "EC",
        "province": "Cañar",
        "updatedAt": "27/3/2020 17:30:00",
        "stats": {
            "confirmed": 16,
            "deaths": 0,
            "recovered": 0
        },
        "coordinates": {
            "latitude": "-2.7397863",
            "longitude": "-78.86261"
        }
    }
]
```

Im currently working of the missing data.

But if you closed that mean you are not interest or just is no way to added...
