### ISSUE TITLE
fix server.js

### ISSUE THREAD

**Issue by ItsNash0** [NovelCOVID/API#25]
I run 
npm install
node server.js

and when I attempt to load /all I get this

> ➜  API git:(master) node server.js 
> Your app is listening on port 80
> (node:3391) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cases' of null
>     at /Users/itsnash0/Sites/API/server.js:149:10
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:3391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:3391) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ItsNash0** [comment]
how can I fix this to use the api?

**Comment by EliteDaMyth** [comment]
This is an issue because of the caching we use which is quick.db it's not an issue with the api itself. The thing updates itself every 10 minutes so it will be fixed if you keep the app running for 10 minutes. It's not optimised for self hosting. Thanks.
