### ISSUE TITLE
Country First and second name

### ISSUE THREAD

**Issue by gauravnewton** [NovelCOVID/API#251]
If a country name is of single word like USA  the get call https://corona.lmao.ninja/v2/historical/USA
working fine, But what if it contains two or more word like Turks and Caicos. Help me in that.

**Comment by gauravnewton** [comment]
I tried https://corona.lmao.ninja/v2/historical/Turks-and Caicos

**Comment by gowthamrm** [comment]
Try this, https://corona.lmao.ninja/countries/Turks

**Comment by buster95** [comment]
Ok, working on it

**Comment by ebwinters** [comment]
https://corona.lmao.ninja/countries/turks%20and%20caicos
