### ISSUE TITLE
Mistake on country name

### ISSUE THREAD

**Issue by innoving** [NovelCOVID/API#254]
Hello,

There is a mistake on this country name : **Coast d'ivoire** .... The right name is **Côte d'ivoire.**
Refence link : https://corona.lmao.ninja/countries
Thanks you advance

**Comment by buster95** [comment]
Working on it

**Comment by chroventer** [comment]
#257

**Comment by chroventer** [comment]
Fix: #258

**Comment by buster95** [comment]
> Fix: #258
Check my comment on your PR
