### ISSUE TITLE
Paging for countries

### ISSUE THREAD

**Issue by erichstark** [NovelCOVID/API#26]
It would be great to implement paging for /countries route because sometimes app that is consuming the resource could use a lot of memory.

What is the best approach to return number of defined countries?
For example /countries?num=10

**Comment by EliteDaMyth** [comment]
It seems unnecessary to me. Also if you were to define number of countries to return how would you be sure those are the countries you need. If you wanna fork this and run it you are open to do so. Closing for now

**Comment by erichstark** [comment]
I think you do not need exact countries for this. Because usually it is used as list so you want to scroll through them for example as infinity list.
