### ISSUE TITLE
Lat and Long return 0 for some items

### ISSUE THREAD

**Issue by DavidBarbaran** [NovelCOVID/API#269]
Request: https://corona.lmao.ninja/countries

Return lat and long 0 for:
Diamond Princess
MS Zaandam

Is this correct? Thanks :)

**Comment by Anish-Shobith** [comment]
Diamond Princess is a cruise Ship so probably yes

**Comment by ebwinters** [comment]
![](https://i.imgur.com/vOsl04l.gif)
the dude is closing this now
