### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [NovelCOVID/API#27]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the Open-Source-COVID-19 page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

https://weileizeng.github.io/Open-Source-COVID-19/

Cheers!

**Comment by EliteDaMyth** [comment]
This is awesome! Hmu on discord EliteDaMyth#0690 of you wanna get it onto my domain.

**Comment by WeileiZeng** [comment]
sounds good! I don't have discord. My twitter is https://twitter.com/WeileiZeng1992 or we can just discuss here. My data is in yaml format, but I would be willing to add a json copy

**Comment by WeileiZeng** [comment]
I see what you mean. If there are some pretty short domain, I would be happy to switch.

**Comment by WeileiZeng** [comment]
http://open-source-covid-19.weileizeng.com/

I finally decided to change the domain
