### ISSUE TITLE
Numbers aren't parsed correctly

### ISSUE THREAD

**Issue by stroncis** [NovelCOVID/API#274]
Lines:
https://github.com/NovelCOVID/API/blob/master/funcs/getWorldometers.js#L88
and
https://github.com/NovelCOVID/API/blob/master/funcs/getWorldometers.js#L94

While parsing, _parseFloat()_ strips number on comma and outputs 1, f.e.: `1,529.05` to `1`

Fix:
`parseFloat(casesPerOneMillion)` to `parseFloat(casesPerOneMillion.split(',').join(''))`
and
`parseFloat(deathsPerOneMillion)` to `parseFloat(deathsPerOneMillion.split(',').join(''))`

**Comment by ebwinters** [comment]
this was fixed, idk what happened - let me make a hotfix
