### ISSUE TITLE
Redis-server PORT config

### ISSUE THREAD

**Issue by saisk73** [NovelCOVID/API#276]
in config.json the port of redis-server is 6969 instead of 6379.
This is causing error in starting the server.
**[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6969**
Please Fix it.

**Comment by ebwinters** [comment]
Is the error local on your machine

**Comment by saisk73** [comment]
> Is the error local on your machine

The error is on ubuntu server 18.04.
To check whether its on my server i created another server but the error has still occurred.

**Comment by Anish-Shobith** [comment]
It's because redis server is not running on the port 6969

**Comment by ebwinters** [comment]
Where are you seeing this error I don’t even understand this issue. The server is running somewhere and it’s up fine

**Comment by Anish-Shobith** [comment]
> Where are you seeing this error I don’t even understand this issue. The server is running somewhere and it’s up fine 

They are trying to self host, the default port is 6379 of redis but in the config its mentioned 6969 so it's using that, instead of 6379. They need to change the config to work that's all

**Comment by ebwinters** [comment]
You wana make a PR for that dude

**Comment by saisk73** [comment]
> Where are you seeing this error I don’t even understand this issue. The server is running somewhere and it’s up fine

Its when i start the server node server.js.
I installed redis-server in linux the default port its running on is 6379. But in config.example.json redis port is 6969.

**Comment by saisk73** [comment]
> > Where are you seeing this error I don’t even understand this issue. The server is running somewhere and it’s up fine
> 
> They are trying to self host, the default port is 6379 of redis but in the config its mentioned 6969 so it's using that, instead of 6379. They need to change the config to work that's all

Yes that's all.😁

**Comment by ebwinters** [comment]
Ok dude, make the PR and I’ll merge it

**Comment by saisk73** [comment]
> Ok dude, make the PR and I’ll merge it

done 👍

**Comment by ebwinters** [comment]
I don’t see it

**Comment by saisk73** [comment]
> I don’t see it

Made a PR just now.
