### ISSUE TITLE
Accuracy and testing multiple sources

### ISSUE THREAD

**Issue by endepointe** [NovelCOVID/API#283]
I am only pulling from this api but I assume that the data is being provided by every participating hospital. Can someone direct me to see how the reports are being collected?

I've been building up a display tool here: 
https://github.com/endepointe/ende/blob/master/client/src/components/Covid.js

**Comment by ebwinters** [comment]
we scrape worldometers and use JHU data for time series

**Comment by endepointe** [comment]
I saw the readme and the sources being used. I should have specified wanting to know  *who* is inputting this data. This is probably not the correct platform to get the answer I am seeking. thank you for your answer though and keep up the good work!
