### ISSUE TITLE
Add UK county data

### ISSUE THREAD

**Issue by ebwinters** [NovelCOVID/API#285]
https://www.arcgis.com/apps/opsdashboard/index.html#/f94c3c90da5b4e9f9a0b19484dd4bb14

Add to countries/uk a `countyData` field, and we can begin building this functionality for others once we have time and sources

**Comment by EliteDaMyth** [comment]
@ebwinters not needed. arcgis provides an rest api too 
`https://services1.arcgis.com/0IrmI40n5ZYxTUrV/arcgis/rest/services/CountyUAs_cases/FeatureServer/0/query?f=json&where=TotalCases%20%3C%3E%200&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=TotalCases%20desc&resultOffset=0&resultRecordCount=1000&cacheHint=true`
