### ISSUE TITLE
Updated attribute the same for every country

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#286]
Wouldn't it be more helpful/useful to have the updated attribute actually reflect the last time the numbers of the country were updated? Now the updated attribute is just almost (just a few ms difference) the same for every country.

**Comment by buster95** [comment]
excellent observation, we haven't information about that by country, we only take server date information, I think should will remove that field for that endpoint is the same for all, has no sense

**Comment by S1MB10T3** [comment]
If anything you can update the attribute if the data from an country has changed. Definite a lot more resource intensive.

**Comment by ebwinters** [comment]
I don't get it what are you requesting @MarkSmit

**Comment by ebwinters** [comment]
closin for now

**Comment by MarkSmit** [comment]
The updated attribute in `/countries` Is the same for every country. It would be way more useful if it would give the actual time that the numbers of that country have been updated. For example, if Italy has not yet updated their numbers today, the updated attribute could display the time it was updated yesterday. And if Spain has updated its numbers than the updated attribute should reflect the moment that happened. That way the user of the API could show it’s users how recent the numbers are.

**Comment by EliteDaMyth** [comment]
@MarkSmit the number is the time the data was pulled from worldometers.

**Comment by MarkSmit** [comment]
@EliteDaMyth yeah, I know. But it should be the actual time that the numbers where updated. If a country has not updated today and the updated attribute says that it was updated 1 minute ago, than that is actually incorrect.

**Comment by MarkSmit** [comment]
@ebwinters could you please reopen this issue? if you need more information, please let me know.
