### ISSUE TITLE
Update Readme/Docs for Installation

### ISSUE THREAD

**Issue by S1MB10T3** [NovelCOVID/API#288]
Would be a nice idea to add info to the readme about installing the API for yourself for those who want to contribute. 

I recommend moving the info from `contrib.md` to the `README.md` or have a link to it in the readme to it. I can make a PR for either or if someone agrees.

**Comment by ebwinters** [comment]
hey dude, you can make a PR for this.
![](https://media1.giphy.com/media/ZCTZKfNl6ABGdqRCBR/giphy.gif?cid=ecf05e474fcb7f42ca757ccff8d6d4e52eb6afbe8f7efcfb&rid=giphy.gif)

**Comment by S1MB10T3** [comment]
PR created #291
