### ISSUE TITLE
Endpoint is not working

### ISSUE THREAD

**Issue by ebwinters** [NovelCOVID/API#29]
A query to the endpoint such as: https://corona.lmao.ninja/countries/usa returns plaintext `Country not found`

**Comment by benjamin-sommer** [comment]
Same here.

**Comment by Solweigdev** [comment]
Duplicate of #30

**Comment by silverhairs** [comment]
Fixed

**Comment by EliteDaMyth** [comment]
Fixed

**Comment by ebwinters** [comment]
Happening again rn
