### ISSUE TITLE
China is listed at the end of the list

### ISSUE THREAD

**Issue by O-r-D** [NovelCOVID/API#290]
Thank you so much for this awesome API.

So getting the /countries endpoint returns a list of all countries with cases ordered by the number of total cases for each country.

But China, for some reason, is appearing as the last Entry. And it surely should be in the top 5.

**Comment by ebwinters** [comment]
hey dude, just sort it https://corona.lmao.ninja/countries?sort=cases

![](https://i.giphy.com/media/TmQt53R5SoLDi/giphy.gif)

**Comment by O-r-D** [comment]
Having the ability to sort it solves this indeed.


I just wanted to indicate that something is went wrong, because the list is ordered by cases except for China.

Cheers
