### ISSUE TITLE
Allow frontend developers to integrate with real-time support

### ISSUE THREAD

**Issue by WinnersProx** [NovelCOVID/API#295]
I've just seen the way you guys managed to approach getting real-time data. However, when there's a change the users also have use ```setInterval``` to get the incoming data.

I would recommend using [Socket.io](https://socket.io/) to emit events for a better user experience

**Comment by EliteDaMyth** [comment]
An bidirectional communication channel is not necessary for the api. it would be easier for developers to use a setInterval too.
