### ISSUE TITLE
Some data is wrong value?

### ISSUE THREAD

**Issue by obolorhuu** [NovelCOVID/API#296]
I remembered that was okey two days ago, but now some data is wrong value. such us 
USA's today cases  just 333, but you know that https://www.worldometers.info/coronavirus/ shows +15,000  likewise, todayDeaths is same wrong.

**Comment by benjamin-sommer** [comment]
https://www.worldometers.info/coronavirus/ shows data for the world. There are around 16,000 new cases worldwide, not in the USA. If you go to https://www.worldometers.info/coronavirus/country/us, you can see that there have only been 6 new deaths and 333 new cases in the USA. I believe the data being returned from the API is correct.

Could you please check which API route you are calling?

This is from the US specific page:

![Screenshot 2020-03-30 at 14 07 55](https://user-images.githubusercontent.com/39101651/77916017-57ac7b00-7290-11ea-8dba-68130559ad52.png)

**Comment by EliteDaMyth** [comment]
seems to not be an issue :)
