### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by adamwojt** [NovelCOVID/API#3]
What's is your data source ? Do you store data and could you share it ? Are you scraping some website to get it ?

**Comment by ericzlmd** [comment]
> 
> 
> What's is your data source ? Do you store data and could you share it ? Are you scraping some website to get it ?

He's using GHO's datat API, which is WHO's

https://www.programmableweb.com/api/world-health-organization-gho-odata-rest-api-v10

**Comment by gabrielcosi** [comment]
What is the endpoint to get covid-19 stats? That api is huge

**Comment by javieraviles** [comment]
The api is scraping this website each 10 minutes:
https://www.worldometers.info/coronavirus/

**Comment by EliteDaMyth** [comment]
> The api is scraping this website each 10 minutes:
> https://www.worldometers.info/coronavirus/

This is the correct answer I'm closing this issue for now!

**Comment by muhammedmagdi** [comment]
@EliteDaMyth I just would like to ask if it is legal to scrap the data from this website? 
I see that they have licensing system with payment. I just would like to know.
