### ISSUE TITLE
Endoint returns empty array

### ISSUE THREAD

**Issue by aarons2222** [NovelCOVID/API#30]
https://corona.lmao.ninja/countries returns []

**Comment by benjamin-sommer** [comment]
Same error.

**Comment by Ramonet72** [comment]
Yes, I experienced the same. It may be https://www.worldometers.info/coronavirus/ changed the data format?

**Comment by simranz** [comment]
same error

**Comment by benjamin-sommer** [comment]
The selector "table#main_table_countries" returns nothing. The website format has changed, only showing two tables, "table#main_table_countries_today" and "table#main_table_countries_yesterday".

**Comment by duarteocarmo** [comment]
Same here :)

**Comment by simranz** [comment]
they've moved the main_table_countries from id to one of the classes of the table.

**Comment by MhndMousa** [comment]
Will try to make a pull request for that

**Comment by Solweigdev** [comment]
Same here :)

**Comment by benjamin-sommer** [comment]
PR done. https://github.com/NovelCOVID/API/pull/31

**Comment by Solweigdev** [comment]
@benjamin-sommer Why you close this PR ? Not working ?

**Comment by GowthamF** [comment]
Doesn't it need to be deployed?

**Comment by richardkeep** [comment]
Same here. My app https://github.com/richardkeep/covid-19 is broken.

**Comment by benjamin-sommer** [comment]
> @benjamin-sommer Why you close this PR ? Not working ?

Sorry, I re-opened it now.

**Comment by benjamin-sommer** [comment]
Can you please deploy it?

**Comment by benjamin-sommer** [comment]
Still not fixed. Hmmm...

**Comment by GaboMendez** [comment]
Same here 😪

**Comment by andretimm** [comment]
@benjamin-sommer  Maybe still need to deploy to https://corona.lmao.ninja

**Comment by benjamin-sommer** [comment]
> @benjamin-sommer Maybe still need to deploy to https://corona.lmao.ninja

I don't think so. The code is shown to be updated in GitHub. Maybe the 10 minute delay caused by the `setInterval` between scrapings is causing a wait. In 10 mins it should hopefully update.

**Comment by benjamin-sommer** [comment]
@Solweigdev can you temporarily change the `setInterval` to 10 seconds and then back, so we can see if the changes had any affect? Thanks

**Comment by Solweigdev** [comment]
Ok

**Comment by benjamin-sommer** [comment]
Thanks

**Comment by MhndMousa** [comment]
My localhost version seems to be working with @benjamin-sommer fix with no `setIntervals`. I wonder why is that not working with the endpoint

**Comment by benjamin-sommer** [comment]
Working now!

**Comment by benjamin-sommer** [comment]
Now the site is down.

**Comment by Solweigdev** [comment]
Oh yes ... :'(

**Comment by l-sugar** [comment]
up again 👍

**Comment by MhndMousa** [comment]
Host is down :/

**Comment by sajjadgrw1** [comment]
Web server is down.

**Comment by Solweigdev** [comment]
Up

**Comment by MhndMousa** [comment]
It's back up

**Comment by benjamin-sommer** [comment]
Up again!

**Comment by Solweigdev** [comment]
Now ... waiting 10minutes again

**Comment by benjamin-sommer** [comment]
It works for me in the browser and in my app.

**Comment by Valaia** [comment]
It's displaying data from a few days ago

**Comment by benjamin-sommer** [comment]
![Screenshot 2020-03-18 at 17 48 01](https://user-images.githubusercontent.com/39101651/76990962-be50a100-6940-11ea-8d2c-8bbb27999d55.png)

**Comment by thenamesweretakenalready** [comment]
Hoorah it's back up.

**Comment by l-sugar** [comment]
data is not accurate though

**Comment by MatYRicS** [comment]
https://corona.lmao.ninja/countries/[country-name]  dosen't work for me.

**Comment by benjamin-sommer** [comment]
> data is not accurate though

For me, it is not accurate in the browser, but strangely in my app it shows data from just a few minutes ago.

**Comment by Rv607x** [comment]
Data not accurate eg {"country":"Kenya","cases":3,"todayCases":0,"deaths":0,"todayDeaths":0,"recovered":0,"critical":0}
Kenya should have like 7 cases today

**Comment by erichstark** [comment]
I have also problem with call for a country and also data seem to be outdated.

**Comment by thenamesweretakenalready** [comment]
I've also noticed that they all seem to be outdated. It looks like all countries are (?)

**Comment by l-sugar** [comment]
![Screenshot 2020-03-18 at 18 52 29](https://user-images.githubusercontent.com/16088875/76991308-a6c9e600-6949-11ea-8342-2e8e071d34dd.png)
my telegram bot queries /countries and is giving outdated data

**Comment by Kvanrooyen** [comment]
Host is down again for me

**Comment by thenamesweretakenalready** [comment]
Maybe the dev is hosting saved prior data while they pump out an actual fix. If that's the case then we'll  probably have to wait a while.

**Comment by benjamin-sommer** [comment]
My BitBar plugin is giving updated data for some reason. 
![Screenshot 2020-03-18 at 17 48 01](https://user-images.githubusercontent.com/39101651/76991380-69f9f100-6941-11ea-8088-a48dbb662663.png)

**Comment by sajjadgrw1** [comment]
<img width="1108" alt="Screen Shot 2020-03-18 at 10 52 56 PM" src="https://user-images.githubusercontent.com/4892234/76991364-4a77be00-696b-11ea-9eb0-68955448fc35.png">

**Comment by Solweigdev** [comment]
![image](https://user-images.githubusercontent.com/37271302/76991482-f4dee980-6949-11ea-8dc3-38c860de5911.png)

**Comment by benjamin-sommer** [comment]
That data looks up to date.

**Comment by gitmonox** [comment]
Is not u´p to date
{
"country": "Brazil",
"cases": 203,
"todayCases": 3,
"deaths": 0,
"todayDeaths": 0,
"recovered": 2,
"critical": 2

SOURCE

Brazil | 367 | +21
-- | -- | --

**Comment by MhndMousa** [comment]
Not for me

![image](https://user-images.githubusercontent.com/15264541/76991759-b7f60100-690f-11ea-9c40-dc799bd82364.png)

**Comment by thenamesweretakenalready** [comment]
Still not up to date according to https://www.worldometers.info/coronavirus/#countries

**Comment by PablockDA** [comment]
https://corona.lmao.ninja/countries/[country] Also is not working.

**Comment by EliteDaMyth** [comment]
Fixed

**Comment by MhndMousa** [comment]
Not for me
![image](https://user-images.githubusercontent.com/15264541/76991884-f4c1f800-690f-11ea-8c5a-28bf80ee8e6b.png)

**Comment by gitmonox** [comment]
Still not up to date

**Comment by Solweigdev** [comment]
> 
> 
> Not for me
> ![image](https://user-images.githubusercontent.com/15264541/76991884-f4c1f800-690f-11ea-8c5a-28bf80ee8e6b.png)

Wait updating maybe ?

**Comment by thenamesweretakenalready** [comment]
still not up to date for me either.

**Comment by benjamin-sommer** [comment]
Updated now!

**Comment by gitmonox** [comment]
Empty array

**Comment by benjamin-sommer** [comment]
Now just empty array

**Comment by thenamesweretakenalready** [comment]
Now I'm back to the empty response :(

**Comment by karolosk** [comment]
Since you are on it, on the latest fix - which as previously mentioned again does not work - could you also check the last updated field, which was provided earlier?

**Comment by sajjadgrw1** [comment]
Empty response. :(

**Comment by thenamesweretakenalready** [comment]
Do you mean https://corona.lmao.ninja/all ?

**Comment by thenamesweretakenalready** [comment]
Because I'm getting up to date data from that

**Comment by benjamin-sommer** [comment]
Web server down :-(

**Comment by sajjadgrw1** [comment]
No. /all was working. But /countries was not working. And now the server is down again.

**Comment by thenamesweretakenalready** [comment]
Damn it the server's down again.

**Comment by thenamesweretakenalready** [comment]
It's back up I think

**Comment by thenamesweretakenalready** [comment]
Never mind, but somehow I just got a response from the webserver - maybe momentarily up?

**Comment by thenamesweretakenalready** [comment]
Webserver back up - part one of two in the solution, now getting a different message from the /countries endpoint: `Cannot GET /countries`

**Comment by thenamesweretakenalready** [comment]
Cloudflare http error 521 now :(

**Comment by thenamesweretakenalready** [comment]
Looks like it's fixed now, nice. Data seems to be up to date. Running commentary is now closed until further notice.

**Comment by richardkeep** [comment]
I have recreated the **/countries** API using the Lumen (PHP) framework. 

Check it out guys: https://github.com/richardkeep/covid-19-api
