### ISSUE TITLE
[Feature Request] Adding API call for historical data for multiple countries

### ISSUE THREAD

**Issue by alekspopovic** [NovelCOVID/API#303]
Having an API call that would pull historical data for multiple countries at once would be extremely useful. Something like https://corona.lmao.ninja/v2/historical/usa,italy,france for names as parameters, or https://corona.lmao.ninja/v2/historical/840,380,250 for ids as parameters, or however you choose to implement it.

**Comment by ebwinters** [comment]
great idea, dude
![](https://i.giphy.com/media/tyxovVLbfZdok/giphy.gif)

**Comment by oumaabde** [comment]
good  idea
