### ISSUE TITLE
https://corona.lmao.ninja/v2/historical/all => response format

### ISSUE THREAD

**Issue by tobiu** [NovelCOVID/API#309]
https://corona.lmao.ninja/v2/historical/:country

response:
```
{
    country: 'X',
    province: null,
    timeline: data
}
```

https://corona.lmao.ninja/v2/historical/all

response:
```
data
```

this is not consistent and it would be nice if this could get changed to:

response:
```
{
    country: null, // or 'all'
    province: null,
    timeline: data
}
```

the important part is to put the data into the timeline prop.

thx!

**Comment by ebwinters** [comment]
that would be introducing a breaking change for many of the APIs users. I agree it would be nice to have consistency but I don't see a reason to do this right now if it's documented. Just handle it on your end.
