### ISSUE TITLE
[Feature Request] Adding API call for historical data for Period

### ISSUE THREAD

**Issue by fanfaron2004** [NovelCOVID/API#310]
Having an API call that would pull historical data (all or countries) for a period (start Date/ end Date). Tks a lot.

**Comment by buster95** [comment]
Hey @ebwinters can I work on this?

**Comment by ebwinters** [comment]
Sure ting mate

**Comment by ebwinters** [comment]
This seems like it could get very complex, and isn’t needed by the API since we supply the data and they can filter by date on their end. If the code gets too complex and makes room for regression, id be against this feature.

**Comment by ebwinters** [comment]
This could definitely create a lot of regression and is easy to do on client side ...😳

**Comment by fanfaron2004** [comment]
thank you for your response, but I made the request because the client side is limited in memory

**Comment by ebwinters** [comment]
what do you mean limited memory. This is an API, it aggregates and supplies data. This seems like a very specialized use case, which can be done on the user's end by looping over the data and filtering out dates outside of a certain range.

**Comment by fanfaron2004** [comment]
sure, it’s for watch device with 64k memory :-)

**Comment by fanfaron2004** [comment]
or may be per month?
