### ISSUE TITLE
[Feature Request] Adding API call for all statistics data for Numbre countries

### ISSUE THREAD

**Issue by oumaabde** [NovelCOVID/API#311]
Having an API call that would pull all statistics https://corona.lmao.ninja/all
 add numbre affected countries for exemple
{
  cases: 805377,
  deaths: 39469,
  recovered: 172436,
  updated: 1585665307196,
  active: 593472,
  affected_countries: 190
}

**Comment by benjamin-sommer** [comment]
https://github.com/NovelCOVID/API/pull/312

**Comment by benjamin-sommer** [comment]
#312

**Comment by benjamin-sommer** [comment]
@oumaabde I added `affectedCountries` to https://corona.lmao.ninja/all.

**Comment by oumaabde** [comment]
> @oumaabde I added `affectedCountries` to https://corona.lmao.ninja/all.

Thank you for all support and speed to reply and development

**Comment by benjamin-sommer** [comment]
No problem!
