### ISSUE TITLE
Add yesterday data or Delta

### ISSUE THREAD

**Issue by akanshgulati** [NovelCOVID/API#314]
Currently we can only find increase of deaths and total number of cases and with the current API for data, we can not calculate `change in active cases and recovered cases`. So, please add those fields like `todayRecoveredCases` or `todayActiveCases` in current API or share the yesterday data too.

**Comment by akanshgulati** [comment]
@ebwinters Please let me if you need help on closing this PR, would love to contribute.

**Comment by ebwinters** [comment]
It’s already done and the code is already there, I’m just going to add the endpoint

**Comment by akanshgulati** [comment]
@ebwinters Can you please share ETA on this? Building a feature and it dependent on that. Would be a great help if you can provide it.
