### ISSUE TITLE
How to access historical data of non-countries

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#326]
How can you access the `/v2/historical/` data from for example the Diamond Princess?
I tried `Diamond%20Princess`, `Diamond+Princess` and `Diamond` with no response, while the data exists in the endpoint

**Comment by buster95** [comment]
Let me check

**Comment by MarkSmit** [comment]
@buster95 This problem is there again. Diamond Princess and MS Zaandam are inaccessible.

**Comment by buster95** [comment]
@MarkSmit wait for publish on server

**Comment by buster95** [comment]
This is on my local I think someone touched the code that I've uploaded
![image](https://user-images.githubusercontent.com/15637669/78377116-7068a980-758c-11ea-9c4a-47b2a4bf5033.png)
