### ISSUE TITLE
/jhucsse not returning US data anymore

### ISSUE THREAD

**Issue by chrisvalmonte** [NovelCOVID/API#333]
Data fetched from https://corona.lmao.ninja/jhucsse is no longer returning US data.

Also, two items in the list ("US" and "Canada") have "Recovered" as a province and zero'd out longitude and latitude coordinates:
<img width="598" alt="Screen Shot 2020-04-01 at 5 55 10 PM" src="https://user-images.githubusercontent.com/22405692/78199991-19ef5400-7442-11ea-9391-5993d929a075.png">

**Comment by chrisvalmonte** [comment]
Also check out your work in action @ www.covid19-confirmed.com. Thanks for the APIs!!!

**Comment by ebwinters** [comment]
fixed for now, issue on JHU's end. Until then data will be from most recent upload, 3/31
