### ISSUE TITLE
US data gone?

### ISSUE THREAD

**Issue by mayankverr** [NovelCOVID/API#334]
It was working fine a couple of hours ago but now when I visit [https://corona.lmao.ninja/v2/jhucsse](https://corona.lmao.ninja/v2/jhucsse), I see just one object with the country name US. Is it under maintainence or something?

![Annotation 2020-04-02 062757](https://user-images.githubusercontent.com/54323745/78200180-7470ca80-74ab-11ea-8ba7-a082624b6bfe.jpg)

**Comment by ebwinters** [comment]
see my comment on #333
