### ISSUE TITLE
(node:8283) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by n-haddag** [NovelCOVID/API#339]
> `
(node:8283) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at fillResult (/home/nhaddag/API/funcs/getWorldometers.js:96:83)
    at Object.getYesterday (/home/nhaddag/API/funcs/getWorldometers.js:133:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8283) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8283) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8283) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at fillResult (/home/nhaddag/API/funcs/getWorldometers.js:96:83)
    at Object.getCountries (/home/nhaddag/API/funcs/getWorldometers.js:115:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8283) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
`

**Comment by karokh94** [comment]
@n-haddag 

in API/funcs/getWorldometers.js
change:
`const totalColumns = 11;`
to:
`const totalColumns = 10;`

**Comment by EliteDaMyth** [comment]
https://github.com/NovelCOVID/API/commit/3db3a27924322e7b2a9921fbfeee335e550e7fd4
