### ISSUE TITLE
Countries

### ISSUE THREAD

**Issue by boraoksuzoglu** [NovelCOVID/API#34]
Countries results doesn't work.

Result: [ ]

Can you fix this?

**Comment by benjamin-sommer** [comment]
https://github.com/NovelCOVID/API/issues/30

**Comment by l-sugar** [comment]
fix was just merged into master

**Comment by Solweigdev** [comment]
> 
> 
> fix was just merged into master

Don't work aha

**Comment by ChristianPredoianu** [comment]
Still don't work guys

**Comment by elabayoub** [comment]
Same issue for my guys

**Comment by gitmonox** [comment]
Same Here

**Comment by smdedar** [comment]
blank array

**Comment by constanzaccg** [comment]
It's working now, but the endpoint to get the data by country still doesn't work :(

**Comment by rizki5411** [comment]
now server error **Error 521** hahaha

**Comment by elabayoub** [comment]
Server error OK, Countries OK, thanks

**Comment by Krato** [comment]
Nom, data is not correct. For spain at least

**Comment by silverhairs** [comment]
> > fix was just merged into master
> 
> Don't work aha

Really??  I don't know but it's working for me now. you can also try [this one](https://coronavirus-tracker-api.herokuapp.com/v2/locations)

**Comment by dicedtomatoreal** [comment]
We're working on it, due to our source updating their website stuff has changed :)

**Comment by rizki5411** [comment]
i think developers work hard now to fix this problems, spirit!!

**Comment by Krato** [comment]
Perfect. Thanks!

**Comment by javieraviles** [comment]
I want you all to keep using this api, not mine, which is a fork, but JUST meanwhile this one is getting fixed, can use mine 

https://github.com/javieraviles/covidAPI

is exactly the same without country specific nor sorting

**Comment by erichstark** [comment]
The source code is working, just the deployment not. If you try it at localhost, everything is okay.

**Comment by Krato** [comment]
> I want you all to keep using this api, not mine, which is a fork, but JUST meanwhile this one is getting fixed, can use mine
> 
> https://github.com/javieraviles/covidAPI
> 
> is exactly the same without country specific nor sorting

Perfect temp fix. 

> Por cierto. He visto que eres español. Pásate si quieres por el repo que he creado https://github.com/Krato/covid19ESP

**Comment by elabayoub** [comment]
> > I want you all to keep using this api, not mine, which is a fork, but JUST meanwhile this one is getting fixed, can use mine
> > https://github.com/javieraviles/covidAPI
> > is exactly the same without country specific nor sorting
> 
> Perfect temp fix.
> 
> > Por cierto. He visto que eres español. Pásate si quieres por el repo que he creado https://github.com/Krato/covid19ESP

Why not using other branche for devs and master to stay safe and sound ? just saying; thanks

**Comment by erichstark** [comment]
> > I want you all to keep using this api, not mine, which is a fork, but JUST meanwhile this one is getting fixed, can use mine
> > https://github.com/javieraviles/covidAPI
> > is exactly the same without country specific nor sorting
> 
> Perfect temp fix.
> 
> > Por cierto. He visto que eres español. Pásate si quieres por el repo que he creado https://github.com/Krato/covid19ESP

This is not working also to fetch specific country

**Comment by javieraviles** [comment]
country specific endpoint coming in 5 min, will have a 2min downtime, then working with country specific endpoint too :)

**Comment by javieraviles** [comment]
https://github.com/javieraviles/covidAPI/runs/507046789?check_suite_focus=true

**Comment by benjamin-sommer** [comment]
@elabayoub Using a different dev branch would not stop the errors on the master branch.

**Comment by elabayoub** [comment]
@benjamin-sommer thanks for your answer, but it would atleast limit bugs for future features not talking about actual situation.

**Comment by crpozo** [comment]
but what is the point if the json doesnt work haha

**Comment by dicedtomatoreal** [comment]
Our host died, we are moving it to a better host sorry for the downtime..

**Comment by javieraviles** [comment]
just added country-specific endpoint while the fix 

https://coronavirus-19-api.herokuapp.com/all
https://coronavirus-19-api.herokuapp.com/countries
https://coronavirus-19-api.herokuapp.com/countries/spain

**Comment by benjamin-sommer** [comment]
> just added country-specific endpoint while the fix
> 
> https://coronavirus-19-api.herokuapp.com/all
> https://coronavirus-19-api.herokuapp.com/countries
> https://coronavirus-19-api.herokuapp.com/countries/spain

Back up!

**Comment by dicedtomatoreal** [comment]
Thanks for waiting, its up now have fun tracking the virus.
