### ISSUE TITLE
(node:5921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by IlyesBenarroum** [NovelCOVID/API#340]
(node:5921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
    at getCellData (/home/iliesbenarroum/Downloads/API-master/funcs/getWorldometers.js:22:8)
    at fillResult (/home/iliesbenarroum/Downloads/API-master/funcs/getWorldometers.js:85:41)
    at Object.getYesterday (/home/iliesbenarroum/Downloads/API-master/funcs/getWorldometers.js:133:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by karokh94** [comment]
@IlyesBenarroum 

in API/funcs/getWorldometers.js
change:
`const totalColumns = 11;`
to:
`const totalColumns = 10;`

**Comment by EliteDaMyth** [comment]
https://github.com/NovelCOVID/API/commit/3db3a27924322e7b2a9921fbfeee335e550e7fd4
fixed
