### ISSUE TITLE
Missing data from today cases

### ISSUE THREAD

**Issue by bojczmac** [NovelCOVID/API#341]
Today cases value is 0. Which is not correct comparing it to the source data.

**Comment by vasanianil** [comment]
Yup, pls fix asap.

**Comment by vasanianil** [comment]
Thanks, Fixed

**Comment by EliteDaMyth** [comment]
https://github.com/NovelCOVID/API/commit/3db3a27924322e7b2a9921fbfeee335e550e7fd4
fixed
