### ISSUE TITLE
no update api

### ISSUE THREAD

**Issue by artscripts** [NovelCOVID/API#342]
Data is not updated GET Country  "url": "https://corona.lmao.ninja/countries/RU",

old values shown

**Comment by anmn85** [comment]
Dear admin,

Just to info the data from API not updated.

Thank you

**Comment by EliteDaMyth** [comment]
https://github.com/NovelCOVID/API/commit/3db3a27924322e7b2a9921fbfeee335e550e7fd4

**Comment by anmn85** [comment]
Thank you admin, really appreciate it. May god bless you
