### ISSUE TITLE
Query multiple countries

### ISSUE THREAD

**Issue by colbyfayock** [NovelCOVID/API#345]
I was asked about a use case where someone would like to make a clone of http://my-coronavirus-map.netlify.com/ which uses your API for a specific continent which includes multiple countries. Would it be possible to use the `/countries/{query}` endpoint with a delimited list of country codes?

for instance, if I wanted to look up North America, I would be able to do something like `/countries/us,ca,mx` theoretically

In the meantime, I'm just going to do a static list of the countries and filter the data which isn't bad, but thought that might be a nice native API feature.

Thanks

**Comment by ebwinters** [comment]
we have this ability for the historical endpoint, would be nice to have for countries too
