### ISSUE TITLE
Wrong country names in history data

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#346]
Some countries are spelled completely different in `/v2/histoical` than in `/countries`, some examples:
- 'faroe islands' instead of 'Faeroe Islands'
- 'macau' instead of 'Macao'
- 'curacao' instead of 'Curaçao'
- 'st martin' instead of 'Saint Martin'
- 'Congo (Kinshasa)' instead of 'DRC'

**Comment by buster95** [comment]
I'm checking this
