### ISSUE TITLE
Some countries' historical data can't be accessed by iso2

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#347]
Countries that can't be accessed by `/v2/historical/{{ ISO2 }}` are for example:
- Brunei (BN)
- Bolivia (BO)
- Belarus (BL)
- Chad (TC)

**Comment by ebwinters** [comment]
right on dude, i'll fix it today

**Comment by buster95** [comment]
@ebwinters I can check this

**Comment by ebwinters** [comment]
Go for it

**Comment by buster95** [comment]
was fixed I gonna open a new PR

**Comment by MarkSmit** [comment]
Taiwan (TW) also doesn't work, the name of Taiwan is also displayed as 'Taiwan*'

**Comment by ebwinters** [comment]
@buster95  I need merge access to PR
