### ISSUE TITLE
not found province doesn't return 404

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#354]
When searching `/v2/historical/US/blabla` it returns a 200 status not a 404 status.
It also gives an `err` instead of `message`, which you will get at `/v2/historical/blabla`

**Comment by ebwinters** [comment]
github is down

**Comment by MarkSmit** [comment]
@ebwinters Yes, I know, but that's not the problem. When the province is not found it should also return a 404.

**Comment by ebwinters** [comment]
Oh yea gotta uniform it. Will re open this issue after my nap
