### ISSUE TITLE
/jhucsse not returning recovered data for US

### ISSUE THREAD

**Issue by chrisvalmonte** [NovelCOVID/API#356]
Data fetched from `https://corona.lmao.ninja/jhucsse` has zero'd out "recovered" stat for all items with "US" as the "country"

<img width="494" alt="Screen Shot 2020-04-02 at 4 31 26 PM" src="https://user-images.githubusercontent.com/22405692/78309285-69478a00-74ff-11ea-9db4-886a1f2df473.png">
<img width="1243" alt="Screen Shot 2020-04-02 at 4 29 13 PM" src="https://user-images.githubusercontent.com/22405692/78309247-5339c980-74ff-11ea-8041-427d7107215a.png">

However, data fetched from `https://corona.lmao.ninja/countries?country=USA` shows that total recovered is ~10k right now

**Comment by benjamin-sommer** [comment]
The most likely cause of this issue is that not every city/province provides data on recovered patients. The US-wide figure for recovered cases is not a definitive number, it can only sum all the cities/provinces that have provided the data.

**Comment by ebwinters** [comment]
the data source is giving us this data
