### ISSUE TITLE
Not updated

### ISSUE THREAD

**Issue by DonPramis** [NovelCOVID/API#361]
https://google.com/covid19-map/?hl=en 

The Above link show the updated statistics

**Comment by Anish-Shobith** [comment]
Its fetching from the same site from which this API fetches ? if you scroll down it says About this data its fetching from WHO site which is from where this API also fetches the data not sure if you are asking to update to that link which could be a whole rewrite in the API

**Comment by ebwinters** [comment]
we scrape data on a time schedule do you think we are hitting these sites every request we get? That would be nearly 100,000,000 reqs a day of traffic mate.
