### ISSUE TITLE
provinces with comma unaccessible

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#365]
A province is called "bonaire, sint eustatius and saba" in `/v2/historical`, which is the "Caribbean Netherlands" in `/countries` is not accessible because of the comma in the name.
So `/v2/historical/NL/bonaire%2C%20sint%20eustatius%20and%20saba` won't work, `/v2/historical/NL/BX` and `/v2/historical/NL/Caribbean%20Netherlands` neither.

**Comment by EliteDaMyth** [comment]
#350 please merge this issue with that. seems similar. dont clutter up issues section

**Comment by MarkSmit** [comment]
@EliteDaMyth This is a very different issue than #350, and #350 is fixed, so this one should be reopened to get fixed.

**Comment by ebwinters** [comment]
I agree, it is different enough to be its own issue

**Comment by ebwinters** [comment]
i'll deal with it tomorrow, unless anyone else wants to make a PR :)

**Comment by puf17640** [comment]
@ebwinters we could exchange the comma seperator by a semicolon or |

**Comment by ebwinters** [comment]
PR closes this allows you to separate countries by `,` or `|`, but you must choose one. I don't want to deprecate current functionality with the `,`
