### ISSUE TITLE
field 'updated' on https://corona.lmao.ninja/countries

### ISSUE THREAD

**Issue by JosVermoesen** [NovelCOVID/API#366]
I hope field updated can give time stamp of the latest changes for given country. Shows now same time in milliseconds from your latest  generating.  Yet, great work you do

**Comment by EliteDaMyth** [comment]
it is an EPOCH timestamp. if you are in javascript use 
new Date(timestamp)

**Comment by EliteDaMyth** [comment]
google to learn more about Epoch
