### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by gabrielcosi** [NovelCOVID/API#37]
In worldometers.info China has 80,894 total cases, API shows 80880

**Comment by EliteDaMyth** [comment]
Updates every 10 minutes.

**Comment by InvenceSaltillo** [comment]
Yes, the data is incorrect, on the update date it shows me December 31, 1969

**Comment by gabrielcosi** [comment]
Peru yesterday was in 117, now is in 145, why it shows 71
