### ISSUE TITLE
states endpoint doesnt support sorting

### ISSUE THREAD

**Issue by puf17640** [NovelCOVID/API#380]
as title says.

**Comment by benjamin-sommer** [comment]
Working on this right now

**Comment by puf17640** [comment]
@benjamin-sommer if youre already working on this, could you also add an endpoint for getting individual states with /states/{state}

**Comment by benjamin-sommer** [comment]
Sure, I'll take a look.

**Comment by benjamin-sommer** [comment]
closes #381
