### ISSUE TITLE
Add Global Historical API

### ISSUE THREAD

**Issue by ianvizarra** [NovelCOVID/API#386]
Only per country is available in Historical API. 

`v2/history` -> display all countries with timelines
`v2/history/:country` -> display one country with timeline

`v2/history/world` -> display sum of all countries timeline per day
```json
"timeline": {
     "cases": {
           "1/22/20": 10000,
           "1/23/20": 20000,
           "1/24/20": 30000,
           "1/25/20": 40000,
           "1/26/20": 50000,
           "1/27/20": 90000,
           "1/28/20": 100000,
            ...

**Comment by buster95** [comment]
Hey dude check this https://corona.lmao.ninja/v2/historical/all

**Comment by ianvizarra** [comment]
Thanks @buster95
