### ISSUE TITLE
[Documentation] Check endpoints on docs

### ISSUE THREAD

**Issue by buster95** [NovelCOVID/API#387]
![image](https://user-images.githubusercontent.com/15637669/78418756-9d54a500-75fc-11ea-8126-8522418371a8.png)

**Comment by nibble-4bits** [comment]
Oh that's my bad! Let me fix that

**Comment by nibble-4bits** [comment]
Turns out you can't describe query parameter as part of the URL:
https://stackoverflow.com/a/30252104

I'll create a pull request fixing this error soon

**Comment by EliteDaMyth** [comment]
@all-contributors please add @nibble-4bits for docs
