### ISSUE TITLE
Fix your stats

### ISSUE THREAD

**Issue by Dieknon** [NovelCOVID/API#391]
Currently the bot counts "World" as a separate country, thus doubling the numbers. It really shouldn't. There aren't 2260000 confirmed infected.

**Comment by ustaslive** [comment]
Agree. And it's inconsistent to have 'World' as a country. This approach will make people think that they can request countries "Africa", "Europe", etc and other areas

**Comment by vBm** [comment]
`World` column is an easy way to populate more data for `all` endpoint and close #394 :)
