### ISSUE TITLE
standardize endpoints 

### ISSUE THREAD

**Issue by puf17640** [NovelCOVID/API#398]
- [x] /yesterday is still returning the world row from worldometers
- [x] /yesterday does not support sorting
- [x] /yesterday/{country} is missing

- [x] /states does not support sorting
- [x] /states/{state} is missing

**Comment by puf17640** [comment]
@ebwinters thanks! I will wait for you to fix this issue and then push the updated node api wrapper

**Comment by puf17640** [comment]
- /v2/jhucsse/counties/{county} returns an array instead of an object

**Comment by nibble-4bits** [comment]
@ebwinters Could I work on bullets 2 and 3?

**Comment by ebwinters** [comment]
sure @nibble-4bits  I can do states

**Comment by nibble-4bits** [comment]
Thanks man, I'll get to work then

**Comment by smilingchemist** [comment]
Would it be possible to add yesterday/all? Thank you!
