### ISSUE TITLE
(node:469) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by fqriss** [NovelCOVID/API#4]
Full error:
`(node:469) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of null
at Timeout.setInterval [as _onTimeout] (/app/server.js:10:556)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)`

Code:
```javascript
var getcountries=setInterval(async()=>{let e;try{200!==(e=await axios.get("https://www.worldometers.info/coronavirus/")).status&&console.log("Error",e.status)}catch(e){return null}const t=[],r=cheerio.load(e.data)("table#main_table_countries").children("tbody").children("tr").children("td");for(let e=0;e<r.length-8;e+=1){const a=r[e];if(e%8==0){let e=a.children[0].data||a.children[0].children[0].data||a.children[0].children[0].children[0].data||a.children[0].children[0].children[0].children[0].data||"";0===(e=e.trim()).length&&(e=a.children[0].next.children[0].data||""),t.push({country:e.trim()||""})}if(e%8==1){let e=a.children[0].data||"";t[t.length-1].cases=parseInt(e.trim().replace(/,/g,"")||"0",10)}if(e%8==2){let e=a.children[0].data||"";t[t.length-1].todayCases=parseInt(e.trim().replace(/,/g,"")||"0",10)}if(e%8==3){let e=a.children[0].data||"";t[t.length-1].deaths=parseInt(e.trim().replace(/,/g,"")||"0",10)}if(e%8==4){let e=a.children[0].data||"";t[t.length-1].todayDeaths=parseInt(e.trim().replace(/,/g,"")||"0",10)}if(e%8==6){let e=a.children[0].data||0;t[t.length-1].recovered=parseInt(e.trim().replace(/,/g,"")||0,10)}if(e%8==7){let e=a.children[0].data||"";t[t.length-1].critical=parseInt(e.trim().replace(/,/g,"")||"0",10)}}db.set("countries",t),console.log("Updated The Countries",t)},6e4);
```

**Comment by javieraviles** [comment]
To fix it go to `unminified.js`, lines 69-76, and change to

`  const totalColumns = 9;
  const countryColIndex = 0;
  const casesColIndex = 1;
  const todayCasesColIndex = 2;
  const deathsColIndex = 3;
  const todayDeathsColIndex = 4;
  const curedColIndex = 5;
  const activeColIndex = 6;
  const criticalColIndex = 7;`

Web from were the api scraps changed

**Comment by fqriss** [comment]
Still returning the same error.

**Comment by javieraviles** [comment]
Checkout my fork, there is surely working:
https://github.com/javieraviles/covidAPI

I fixed the indexes.

**Comment by EliteDaMyth** [comment]
Fixed in main repo too
