### ISSUE TITLE
Add countryInfo for Falkland Islands

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#403]
please add the countryInfo for Falkland Islands:
 - id: 238
- iso2: FK
- iso3: FLK

**Comment by buster95** [comment]
Let me check

**Comment by buster95** [comment]
you can search for 
![image](https://user-images.githubusercontent.com/15637669/78459812-f2ce9780-7678-11ea-925b-07a14de84230.png)
or
![image](https://user-images.githubusercontent.com/15637669/78459816-fe21c300-7678-11ea-9c6c-f2eb56e2de2d.png)
