### ISSUE TITLE
States Method for Each country 

### ISSUE THREAD

**Issue by mdudigam** [NovelCOVID/API#405]
Could you please develop and publish a method to get states from each country. Currently there is only one method to get the states specific to USA but not for all the countries.

**Comment by mdudigam** [comment]
Hey Ethan, why this issue was closed ? Could you please help me with the method to get all states from each county or India (at least).

**Comment by ebwinters** [comment]
don't have data source

**Comment by mdudigam** [comment]
there is a data source available for india.


https://coronaindia.in/india-stats

would you be able to add an api only for india?

Thanks,
*Mahesh*
