### ISSUE TITLE
Total tests and tests per one million

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#408]
https://www.worldometers.info/coronavirus/ added two new columns to the table, Total tests and tests/ 1M pop. Is it possible to make them available in the API?

**Comment by ebwinters** [comment]
yea, but this is an open source repo. You can make a pull request.

**Comment by benjamin-sommer** [comment]
I'll start work on this

**Comment by benjamin-sommer** [comment]
https://github.com/NovelCOVID/API/pull/419
