### ISSUE TITLE
Wrong values for Nepal

### ISSUE THREAD

**Issue by Bassem-Belkhir** [NovelCOVID/API#41]
Values for Nepal gives {"country":"Nepal","cases":1,"todayCases":0,"deaths":0,"todayDeaths":0,"recovered":1,"critical":0}
while https://www.worldometers.info/coronavirus/ gives other values

**Comment by filipemanuelofs** [comment]
Can you provide some example? Here's image of worldometers.info about Nepal.

![image](https://user-images.githubusercontent.com/1047292/77025082-ff5faa00-696e-11ea-97de-f299cba56662.png)

**Comment by psmeeta** [comment]
[ https://www.worldometers.info/coronavirus/]( https://www.worldometers.info/coronavirus/) gives the same value.

**Comment by EliteDaMyth** [comment]
Same as worldometers.
