### ISSUE TITLE
Include CSSE new country mapping table

### ISSUE THREAD

**Issue by payamazadi** [NovelCOVID/API#414]
CSSE is publishing a table that maps their country names to ISO2/3 names, and adds other fields

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv

We should add a new consumption for this. Should be easy to add in a data fetch for this and throw it into Redis. I can probably submit a PR for this..

**Comment by ebwinters** [comment]
We already support ios2/3 codes in our code base, I don't see a purpose to using theirs when we already have all the info.
