### ISSUE TITLE
wat is the purpose of "test" data states in the API

### ISSUE THREAD

**Issue by DutchmanNL** [NovelCOVID/API#429]
does it reflect any official value or is it just test data ?

https://github.com/NovelCOVID/API/commit/f40cfab3e8bb3235ccf325c6acc773cfd3dc4def

**Comment by benjamin-sommer** [comment]
The `test` value shows the total number of covid-19 tests taken globally. It reflects the `Total Tests` column in the table at https://www.worldometers.info/coronavirus/.

**Comment by DutchmanNL** [comment]
> The `test` value shows the total number of covid-19 tests taken globally. It reflects the `Total Tests` column in the table at https://www.worldometers.info/coronavirus/.

thank you !
