### ISSUE TITLE
Endpoints have no data

### ISSUE THREAD

**Issue by silverhairs** [NovelCOVID/API#43]
https://corona.lmao.ninja/countries is returning an empty array and https://corona.lmao.ninja/all is just returning 
 `{
"updated": 1584576028335
}`

**Comment by DavidCDCB** [comment]
Why has this been so frequent? Are there more changes in the source of information?

**Comment by elabayoub** [comment]
Maybe scraping changes overtime

**Comment by DavidCDCB** [comment]
> Maybe scraping changes overtime

excuse my ignorance on the subject, is there a way to avoid this kind of setback automatically?

**Comment by ooanishoo** [comment]
i'm having the same issue

**Comment by gitmonox** [comment]
Empty Array

**Comment by dicedtomatoreal** [comment]
The source is being updated, which we dont have control over :|

**Comment by elabayoub** [comment]
> > Maybe scraping changes overtime
> 
> excuse my ignorance on the subject, is there a way to avoid this kind of setback automatically?

the project owner is scraping from original website the table with id 'main_table_countries_today' so if id got changed or any targeted tag, result wont come in; in other words you cant control the main source of data (worldometers.info)

**Comment by silverhairs** [comment]
> i'm having the same issue
this

**Comment by gitmonox** [comment]
That´s the only source u can get?

**Comment by dicedtomatoreal** [comment]
Im not familiar with scraping, im asking Elite right now how to fix it, if yall know how to fix this please to reply :joy:

**Comment by silverhairs** [comment]
> Im not familiar with scraping, im asking Elite right now how to fix it, if yall know how to fix this please to reply

We are depending on the owner's URLs and they are depending on the website's database; if there is a change on one of the website's ids, the url we are using will be broken

**Comment by elabayoub** [comment]
You can do as we do, try to understand and compare with source if something has been changed :D : https://github.com/NovelCOVID/API/blob/master/server.js

**Comment by dicedtomatoreal** [comment]
@elabayoub Is yours working right now?

**Comment by gitmonox** [comment]
> @elabayoub Is yours working right now?

No

**Comment by gitmonox** [comment]
The table ID is the same, maybe the add new Countries and that´s broken the array?

**Comment by dicedtomatoreal** [comment]
I just checked all the indexes and they are corect

**Comment by elabayoub** [comment]
Maybe because of some countries with href that got wrapped now in 'td'

**Comment by dicedtomatoreal** [comment]
Its erroring on line 103, which is under the comment "get today cases"

**Comment by gitmonox** [comment]
Cannot GET /tabs/tab2

**Comment by dicedtomatoreal** [comment]
tabs..?

**Comment by elabayoub** [comment]
> Cannot GET /tabs/tab2

try / without /tabs/tab2 cannot get bcuz of routes; you are using another project HAHA

**Comment by gitmonox** [comment]
That´s why i erase the comment

**Comment by dicedtomatoreal** [comment]
cell.children is returning an empty array

**Comment by javieraviles** [comment]
just fixed it in my project, deploying now, 

https://github.com/javieraviles/covidAPI

this is the pipeline
https://github.com/javieraviles/covidAPI/runs/518074421?check_suite_focus=true

a soon as it finishes, will take 2-3 min to scrap then will work fine

**Comment by dicedtomatoreal** [comment]
thanks

**Comment by gitmonox** [comment]
Thanksssssss

**Comment by elabayoub** [comment]
can you create a MR, thanks

**Comment by dicedtomatoreal** [comment]
I just tried @javieraviles and its getting an error on the cured.trim()

**Comment by markjosephcapalad** [comment]
Is it working now for you guys?

**Comment by gitmonox** [comment]
> Is it working now for you guys?

No

**Comment by dicedtomatoreal** [comment]
Not yet

**Comment by dicedtomatoreal** [comment]
im getting stressed over this cause we get 10m+ requests and people will stop using them :|

**Comment by 1rubenito** [comment]
be patience guys...

**Comment by javieraviles** [comment]
sorry, forgot to commit one more thing, coming now! 
https://github.com/javieraviles/covidAPI/actions/runs/58604522

**Comment by javieraviles** [comment]
lets gooo

https://coronavirus-19-api.herokuapp.com/all
https://coronavirus-19-api.herokuapp.com/countries
https://coronavirus-19-api.herokuapp.com/countries/spain

**Comment by dicedtomatoreal** [comment]
Thank you so much @javieraviles, you ahve been my savior since i dont know how to scrape :joy: corona.lmao.ninja now works and we wont be able to push it to git yet.

**Comment by javieraviles** [comment]
i can open a pull request here, can fail again if empty values are present in worldometer...

**Comment by javieraviles** [comment]
https://github.com/NovelCOVID/API/pull/46

this PR should fix it

**Comment by gitmonox** [comment]
THANK YOU SO MUCH

**Comment by markjosephcapalad** [comment]
You are awesome guys! Thanks!

**Comment by elabayoub** [comment]
new attribute has been added to /countries guys is casesPerOneMillion

**Comment by ElBort** [comment]
https://github.com/ElBort/API-COVID-19

I clean a bit the code so people can fix it by themselves
