### ISSUE TITLE
/v2/historical/{query} lastdays => allWithValue

### ISSUE THREAD

**Issue by tobiu** [NovelCOVID/API#434]
the "all" value is nice and in general the ability to set a fixed amount of time makes sense for comparing countries.

when displaying data for just 1 country, it is nice to show all data inside a chart as soon as there is at least 1 case.

i did it like this on the ui side for now (no rocket science included :))
https://github.com/neomjs/neo/commit/bdd2936db04ec9eee8bcee2c9bf15f76bf95f995

example use case:
https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/apps/covid/index.html#mainview=table&country=Italy

**Comment by benjamin-sommer** [comment]
I'll take a look at this

**Comment by ebwinters** [comment]
This is a very specialized feature and use case. You're already doing it on your end so I see no need.

**Comment by tobiu** [comment]
The benefit to do it would be to reduce the traffic quite a bit: there are
countries with > 50% of empty records in case you send the all param.

Not a high priority item for me.
