### ISSUE TITLE
/countries string encoding changes

### ISSUE THREAD

**Issue by tobiu** [NovelCOVID/API#435]
before: "Lao People\'s Democratic Republic"
after: "Lao People"s Democratic Republic"

same for ivory coast (cote d'ivore)

this change can break UIs easily.

did this on the client side for now:
```
        data.forEach(item => {
            if (item.country.includes('"')) {
                item.country = item.country.replace('"', "\'");
            }
        });
```

**Comment by puf17640** [comment]
closed by #438
