### ISSUE TITLE
China showing last in the list

### ISSUE THREAD

**Issue by mdudigam** [NovelCOVID/API#439]
China returned in the last of the JSON data. 

      {
      "country": "China",
      "countryInfo":       {
         "_id": 156,
         "iso2": "CN",
         "iso3": "CHN",
         "lat": 35,
         "long": 105,
         "flag": "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cn.png"
      },
      "updated": 1586145842302,
      "cases": 81708,
      "todayCases": 39,
      "deaths": 3331,
      "todayDeaths": 2,
      "recovered": 77078,
      "active": 1299,
      "critical": 265,
      "casesPerOneMillion": 57,
      "deathsPerOneMillion": 2,
      "tests": 0,
      "testsPerOneMillion": 0
   }

**Comment by ebwinters** [comment]
bruh you can sort it if you want read the docs there is a sort param

**Comment by mdudigam** [comment]
I dont find the documentation related to sorting. would you mind share the query to sort based on country. I appreciate your help Ethan.

**Comment by ebwinters** [comment]
https://corona.lmao.ninja/countries?sort=cases
