### ISSUE TITLE
Empty Array

### ISSUE THREAD

**Issue by gitmonox** [NovelCOVID/API#44]
There ir no other source?

**Comment by javieraviles** [comment]
lets gooo

https://coronavirus-19-api.herokuapp.com/all
https://coronavirus-19-api.herokuapp.com/countries
https://coronavirus-19-api.herokuapp.com/countries/spain

**Comment by javieraviles** [comment]
if this one fails, 
https://coronavirus-19-api.herokuapp.com/all
https://coronavirus-19-api.herokuapp.com/countries
https://coronavirus-19-api.herokuapp.com/countries/spain

**Comment by EliteDaMyth** [comment]
Fixed
