### ISSUE TITLE
historical data before Mar 7

### ISSUE THREAD

**Issue by nasqar** [NovelCOVID/API#442]
Hi,
I am using this great api for a web application, but I noticed the /v2/historical data before Mar 7 is gone. 

Any suggestions?

**Comment by puf17640** [comment]
Please refer to the docs! The /v2/historical endpoint has a new parameter 'lastdays' which controls how many days get returned by the api 

https://corona.lmao.ninja/v2/historical?lastdays=40
this retrieves the last 40 days

**Comment by EliteDaMyth** [comment]
please refer to above comment.
