### ISSUE TITLE
add countryInfo for Saint Pierre Miquelon and South Sudan

### ISSUE THREAD

**Issue by MarkSmit** [NovelCOVID/API#445]
please add the countryInfo for the following countries:

**Saint Pierre Miquelon**:
- id: 666
- iso2: PM
- iso3: SPM
- possible name is also: "Saint Pierre and Miquelon"

**South Sudan**:
- id: 728
- iso2: SS
- iso3: SSD

**Comment by nibble-4bits** [comment]
I've linked a PR resolving this issue
