### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by ChrisChrome** [NovelCOVID/API#45]
Not sure if ya'll know or not but the API is down
Getting a cloudflare error
See image [here](https://www.chrischromeyt.com/screenshot/7oEfoQspQtVRStlChfZy.png)

**Comment by javieraviles** [comment]
try here should be fine 

https://coronavirus-19-api.herokuapp.com/all
https://coronavirus-19-api.herokuapp.com/countries
https://coronavirus-19-api.herokuapp.com/countries/spain

**Comment by ChrisChrome** [comment]
Thanks for that :3
