### ISSUE TITLE
[FEATURE REQUEST] - Add new cases to historical endpoint

### ISSUE THREAD

**Issue by go4cas** [NovelCOVID/API#455]
At present the `https://corona.lmao.ninja/historical` endpoint displays the current total cases for that day. It would be great if we could have the new cases per day, as well. Using this, one could plot trends/spikes of new cases over time.

And, thanks for the great API ... busy building a dashboard, and your API is a perfect fit!

**Comment by puf17640** [comment]
I will be working at this in addition to #421

**Comment by ebwinters** [comment]
So actually this can be done on your end, or with https://corona.lmao.ninja/countries/USA (or any country name) using the `todayCases` field
