### ISSUE TITLE
Spme coordinates for https://corona.lmao.ninja/countries endpoint isn't much accurate

### ISSUE THREAD

**Issue by benacq** [NovelCOVID/API#456]
I just tested that endpoint and it seems quite a few of the coordinates are not pinpointing the exact location(some end up in the ocean instead of some island).
These are the few i have noticed.

- Maldives
- Seychelles
- French Polynesia
- Fiji
- Chile
and some others.
Personally i think coordinates with integer values are not precise enough for many locations since the accuracy relies more on the decimal places (i could be wrong tho :) )

**Comment by puf17640** [comment]
The question is, how inaccurate are they and would such accuracy be beneficial to the API?

**Comment by Krato** [comment]
Maybe we can use some package to get the lat, lng like https://github.com/mambaz/country-js

**Comment by puf17640** [comment]
> Maybe we can use some package to get the lat, lng like https://github.com/mambaz/country-js

Again, it is surely possible as you just proved but the question is if it is necessary to add another dependency just for that extra accuracy on a value that, I personally havent used yet in my projects

**Comment by EliteDaMyth** [comment]
> I just tested that endpoint and it seems quite a few of the coordinates are not pinpointing the exact location(some end up in the ocean instead of some island).
> These are the few i have noticed.
> 
> * Maldives
> * Seychelles
> * French Polynesia
> * Fiji
> * Chile
>   and some others.
>   Personally i think coordinates with integer values are not precise enough for many locations since the accuracy relies more on the decimal places (i could be wrong tho :) )

it *can* be an issue for the map you are using. also as @Krato you can use an third party package on the client side. we wont be implementing any additional dependencies on the api.
