### ISSUE TITLE
minor Johns Hopkins Data issues

### ISSUE THREAD

**Issue by Maarondesigns** [NovelCOVID/API#458]
Not sure if this is within the control of this api but here are some issues I am trying to solve on my map with the "/v2/jhucsse" endpoint.

1. Recovered data is only for US and Canada and is listed as a separate data point with "Recovered" as the province, which is confusing, and with no latitude or londitude. From what I see the states within US and Canada say recovered: 0. It would be better if the recovered numbers were on the state/province data points and not separated.

2. Northern Mariana Islands is missing lat/lon. I am using this: `{ latitude: 15.08635, longitude: 145.686101 }`

3. v1 had detailed data down to counties, not just states. I am curious why that changed and if the county level information is still available.

Otherwise, this api is working great and I will share my site as soon as it's up. Thanks!

**Comment by puf17640** [comment]
Could you please try finding out if it is our problem by checking the official repo ? That would really help alot! 👍
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by ebwinters** [comment]
1. We are only reporting the JHU data as we are getting it. They have really messed up on Canada and the US, so write your programs accordingly. There is no way for us to merge the overall Canada data with its separate provinces.
2. JHU data has no lat long coords for that
3. read the docs. https://corona.lmao.ninja/v2/jhucsse/counties/
