### ISSUE TITLE
Data / routing issue with GBR and UKR

### ISSUE THREAD

**Issue by mralexhenry** [NovelCOVID/API#461]
Hi, 

When making the following request for data for the UK (GBR), in the response it tells me that the country is 'Ukraine'. The stats look like they are for the UK though, so it seems to be an issue with country name tagging.

https://corona.lmao.ninja/v2/historical/GBR/mainland

Cheers

Alex

**Comment by buster95** [comment]
Oh lets me check that

**Comment by ebwinters** [comment]
fixing and making PR
