### ISSUE TITLE
Data only from 03/08/2020 and no longer from 01/22/2020

### ISSUE THREAD

**Issue by mllrmnn** [NovelCOVID/API#462]
Recently, the historical data, which canfetched data via "https://corona.lmao.ninja/v2/historical", is only available from 03/08/2020 and not as before from 01/22/2020 . Is it possible to get the data again from 01/2/2020 or to get it elsewhere in the same structure?

**Comment by othaner** [comment]
Yes, you use the parameter "lastdays=X". By default value is 30. You could use "all".

Docs: https://corona.lmao.ninja/docs/#/JHUCSSE/get_v2_historical

**Comment by mllrmnn** [comment]
Thank you!
