### ISSUE TITLE
Canada issues in historical data.

### ISSUE THREAD

**Issue by magicDamo** [NovelCOVID/API#470]
Hi there, thanks for all the hard work and useful api. I've noticed 2 issues with canada, they should proablably be separated, however using this endpoint:
'https://corona.lmao.ninja/v2/historical'
1) canada's provninces have no stats for timeline.recovered , even though the data keys are there.

2) this is probably related, but Canada has an entry with a province of 'recovered'

![image](https://user-images.githubusercontent.com/862654/78847228-0c4a4900-79c3-11ea-9020-012cf835c070.png)

**Comment by ebwinters** [comment]
yes we know. This is because the recovered entry for canada is only for all of canada, no individual provinces. They offer this data in a row where province is called recovered. I can't think of a viable solution to this, considering there is no province recovery data, so we are leaving it be.

**Comment by magicDamo** [comment]
Thanks Ethan, 
It's unfortunate but ¯\_(ツ)_/¯
what can you do??

damo
