### ISSUE TITLE
Your API data is not updating

### ISSUE THREAD

**Issue by Abinash-bapu123** [NovelCOVID/API#477]
https://corona.lmao.ninja/all

**Comment by priyomukul** [comment]
I am also facing this issue, I hope all are facing the same.

can anyone from the team check this issue, please?

**Comment by puf17640** [comment]
I have already filed a PR to fix the changes to the worldometer page but it seems this is a problem with the server not the code.

**Comment by oumaabde** [comment]
now API is updated
