### ISSUE TITLE
Adding more fields to /all endpoint

### ISSUE THREAD

**Issue by GowthamF** [NovelCOVID/API#48]
It would be great if you can add some more fields to /all endpoints so we show more information to the users. i.e. TotalNewCases, TotalNewDeaths.
![image](https://user-images.githubusercontent.com/40605124/77029998-52fbe300-69c3-11ea-9e49-04f4ccc92801.png)

**Comment by EliteDaMyth** [comment]
you can do this yourself by mapping the countries endpoint and adding all the stuff but will take into consideration next time!

**Comment by CopyMist** [comment]
This should totally be implemented. The combined data on `/all` should show all the fields, same as `/countries/<country>`. Why not add it if Worldometer already has it summed?

![2020-03-22_235405](https://user-images.githubusercontent.com/51974641/77260407-db66d600-6c98-11ea-891a-7054e7dff10b.png)
