### ISSUE TITLE
China is not updated

### ISSUE THREAD

**Issue by Ovardov** [NovelCOVID/API#482]
I found wrong values for China. Tests, Tests per one million, cases per one million and deaths per one million are not updated.

**Comment by ebwinters** [comment]
![](https://i.giphy.com/media/3kyqJeHUD9vXzkdeoH/giphy.gif)
check again

**Comment by Ovardov** [comment]
![5](https://user-images.githubusercontent.com/45401377/78967112-2f334500-7b0a-11ea-9837-41e3c04a14ec.PNG)
