### ISSUE TITLE
Deprecate /all /yesterday /countries /states on 4/16

### ISSUE THREAD

**Issue by ebwinters** [NovelCOVID/API#486]
This is an issue to remind myself to:
- [x] Move /all /yesterday /countries and /states endpoints to the deprecated functions file
- [x] Update their code to return {"message": "..."}
- [x] Default sort by name in getWorldometers.js (see TODO)
- [x] Update tests
- [ ] Update docs

**Comment by ThinkHattke** [comment]
I can work on giving data for India state wise? @ebwinters

**Comment by puf17640** [comment]
> I can work on giving data for India state wise? @ebwinters

open an issue about it or just fork the repo, start hacking and then file a PR
