### ISSUE TITLE
Netherlands - Carribean Netherlands conflict

### ISSUE THREAD

**Issue by cenkingunlugu** [NovelCOVID/API#488]
When you make a request to: https://corona.lmao.ninja/countries/netherlands

It brings "Carribean Netherlands" info.

Until yesterday this was working.

Now It is broken.

**Comment by MarvelDC** [comment]
Use `?strict=true`?

**Comment by cenkingunlugu** [comment]
> Use `?strict=true`?

That is also ok, but this is a behavior change. I have a chrome extension and for adding strict=true i need to send it to review, people will see wrong data until they approve my extension again.

**Comment by EliteDaMyth** [comment]
use strict=true or search by country code (NL)
https://corona.lmao.ninja/countries/NL
