### ISSUE TITLE
Data is not accurate

### ISSUE THREAD

**Issue by HashemDeveloper** [NovelCOVID/API#491]
Hi there! The given data seems to be not accurate. The current status of COVID 19 sats total case is 159,937, recovered 13,000 and death is 7,067. However, from this API, the status says confirmed cases 172348, death 7867, recovered 0. This is John Hopkins CSSE Data.

**Comment by EliteDaMyth** [comment]
our api scrapes the data. you can make an issue on the JHU repo.
