### ISSUE TITLE
Implements Realtime with Socket.IO

### ISSUE THREAD

**Issue by danrleylfd** [NovelCOVID/API#492]
This would help to reduce the number of requests, since there would only be one request. and the answer would only come when there are changes in the data.

**Comment by puf17640** [comment]
i really dont see a point in implementing this

**Comment by puf17640** [comment]
this is a rest api

**Comment by EliteDaMyth** [comment]
copy of https://github.com/NovelCOVID/API/issues/295
https://github.com/NovelCOVID/API/issues/295#issuecomment-606009669 look at ths comment do take a look at closed issues before making a new one.
