### ISSUE TITLE
Can I get a country based on my IP?

### ISSUE THREAD

**Issue by renanbastos93** [NovelCOVID/API#494]
I wish to use this API for my Project [Alert COVID-19](https://github.com/renanbastos93/alertcovid19) so I want to improve my filters using this API the @natea123 suggested for my use your API. Even so, I want to improve my filters based on this issue https://github.com/renanbastos93/alertcovid19/issues/11.

**Comment by ebwinters** [comment]
nah we not doin this. You can instead use https://ipstack.com/ and query our API using `country_code`

**Comment by renanbastos93** [comment]
> nah we not doin this. You can instead use https://ipstack.com/ and query our API using `country_code`

Thanks a lot
