### ISSUE TITLE
https://corona.lmao.ninja/v2/jhucsse returning incorrect field values. 

### ISSUE THREAD

**Issue by gautam-11** [NovelCOVID/API#499]
The response from endpoint https://corona.lmao.ninja/v2/jhucsse is returning incorrect data like a number for country, negative value for updatedAt and date for province.
![covid-api](https://user-images.githubusercontent.com/30733798/79083993-15cf0a80-7d4f-11ea-8553-00314fcace4d.png)

**Comment by ebwinters** [comment]
ye JHU changed some things, the tests also caught this

**Comment by ebwinters** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/2144
linked JHU issue

**Comment by gautam-11** [comment]
Thanks for the quick fix.
