### ISSUE TITLE
Adding Yesterday table so we can do a comparison chart

### ISSUE THREAD

**Issue by GowthamF** [NovelCOVID/API#50]
It would be great if we have an endpoint or data from yesterday's table, We can use it to visualize more to the Users.

**Comment by EliteDaMyth** [comment]
Will take a look

**Comment by dicedtomatoreal** [comment]
This is a good idea we will be working on this soon!

**Comment by itaisteinherz** [comment]
Similar suggestion: having an endpoint for a time series report on each country (containing past history of activate records, deaths, recovered, etc.) would be awesome. The data is already available in the [JHU CSSE repo](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series), so adding it shouldn't be too difficult.

This way, you'll have access to (some of) yesterday's data, as well as the other days.
