### ISSUE TITLE
/v2/jhucsse returning incorrect data

### ISSUE THREAD

**Issue by chrisvalmonte** [NovelCOVID/API#501]
It seems there was an update to JHUCSSE's data that's screwing up the /v2/jhucsse API. All of the data is screwed up (see image below)
<img width="583" alt="Screen Shot 2020-04-12 at 8 58 08 PM" src="https://user-images.githubusercontent.com/22405692/79090968-518eb380-7d00-11ea-84bc-a34c49e7ddb8.png">

**Comment by aamay001** [comment]
I'm seeing the same results on my App.

**Comment by ebwinters** [comment]
ye I fixed it again - JHU has now changed the data source twice today, this time bringing it back to its original structure

**Comment by chrisvalmonte** [comment]
Ty
