### ISSUE TITLE
null value in recovered field 

### ISSUE THREAD

**Issue by mmstq** [NovelCOVID/API#504]
I am getting null value in recovered field for country 'UK' only. This was not an issue until this morning.
![Screenshot from 2020-04-13 11-06-22](https://user-images.githubusercontent.com/39179965/79095045-f9df5f00-7d76-11ea-96b1-e28993154093.png)

**Comment by geekygaurav** [comment]
@mmstq Yes. I am also getting that.
`updated: 1586757344679,
country: "UK"
countryInfo: {_id: 826, iso2: "GB", iso3: "GBR", lat: 54, long: -2, …}
cases: 84279
todayCases: 5288
deaths: 10612
todayDeaths: 737
recovered: null
active: 73323
critical: 1559
casesPerOneMillion: 1241
deathsPerOneMillion: 156
tests: 352974
testsPerOneMillion: 5200`

**Comment by puf17640** [comment]
fixing this right now!

**Comment by geekygaurav** [comment]
@puf17640 That's awesome. Thank you.

**Comment by puf17640** [comment]
this is caused by worldometer changing the Total Recovered value for UK to "N/A"
