### ISSUE TITLE
adding continent data from worldometer as endpoints 

### ISSUE THREAD

**Issue by puf17640** [NovelCOVID/API#506]
/europe/all            -> summary
/europe                 -> countries
/europe/austria    -> specific country

Europe
North America
Asia
South America
Africa
Oceania

**Comment by puf17640** [comment]
will be starting to work on this in a few hours

**Comment by ebwinters** [comment]
Perhaps do it as continents endpoint

**Comment by puf17640** [comment]
can we close this down ? #513
