### ISSUE TITLE
Run scrape job on child process to prevent blocking api requests

### ISSUE THREAD

**Issue by king-sam-perez** [NovelCOVID/API#509]
Since nodejs is single-threaded, it is better to run the scrape job in a child process so that processing scraped data doesn't block api requests.

The scrape job is located [here](https://github.com/NovelCOVID/API/blob/cb20c04ff40fafbc2684066295619ca2becb5ad3/server.js#L7).

**Comment by king-sam-perez** [comment]
@puf17640, @sam-perez

**Comment by king-sam-perez** [comment]
Just realized I created this with the wrong account, will be working on it as @sam-perez

**Comment by sam-perez** [comment]
whatup. gonna get things set up on my local machine and make sure it all works.

**Comment by ebwinters** [comment]
nah no child processes. We are looking into a microservices infra tho, so scraper and API separated.
