### ISSUE TITLE
endpoint- /historical/all - query param not filtering data

### ISSUE THREAD

**Issue by AkashTTN** [NovelCOVID/API#511]
Hi, I was looking for global historical data filterable on the basis of days. On going through the documentation I came across this endpoint and it says that it will filter the data according to the lastdays parameter given to it like in the endpoint /historical which unlike the former seems to be working fine. This in turn is responding with the entire data even on specifying the days for which you need the data of.

**Comment by ebwinters** [comment]
thanks for reporting this, will fix
