### ISSUE TITLE
Data errer on France cases

### ISSUE THREAD

**Issue by CodingOrca** [NovelCOVID/API#514]
First I would  like to thank you for your great job of providing these data. I have noticed until now only two inconsistencies:
In the cases reported for France by the v2 jhu historical data, the cases on 4/14/20 are falling back with 6256 cases. The cases shall however always grow. From other sources in the internet, it seems that the daily cases where subtracted here instead of being added:
{
    "country": "France",
    "province": null,
    "timeline": {
      "cases": {
        ...
        "4/13/20": 136779,
        "4/14/20": 130253
      },
      ...

A similar issue happened with the deaths in Germany on 4/11/20: -31 new deaths on that day, still wrong in the historical data.

**Comment by puf17640** [comment]
i am investigating, but we are only serving the data, we do not control what is published by JHU unfortunately

**Comment by EliteDaMyth** [comment]
^
