### ISSUE TITLE
Data Error on UK Recovery cases

### ISSUE THREAD

**Issue by unsingned** [NovelCOVID/API#515]
Thank you for your great job of providing these data, from the last few days the Recovery data on UK is coming as zero. which is not correct. 
https://corona.lmao.ninja/Countries/UK
{
  "updated": 1586944975056,
  "country": "UK",
  "countryInfo": {
    "_id": 826,
    "iso2": "GB",
    "iso3": "GBR",
    "lat": 54,
    "long": -2,
    "flag": "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gb.png"
  },
  "cases": 93873,
  "todayCases": 0,
  "deaths": 12107,
  "todayDeaths": 0,
  **"recovered": 0,**
  "active": 81422,
  "critical": 1559,
  "casesPerOneMillion": 1383,
  "deathsPerOneMillion": 178,
  "tests": 382650,
  "testsPerOneMillion": 5637
}

I am Plotting this information in my site www.rosv.in

**Comment by puf17640** [comment]
This is not an error, this is what Worldometers gives us basically.
https://www.worldometers.info/coronavirus/country/uk/

**Comment by EliteDaMyth** [comment]
^
