### ISSUE TITLE
/states and v2/states including 'USA Total' 

### ISSUE THREAD

**Issue by ofu997** [NovelCOVID/API#521]
Right now, 'v2/states' as well as '/states' include USA Total. In my experience sometimes 'usa total' is there, sometimes it isn't. Can someone take it out, given that USA information can be accessed at "/countries/usa"?

**Comment by puf17640** [comment]
investigating on this

**Comment by puf17640** [comment]
and found it!! this bug was introduced by, who would have guessed it, me. 2 days ago when refactoring i took out the splice calls because of how we refactored the other routes, i will fix this and pr instantly!
