### ISSUE TITLE
Update Published Postman Documentation

### ISSUE THREAD

**Issue by DannyDainton** [NovelCOVID/API#534]
Hey, 

As the version has now been bumped to V2, would you be able to edit the Postman Collection and republish the documentation again?

https://documenter.getpostman.com/view/8854915/SzS7R6uu?version=latest

We list the API on our https://covid-19-apis.postman.com/ page and I would hate to see people missing out on using the resource :) 

Having looked through the Issue again, I see that Kin Lane created the Collection so I'll check in with him about it too.

**Comment by puf17640** [comment]
We already talked about doing this! :+1: @EliteDaMyth created the postman team i think

**Comment by DannyDainton** [comment]
Cool, there were user asking about the routes on the published collection. They can manually fix the route but I wanted people not to have to do that :)

Great resource, keep up the great work!!

**Comment by puf17640** [comment]
Yeah I understand! We will update this as soon as possible! 
Thanks so much for the feedback and also for showing our work to the world!

**Comment by EliteDaMyth** [comment]
@puf17640 I haven't yet created any team or stuff
@DannyDainton how will this go through? I make a team and you can assign the api the team on the page? If there is any existing team I do not own it.

**Comment by DannyDainton** [comment]
@EliteDaMyth  I believe the published template that's currently on the site, was created by @kinlane, as he mentioned in this Issue. https://github.com/NovelCOVID/API/issues/68#issue-585367428

I spoke to @arlemi about this and he's made some changes that would need to be approved by Kin and that will eventually be updated on the site for other users to import. 

@arlemi I'm not sure what's the best thing to do here, ideally, the collection would be owned by the API owner and maintained by them. Any changes made to the API could then be handled on their side rather than us updating it.

**Comment by EliteDaMyth** [comment]
@DannyDainton so is there a way to transfer teh ownership of the collection so we can keep it up to date? @kinlane do you want to work together and sort this out?

**Comment by arlemi** [comment]
@EliteDaMyth Oops, didn't realise there was several discussions going on! I've already created a collection that reflects the latest version of the API (unless it's changed since last Friday :D), feel free to import that in your Postman and publish under your name, once that is done we can feature your collection on our page:
https://www.getpostman.com/collections/b52698bc5ef407158f3f

Here's our Learning Center page about publishing docs: https://learning.postman.com/docs/postman/api-documentation/publishing-your-docs/

If you need any more help with this I've added you on discord so feel free to ping me there!

**Comment by EliteDaMyth** [comment]
@arlemi whats your discord?

**Comment by arlemi** [comment]
@EliteDaMyth `arlemi.postman#3395`

**Comment by ebwinters** [comment]
@arlemi is there any way we can fix this kind ASAP

**Comment by arlemi** [comment]
@ebwinters This will be fixed as soon as https://github.com/postmanlabs/covid-19-apis/pull/252 is merged, hopefully later today!

**Comment by EliteDaMyth** [comment]
:) lmk if that gets merged and ill close

**Comment by arlemi** [comment]
Aaaand it's merged! 🐌

**Comment by kinlane** [comment]
Boom! Thank y'all.

**Comment by puf17640** [comment]
Awesome!
