### ISSUE TITLE
NPM .yesterday() not working

### ISSUE THREAD

**Issue by Noblauch** [NovelCOVID/API#535]
The .yesterday() function of the NPM Module still runs "https://corona.lmao.ninja/v2/yesterday" which currently returns: "Cannot GET /v2/yesterday"

PS: Overall great work! I'm using the web query since the very beginning and am just switching to the NPM module, because of the discontinuance of v1. Great to see how much attention this API gets! I'm currently running an idle web-game with the data ;)

**Comment by puf17640** [comment]
this is not the repo for the npm package. 
https://github.com/novelcovid/node-api

**Comment by puf17640** [comment]
> this is not the repo for the npm package.
> https://github.com/novelcovid/node-api

also the package hasnt been updated because the maintainers havent done it yet. i have write access to the repo now and will update it with my own code which is currently here: https://github.com/puf17640/covidapi

**Comment by Noblauch** [comment]
> this is not the repo for the npm package.
> https://github.com/novelcovid/node-api

Whoopsy, didn't realize there was a seperate one. But thanks for picking it up anyways ;)
