### ISSUE TITLE
returning null, Error 410. Not working. Maybe its depreciated.

### ISSUE THREAD

**Issue by AjayrajSingh** [NovelCOVID/API#536]

**Comment by thealiilman** [comment]
Ran into this as well. Here's what the response says.
<img width="391" alt="Screen Shot 2020-04-17 at 19 13 30" src="https://user-images.githubusercontent.com/26957580/79563523-8ffce780-80df-11ea-90aa-6ab383aa5993.png">

**Comment by puf17640** [comment]
You just have to read.
