### ISSUE TITLE
Deprecated api question

### ISSUE THREAD

**Issue by artemandroid** [NovelCOVID/API#538]
Is it possible to turn on deprecated /countries api till end of weekend?
The problem is that mobile app stores don't review apps on weekends.

**Comment by puf17640** [comment]
I am sorry for you but we announced the deprecation a week before it being deprecated, we will not revert changes that have been announced before and merged already. 

PS: Did you get your App successfully reviewed before? I heard that no mobile apps regarding covid19 are being reviewed right now.

**Comment by artemandroid** [comment]
> I am sorry for you but we announced the deprecation a week before it being deprecated, we will not revert changes that have been announced before and merged already.
Ok. I see)
> PS: Did you get your App successfully reviewed before? I heard that no mobile apps regarding covid19 are being reviewed right now.
Only Google rejects Covid apps. (And Amazon probably)

**Comment by artemandroid** [comment]
> I am sorry for you but we announced the deprecation a week before it being deprecated, we will not revert changes that have been announced before and merged already.
> 
> PS: Did you get your App successfully reviewed before? I heard that no mobile apps regarding covid19 are being reviewed right now.

Only Google rejects Covid apps (And Amazon probably)

**Comment by puf17640** [comment]
I heard it for Apple tho haha but nice that you got yours to be reviewed
