### ISSUE TITLE
[Bug] NYT endpoints give strings rather than integer numbers

### ISSUE THREAD

**Issue by apex2504** [NovelCOVID/API#540]
`/v2/nyt/usa`, `/v2/nyt/states`, `/v2/nyt/counties` and all of their respective filters all report strings for `fips` (not applicable for `/v2/nyt/usa`), `cases` and `deaths`.

It would seem more logical and make more sense to cast these to integers/numbers instead of strings.

**Comment by puf17640** [comment]
okay im doing it

**Comment by ebwinters** [comment]
@puf17640 remember to update docs to reflect the values returned data type
