### ISSUE TITLE
Please keep Version 1 API alive 

### ISSUE THREAD

**Issue by yogeshgosavi** [NovelCOVID/API#541]
Hi i have been using Version 1 API endpoints 
For COVID 19 kwgt widgets that are active on many people homescreen
https://youtu.be/BOCVsAXZVfw 6:00
https://twitter.com/Yogesh_gosavi_/status/1240903825684189184?s=19

it would be nice if you would keep those running.

Url shows : This endpoint has been deprecated. Use v2 

I'll have to update widgets to use newer API But they'll have to re download new widgets again 

Thanks a lot for this API 🤗 
You guys made it soo easy to get stats

I hope you consider this request 🙏

**Comment by ebwinters** [comment]
It would be bad practice to un-deprecate endpoints, and nobody would end up upgrading. We are making twitter and other forms of communication to ensure this is not an issue again.
