### ISSUE TITLE
API not working (April 18, 2010)

### ISSUE THREAD

**Issue by Sanan4li** [NovelCOVID/API#545]
I used the API in my mobile app. It was working perfectly. From last night, its down, I can't get the data from last night.

**Comment by ba1948** [comment]
You should probably use Discord channels for better and timely support.

What API are you using and what is the error you're getting?

**Comment by Sanan4li** [comment]
I used novelcovid npm package for my react native app..
It has been working since it was developed.
From last night, no data has been shown.
My app is in production.

**Comment by EliteDaMyth** [comment]
@Sanan4li the package was updated did you update it? we moved all endpoints to v2 thats why.

**Comment by Sanan4li** [comment]
No, my app is in production. I have shared my app to many people.
How I can change it now?

**Comment by EliteDaMyth** [comment]
We are sorry. we have been announcing the depreceation of v1 endpoints from almost 2 weeks. at this point you'll have to push an update to your app

**Comment by Sanan4li** [comment]
I am facing problem from the last night. Had no issue before that.
Anyways thanks.
