### ISSUE TITLE
Yesterday data not being received 

### ISSUE THREAD

**Issue by lukehecht** [NovelCOVID/API#546]
Using V2, trying to access 'yesterday' data, but it is not being returned despite the yesterday parameter being set to 'true'. 

This can also be replicated using the API  test on the documentation page:
https://corona.lmao.ninja/docs/

**Comment by ebwinters** [comment]
Seems to be working just fine. https://corona.lmao.ninja/v2/countries?yesterday=true&sort=cases

**Comment by lukehecht** [comment]
Can you tell me the name of the property that denotes yesterday's deaths

**Comment by ebwinters** [comment]
@lukehecht I can see how this is a little confusing, but it is just `deaths`.

**Comment by lukehecht** [comment]
That can't be right, as the 'deaths' property of the response clearly denotes total deaths, and not yesterday's deaths
