### ISSUE TITLE
Not getting expected behaviour from '/v2/historical/{query}' this endpoint

### ISSUE THREAD

**Issue by suraj-deshmukh** [NovelCOVID/API#548]
As per the documentation 

    number of days you want the data to go back to. Default is 30. Use all for full data set. Ex: 15, all, 24

when used with _'all'_, api should all return all the available data points but thats not happening instead i am getting data till 17th april see below screenshots

![history](https://user-images.githubusercontent.com/14833831/79678675-7fea2280-821b-11ea-9e13-f45d1e9bbe14.png)

but when used with a _number_ like below screenshot, i get all the results 

![h10](https://user-images.githubusercontent.com/14833831/79678683-985a3d00-821b-11ea-818c-9dd375532de0.png)

**Comment by puf17640** [comment]
I don't know what happened there, check it ou yourself https://corona.lmao.ninja/v2/historical/USA?lastdays=all
