### ISSUE TITLE
Get JHUCSSE historical data for US states 

### ISSUE THREAD

**Issue by ronenmiller-khealth** [NovelCOVID/API#549]
I need to get historical data for each US states from JHUCSSE data. 
Currently we only get the historical data for counties and countries but not US states.
Thanks in advance

**Comment by puf17640** [comment]
https://i-dont-ca.re

**Comment by EliteDaMyth** [comment]
read the docs 💯 
join discord for further help

**Comment by ronenmiller-khealth** [comment]
Read the docs, perhaps you could give it a try and let me know how you could get historical data for states.

**Comment by wxflint** [comment]
> 
> 
> Read the docs, perhaps you could give it a try and let me know how you could get historical data for states.

https://corona.lmao.ninja/docs/#/Default/get_v2_states

**Comment by artemandroid** [comment]
> Read the docs, perhaps you could give it a try and let me know how you could get historical data for states.

As I understood question is about cases/death/recovered timeline per state?

There are only timelines for state counties:
like https://corona.lmao.ninja/v2/historical/usacounties/minnesota

**Comment by ronenmiller-khealth** [comment]
> > Read the docs, perhaps you could give it a try and let me know how you could get historical data for states.
> 
> As I understood question is about cases/death/recovered time series per state?
> 
> There are only time series per state counties:
> like https://corona.lmao.ninja/v2/historical/usacounties/minnesota

Exactly. So wan hoping to get the accumulated data per state.

**Comment by artemandroid** [comment]
> Exactly. So wan hoping to get the accumulated data per state.

@puf17640 looks like you misunderstood the issue. Problem in absence of time series per state.
