### ISSUE TITLE
Add "Services using this api"

### ISSUE THREAD

**Issue by Krato** [NovelCOVID/API#55]
Will be great to see a list of services using this api. Maybe after source title.

Mine is using: Spanish stats panel: https://covid19esp.herokuapp.com/

**Comment by EliteDaMyth** [comment]
I mean where exactly you wanna add it

**Comment by Krato** [comment]
In the readme file?

**Comment by EliteDaMyth** [comment]
Sure if you wanna gather a list of projects make a PR!
