### ISSUE TITLE
Did these APIs stop working?

### ISSUE THREAD

**Issue by techiela2** [NovelCOVID/API#552]
https://corona.lmao.ninja/all
https://corona.lmao.ninja/countries?sort=cases
https://corona.lmao.ninja/states

**Comment by geekygaurav** [comment]
> https://corona.lmao.ninja/all
> https://corona.lmao.ninja/countries?sort=cases
> https://corona.lmao.ninja/states

They moved to version 2.
Just add /v2/
Like /v2/all
Read their documentation

**Comment by techiela2** [comment]
Lovely! thanks very much @geekygaurav. They work again. Here's my simple app, feel free to use. 

https://medium.com/techiela-net/my-covid-19-tracker-3fc12b002364

**Comment by geekygaurav** [comment]
> Lovely! thanks very much @geekygaurav. They work again. Here's my simple app, feel free to use.
> 
> https://medium.com/techiela-net/my-covid-19-tracker-3fc12b002364

That's beautiful! Thanks!
