### ISSUE TITLE
World Sum for Recoveries Don't Match

### ISSUE THREAD

**Issue by YeabkalA** [NovelCOVID/API#555]
The sum of all 'recovered' values from https://corona.lmao.ninja/v2/countries don't match with the live global data (https://corona.lmao.ninja/v2/all); cases and deaths match.

**Comment by puf17640** [comment]
can you show proof? im really not going to try it out right now im busy as fuck

**Comment by YeabkalA** [comment]
Yes. Here is a test page.
https://github.com/YeabkalA/COVID_Tracker_Chrome_Extension/blob/master/recovered_test.html

All the script is included within the HTML file.

**Comment by ebwinters** [comment]
not our problem, a slight anomaly within the data source

**Comment by YeabkalA** [comment]
Sounds good.
