### ISSUE TITLE
Add country data in continent detail route

### ISSUE THREAD

**Issue by andreascai** [NovelCOVID/API#559]
I'm really grateful about what you all built. I wanna suggest to put every country in that continent data like
`{
name:
tests:
cases:
active:
deaths:
recovered:
todayCases:
todayDeaths:
and so on
`
to the
`/v2/continent/:name` route
It will not be battery efficient when request each country in continent for us.
Cheers all

**Comment by EliteDaMyth** [comment]
#539 please look at open issues before making one :)

**Comment by andreascai** [comment]
I was saying about all data in continent detail route. Not just array of string
