### ISSUE TITLE
FEATURE REQUEST: Drill Down by State or County for USA

### ISSUE THREAD

**Issue by Eddoson** [NovelCOVID/API#56]
It would be great to be able to drill down into state data or even further by county or city data. Currently you can only see the overall status of the country of USA, when I see the source website you're getting data from has state information available to scrape.

Example, on the worldometers site when you select USA, I see state information: https://www.worldometers.info/coronavirus/country/us/

**Comment by EliteDaMyth** [comment]
ONLY US has state data. will implement soon
