### ISSUE TITLE
historical data is not accessable for some countries (self-governing countries)

### ISSUE THREAD

**Issue by itsamirrezah** [NovelCOVID/API#561]
I'm considering migrate my app to the API, but I have a little issue with /v2/historical/:country request.
from /v2/countries request I get list of "countries" and their related data but strangely I cant access their historical data with /v2/historical/:country(id,name,iso2,etc).
f.e this result has came from /v2/countries:
{
. . .
    "country": "Isle of Man",
    "countryInfo": {
      "_id": 833,
      "iso2": "IM",
. . .
    },
. . .
  }
but when i call from /v2/historical/833 (or country name) it raises 404 error with this message: "Country not found or doesn't have any historical data"

If i want to access the historical data of these countries I must use /v2/historical/:country/:province call, but the problem is I didn't get enough information from /v2/countries request. All I know is isle of man is a country and I can access their historical from /v2/historical/:country.

I think it would be nice if any country could access their historical from /v2/historical/:country. or another solution might be addressing these self-governing countries as province, not country.

Thank you for the API

**Comment by ebwinters** [comment]
https://corona.lmao.ninja/v2/countries/833 is working fine

**Comment by itsamirrezah** [comment]
yes but it doesn't have historical timelines. Try https://corona.lmao.ninja/v2/historical/833

**Comment by ebwinters** [comment]
Because it is a UK province, and it is not listed as its own country in the JHU data set. This anomaly comes from using  multiple sources, so you can filter down the result of `/v2/historical/uk`

**Comment by itsamirrezah** [comment]
same problem with these country/provinces:
Ids: 540, 258, 60, 238, 136, 535, 254, ...
