### ISSUE TITLE
Daily New Cases 

### ISSUE THREAD

**Issue by markskull** [NovelCOVID/API#562]
Is there a way to show the Daily New Cases as a dataset for Countries via John Hopkins?

**Comment by ebwinters** [comment]
currently you'd have to use` https://corona.lmao.ninja/v2/historical/armenia`, for example, use `timeline.cases` to calculate differences between each element in succession.

**Comment by zhongqi1112** [comment]
I am using `https://corona.lmao.ninja/v2/countries/USA` to get USA `todaycases`, but it looks like the database is updated around 00:00 UTC. Sometimes, the database is updated 30 minutes late and sometimes the database is updated 3 hours late. How can I get `todaycases` by current timezone instead of UTC? For example, I wonder `todaycases` of PDT timezone is. How can know the database is update after 00:00 UTC? Thanks.

**Comment by ebwinters** [comment]
the `updatedAt` key indicates when we pull the data. You can use that to know exactly when the data is from.

**Comment by markskull** [comment]
> 
> 
> currently you'd have to use` https://corona.lmao.ninja/v2/historical/armenia`, for example, use `timeline.cases` to calculate differences between each element in succession.

Couldn't that just be put into the data by the team? You're already doing the compiling and you're reporting new cases for the day, wouldn't adding that to the historical table just be a matter of putting that information there?

**Comment by ebwinters** [comment]
That’s a matter of weather or not we want to add a `newCases` attribute to the timeline. Right now we are just reporting the data as is, so it would be a decision of whether to add our own calculations or keep it strictly the data set JHU has. If it’s something more people want, we will consider, but for now it’s a pretty simple solution on the user’s end

**Comment by markskull** [comment]
With more places focusing on "Flattening the curve" and people asking if we're doing so and with New York state along with Italy and Germany believing they've done just that, I think the demand may be there.

**Comment by ebwinters** [comment]
@puf17640 @buster95 @EliteDaMyth what do u guys think about this possible feature

**Comment by puf17640** [comment]
To be honest, I'm really split on this...
If we do this we will have to put a message out saying we are adding our own properties which we calculate from the data to be transparent. 

The thing is, currently, this API is just serving data. We are not really adding anything besides the flags and shit although we could, we got some issues from people asking for stuff that we then kinda turned down because it wasnt really beneficial to the api and could be done clientside anyway.
This, though, is quite a cool thing to add... I DONT KNOW 😞

**Comment by buster95** [comment]
I think it is unnecessary, with the current data you can get the daily new cases, just subtract the daily amount minus the amount from the previous day

**Comment by puf17640** [comment]
its literally 1 map call in js

**Comment by Nekiono** [comment]
@ebwinters [[Q]](https://github.com/NovelCOVID/API/issues/562#issuecomment-617342128) This issue entails a fundamental concept-change in the API. Surely this is not gonna be taken lightly or discussed in this issue.
We should take some time to discuss and weigh this out between core contributors/reviewers/backers. IMO it's best if we discuss this on the Discord.

From my PoV, there are only two real points
- if we don't add our own data, there's not really any possible point of failure or scientific inaccuracy that we could introduce, which saves us the effort of talking about every change with people from the scientific field. [As puf said](https://github.com/NovelCOVID/API/issues/562#issuecomment-617353614), right now we don't take any responsibility for the data, we can just refer to the source if issues arise.
- if we don't add our own data, we save the computing costs for it, which allows us to pull updates on a higher poll rate, while keeping the resource usage low
- if we add our own data, we could potentially write code once (on the API end), that saves people from implementing the same thing over and over again
- if we add our own data, we could make it easier for beginners to use the API

To answer the initial questions from the issue though:

@markskull [[Q1]](https://github.com/NovelCOVID/API/issues/562#issue-603586081) yes, there definitely is a way to do that, but right now that way would need to happen on the client-side
@markskull [[Q2]](https://github.com/NovelCOVID/API/issues/562#issuecomment-617300674) the data could be entered server-side but that's a fundamental design concern.

@zhongqi1112 [[Q]](https://github.com/NovelCOVID/API/issues/562#issuecomment-616935083) you said the database is updated around 0 UTC, then asked for maybe changing the timezone to other timezones for todayCases. The issue with this is, that we don't have said data. We simply source this from external sources, and that way more often than once per day - if they choose to update it at 0 UTC, then there's nothing we can do about that.
