### ISSUE TITLE
Cloudflare blocking API Requests

### ISSUE THREAD

**Issue by coolplugins** [NovelCOVID/API#572]
Hi there,	
Thanks for creating an awesome COVID-19 Data API. 

We are regularly facing this error while try to access the API endpoint.
Could you please update Cloudflare rules.
https://community.cloudflare.com/t/community-tip-fixing-error-1020-access-denied/66439

Here is the error message:- 

> 
> Please enable cookies.
> 	Error 1020 Ray ID: 587fbede4ad8e2bd • 2020-04-22 13:38:30 UTC
> 	Access denied
> 	What happened?
> 	This website is using a security service to protect itself from online attacks.
> 	Cloudflare Ray ID: 587fbede4ad8e2bd • Your IP: 2409:4055:68e:3c3:9805:c072:2fba:66a3 • Performance & security by Cloudflare

**Comment by EliteDaMyth** [comment]
we are sorry. some people are trying to launch a DDoS attack which is strssing our server. to prevent this we put some security checks in place. you can dm me on discord for more information
