### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mo3aser** [NovelCOVID/API#574]
Hi,

Thanks for great efforts,

Today we got this response when we are trying to access the API

 ["errors"]=> array(1) { [403]=> array(1) { [0]=> string(9) "Forbidden" } } ["error_data"]=> array(1) { [403]=> array(3) { ["response_code"]=> int(403) ["response_cf_ray"]=> string(20) "588008fabadf16f2-FRA" ["response_server"]=> string(10) "cloudflare" } 

Best regards

**Comment by EliteDaMyth** [comment]
https://github.com/NovelCOVID/API/issues/572

**Comment by EliteDaMyth** [comment]
https://github.com/NovelCOVID/API/issues/572#issuecomment-617808029
