### ISSUE TITLE
Error:  invalid json response body at https://disease.sh/v2/historical/Brazil reason: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by LuXDAmore** [NovelCOVID/API#575]
**Belgium is going well:**
_https://disease.sh/v2/historical/Belgium_
Response header: `content-type: application/json; charset=utf-8`

**Brazil is throwing this error:**
_https://disease.sh/v2/historical/Brazil_
Response header: `content-type: text/html; charset=utf-8`

> Error: invalid json response body at https://disease.sh/v2/historical/Brazil reason: Unexpected token < in JSON at position 0

**Comment by EliteDaMyth** [comment]
@LuXDAmore does it not load in the browser for you?

**Comment by Nekiono** [comment]
This is likely due to us currently being under a DDoS attack. Please limit the number of requests you're doing in order to avoid this from happening.
On a side note - [this works just fine for me](https://i-love.pink/YksUVdeK.png).

**Comment by LuXDAmore** [comment]
How many request/second can i send?

I'm getting this error after the update of the library and in the previous version i'm just getting the data for all the countries with a `countries.forEach => covid.historical( null, country )`

How can i achieve the same results with the updated api?

**Comment by EliteDaMyth** [comment]
@LuXDAmore look at the readme of the updated npm package https://www.npmjs.com/package/novelcovid

**Comment by LuXDAmore** [comment]
I've read it and i'm using this one `.historical(null, 'country name');`, but doing this for every country throw me this error.. 

> Error: invalid json response body at https://disease.sh/v2/historical/Brazil reason: Unexpected token < in JSON at position 0

Maybe it's the limit of request, so How many request/second can i send?

**Comment by Nekiono** [comment]
From our rate limit config, you can send 1 r/s with a burst of 10 at once before getting put into a lower priority queue. Though, this should barely affect you at all.

**Comment by LuXDAmore** [comment]
@Nekiono This is the code generating the error:

``` javascript

    const countries = await covid.countries();

    const promises = [];

    countries.forEach(
        ({ country }) => {

            promises.push(
                covid.historical(
                        null,
                        country
                 )
            );

        }
    );

    // eslint-disable-next-line compat/compat
    return Promise.all( promises ).catch( console.error );

```

Any advice?

**Comment by LuXDAmore** [comment]
I don't think what i've done it's wrong, any suggestion?

**Comment by Nekiono** [comment]
well, you send 200 requests at once; of course, our DDoS protection is going to pick up on that.

**Comment by LuXDAmore** [comment]
How can i get all historical data for statistics purpose?
I should delay some calls?

**Comment by puf17640** [comment]
@LuXDAmore please try calling in batches of like 5 countries, then wait 1-2 seconds and then go for another 5, that should work out, you can test out how much you can do more from there then. 

as @Nekiono said, 
> From our rate limit config, you can send 1 r/s with a burst of 10 at once before getting put into a lower priority queue.
