### ISSUE TITLE
Attention Required! | Cloudflare

### ISSUE THREAD

**Issue by khubbaib** [NovelCOVID/API#578]
When call to API i got Cloudflare Error and no data received

**Comment by ebwinters** [comment]
This makes absolutely 0 sense. Why don't you explain the issue using words.

**Comment by khubbaib** [comment]
I got this response when calling the API instead of getting data..

**Comment by ebwinters** [comment]
what was the call

**Comment by khubbaib** [comment]
https://corona.lmao.ninja/v2/countries and all other endpoints blocking the IP

**Comment by khubbaib** [comment]
Other people also face same issue and one of the contributor said

we are sorry. some people are trying to launch a DDoS attack which is strssing our server. to prevent this we put some security checks in place. you can dm me on discord for more information

How i can dm on discord?

**Comment by ebwinters** [comment]
@khubbaib  Ethan Winters#6305 is my tag
