### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by croxydad** [NovelCOVID/API#586]
FetchError: invalid json response body at https://disease.sh/v2/countries/tr reason: Unexpected token < in JSON at position 0

how can i fix this?

**Comment by drewpayment** [comment]
Sounds like a parsing error with your HTTP library. 

Does your HTTP response headers including JSON? 

(This is probably a better question for SO, because you should see the response from the API is working as expected when you click the URL in your post.)

**Comment by puf17640** [comment]
(wild guess) the problem here is probably that @croxydad did not await an async call using a library to get the json response and actually tried to JSON.parse() a Promise instead of the json string returned if you await the Promise
