### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Roguevashda** [NovelCOVID/API#590]
On the documentation [(link)](https://disease.sh/docs/) upon clicking on the GET section for /v2/continents this error is emitted at the top of the page: ![/v2/continents error](https://i.imgur.com/FAp0w8S.png)

**Comment by EliteDaMyth** [comment]
@Roguevashda can you try to reproducs this now? please check console too

**Comment by Roguevashda** [comment]
@EliteDaMyth Same message, nothing in the console

**Comment by ebwinters** [comment]
should be all good now, reply back if not
