### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ebwinters** [NovelCOVID/API#602]
- [x] Change workflow publish file to run on master
  -  [x]  `if: github.repository != 'NovelCOVID/API'` to `if: github.repository == 'NovelCOVID/API'`
  -  [x]   push: `branches: [master, docker-dev]` to `branches: [master]`
  -  [x]   pull_request: `braches: [master]` to removed
-  [x]  Instructions for usage
-  [x]  Test entire workflow as it would be on server
-  [x]  New branch on push to `prod` instead of `master`. Ravy check webhook payload for `ref === refs/head/prod`
- [ ] Ravy updated .env file
- [ ] Ravy update script to `docker-compose pull && npm run docker-start`

**Comment by puf17640** [comment]
@ebwinters  1 should be done right?, i can do the readme updating

**Comment by ebwinters** [comment]
Sure update readme. Don’t touch the action stuff tho until ravy is awake so we can coordinate
