### ISSUE TITLE
"country": "UK" - recovered is null

### ISSUE THREAD

**Issue by omergal99** [NovelCOVID/API#603]
"country": "UK" (& "country": "Netherlands")
{
    "country": "UK",
    "cases": 148377,
    "todayCases": 0,
    "deaths": 20319,
    "todayDeaths": 0,
    "recovered": null,
    "active": 127714,
    "critical": 1559,
    "casesPerOneMillion": 2186,
    "deathsPerOneMillion": 299,
    "totalTests": 640792,
    "testsPerOneMillion": 9439
  }

**Comment by puf17640** [comment]
Would you mind explaining what endpoint you are using... ?

**Comment by puf17640** [comment]
The API does not return null. 
https://corona.lmao.ninja/v2/countries/UK

**Comment by omergal99** [comment]
it return 0 in the recovered

**Comment by EliteDaMyth** [comment]
@omergal99 worldometers doesnt have data for that

**Comment by puf17640** [comment]
> @omergal99 worldometers doesnt have data for that

yeah also that but the API literally can't return null for it, I implemented the 0 -> null thing myself iirc
