### ISSUE TITLE
Hi. There is Error from the website: Connection Timed Out

### ISSUE THREAD

**Issue by tandduong** [NovelCOVID/API#607]
Error 522 Ray ID: 58a633d51b59c1a2 • 2020-04-27 05:39:51 UTC

**Comment by EliteDaMyth** [comment]
Seems like an cloudflare error.

**Comment by tandduong** [comment]
Are you getting the same like me?

**Comment by EliteDaMyth** [comment]
It's different in different regions. We cannot change anything. And to answer your question yes I am getting the same error but the backend seems to be fine

**Comment by tandduong** [comment]
OK my backend works fine now. It seems to be broken few minutes ago. I have this API for my project that will be represented to my prof as final exam. The error got me panic really. Thanks for your help.

**Comment by EliteDaMyth** [comment]
No worries 👍 hope you get a good grade @tandduong

**Comment by puf17640** [comment]
we are working hard to keep it up, but we cannot change the way services we use work unfortunately 😞anyways, the problem was on cloudflare not on us, hope you get a good grade man :)
