### ISSUE TITLE
Add endpoint for historical data

### ISSUE THREAD

**Issue by benjamin-sommer** [NovelCOVID/API#61]
It would be nice if there was an endpoint like `/country/UK/historical` which would return the past 30 days of information in the same format as is being returned for each country at the `/countries` endpoint.

**Comment by khoaisobar** [comment]
like it

**Comment by EliteDaMyth** [comment]
we arent storing the historical data. if you have historical data source LMK on fdiscord

**Comment by benjamin-sommer** [comment]
@EliteDaMyth what is your discord username?

**Comment by EliteDaMyth** [comment]
you can join our discord server but its EliteDaMyth#0690
