### ISSUE TITLE
Number params countries

### ISSUE THREAD

**Issue by souravp712** [NovelCOVID/API#610]
The number params in /v2/countries are both returning todays data, but the boolean params are working fine and returning yesterdays correct data. 

Yesterday = false image
![image](https://user-images.githubusercontent.com/30350506/80436186-93a52100-88cc-11ea-9c4c-41e23813ee1d.png)

Yesterday = true image

![image](https://user-images.githubusercontent.com/30350506/80436226-ac153b80-88cc-11ea-8ea6-a91d2e57da4d.png)

Yesterday = 1
![image](https://user-images.githubusercontent.com/30350506/80436260-be8f7500-88cc-11ea-9e86-87d0c2a2f9f1.png)

Yesterday = 0

![image](https://user-images.githubusercontent.com/30350506/80436280-ca7b3700-88cc-11ea-808f-01590f36a766.png)

The problem is visible in cases

**Comment by ebwinters** [comment]
worldometers is reflecting same cases for yesterday and today...weird. Will monitor this over the next day to see if they update and we match it

**Comment by souravp712** [comment]
I will close the issue if the bug stays fixed. I believe the data is showing up correctly for the time being. The problem may have been the fact that they were updating at different times, and showing false data as a result.
