### ISSUE TITLE
COVID-19 Testing Sites

### ISSUE THREAD

**Issue by colbyfayock** [NovelCOVID/API#613]
I saw [this article on the Verge](https://www.theverge.com/2020/4/28/21240546/apple-maps-covid-19-testing-sites-mobility-trends) about Apple Maps including testing site locations - I was wondering if that's something that's accessible that you all might consider being able to provide as part of the API?

I'm not sure how that fits in with the other endpoints as they're mostly statistics, but I'm imagining it as something that could be a helpful use case and given its location-based information, could be a nice addition.

**Comment by puf17640** [comment]
I don't really think it would fit into the current stage of the API, but good idea.

@ebwinters ? @buster95  ?

**Comment by ebwinters** [comment]
I like the idea, but I don't see a publicly available API we can pull from to get these location

**Comment by ebwinters** [comment]
https://www.apple.com/covid19/mobility this could be cool data tho
