### ISSUE TITLE
Graphql API's

### ISSUE THREAD

**Issue by skavinvarnan** [NovelCOVID/API#616]
I have created Graphql api's using this repo. Please take a look at the document here https://github.com/COVID19-SARS-CoV-2/web-covid-api/blob/master/README.md

Let me know if this can be added to readme.

#### Notes
1. Data is scraped every 10 mins for JHU and worldometer and every 1 hour for NYT
2. The current server can handle a load of 1000 requests second. In theory the server can handle 840million requests a day.

**Comment by ebwinters** [comment]
no but you can add it to the awesome-novelcovid readme as before :)
