### ISSUE TITLE
Adding APIs for Indian state-wise COVID19 cases 

### ISSUE THREAD

**Issue by HarshavardhanK** [NovelCOVID/API#620]
Data obtained from www.covid19india.org.

**Comment by puf17640** [comment]
@ebwinters - should we consider adding data from india? 
the structure is quite weird but it surely is doable, if you want, let's talk about this on the hangout today.
["API Docs"](https://api.covid19india.org)

@HarshavardhanK thanks for suggesting

**Comment by puf17640** [comment]
I just realised we already plan to add official data from india using this ressource https://www.mohfw.gov.in/

thanks anyway!

**Comment by HarshavardhanK** [comment]
Hey! The update frequency is once in 24hrs so I thought the data from www.covid19india.org would be good since it updates faster than the official ministry site
