### ISSUE TITLE
CORS error on fetch API

### ISSUE THREAD

**Issue by Giancarl021** [NovelCOVID/API#626]
I'm getting a CORS blocking error using the fetch API.

![image](https://user-images.githubusercontent.com/44367174/80812503-7effac00-8b9e-11ea-8e43-9094dc20381f.png)

**Comment by puf17640** [comment]
Has this been happening before or has this started just like 40 minutes ago?

**Comment by Giancarl021** [comment]
Another person notified me ~50 minutes ago.

**Comment by puf17640** [comment]
Okay, we are currently in the means of redirecting the old domains (corona.lmao.ninja and api.caw.sh) to the new main domain https://disease.sh because we got free business plan on this domain from cloudflare, this will improve stability enormously

 I am sorry this is happening, I am trying to revert the last changes that might have caused this!!

### THIS DOES NOT MEAN THE OTHER DOMAINS GET DEPRECATED

**Comment by Giancarl021** [comment]
Okay, thak you for the support, I should add that in Postman the requests are working (sorry I forget to add in the issue).

The new domain worked. Thank you!

**Comment by puf17640** [comment]
> Okay, thank you for the support, I should add that in Postman the requests are working (sorry I forget to add in the issue).
> 
> The new domain worked. Thank you!

to the postman thing: yeah the CORS issue only happens when you try to request our resources from the client-side (the javascript on your website).

**Comment by Nivedita-coder** [comment]
The same problem happens with I'm trying to fetch the "ninja" API in my project but it shows error. Why??? please solve my problem.

**Comment by ebwinters** [comment]
Where are you fetching from? Wordpress?

**Comment by Nivedita-coder** [comment]
> Where are you fetching from? Wordpress?
No, actually I'm making a website on react and I'm fetching this "ninja" API there.

**Comment by ebwinters** [comment]
Give an example of your call and env

**Comment by Nivedita-coder** [comment]
![Screenshot from 2020-06-01 18-16-26](https://user-images.githubusercontent.com/56059682/83477475-ef0c9500-a4b0-11ea-92a8-b9682234c836.png)
this the error after fetching API

**Comment by puf17640** [comment]
the error is no CORS error.

**Comment by EliteDaMyth** [comment]
The error is not a CORS error @Nivedita-coder  also we suggest using disease.sh as your main domain as it is the main domain now
