### ISSUE TITLE
Add "last updated" field to responses 

### ISSUE THREAD

**Issue by itaisteinherz** [NovelCOVID/API#63]
First of all, thanks for making this API! It's awesome to use, and is really useful.

One suggestion I have: Since I want to let users know when the data I use was last updated, it would be great to have a `lastUpdated` field in relevant routes.

(Also, if you're busy with other things, let me know and I'll be happy to chip in and work on this myself 😄)

**Comment by dicedtomatoreal** [comment]
They all update every 30 minutes, you can get the /all endpoint for the last update

**Comment by itaisteinherz** [comment]
Maybe add that field to the `/countries` endpoint as well then?

**Comment by dicedtomatoreal** [comment]
If i do that, then **a lot** of website will need to update their systems, which i'm not about. Feel free to do a request to `/all` because there is no limit :)
