### ISSUE TITLE
[Feature Request] Add Todays Recovered, Fatality and Recovery Rate

### ISSUE THREAD

**Issue by jpjpjp28** [NovelCOVID/API#635]
Hi! Is it possible to add todaysRecovered, fatalityRate and recoveryRate in `(https://corona.lmao.ninja/v2/countries/{country})` endpoint?

**Comment by puf17640** [comment]
It is possible yes, but we only serve the data that is provided to us by our sources. We do not plan on adding additional properties to our data.

You can calculate these yourself though, if you need help on that please join our Discord support server.
