### ISSUE TITLE
Spain case statistics issue 

### ISSUE THREAD

**Issue by waleedocp** [NovelCOVID/API#638]
i use this api ("https://disease.sh/v2/historical/ES?lastdays=30") but i got wrong case number from date 4/24/20

**Comment by puf17640** [comment]
could you please explain what "wrong case number" means... why is it wrong and how do you know? this is fetched from the official source

**Comment by waleedocp** [comment]
at 4/24/20 your API recorded  202990 cases, but the official source recorded 219,764
and from that date forth all cases mismatched
reference
https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Spain

**Comment by puf17640** [comment]
> at 4/24/20 your API recorded  202990 cases, but the official source recorded 219,764
> and from that date forth all cases mismatched
> reference
> https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Spain

are you literally using wikipedia as your single official source? 

we dont record any data, we serve official data from our official sources, for this endpoint, the source is John Hopkins University. please open an issue on their github about this, we do not RECORD data, we only serve what they offer.
