### ISSUE TITLE
Data is out of date

### ISSUE THREAD

**Issue by cdbessig** [NovelCOVID/API#64]
For example, I went to: https://corona.lmao.ninja/historical

Then I looked for the county I live in and the numbers are just categorically wrong.  Like not even close...For example 3/19 should be more like 189 cases....There should be over 400 total.  800 if you go to 3/20.  These add up to 16.  I think this data source is outdated or just bad.

  "country": "US",
  "province": "Bergen County, NJ",
  "timeline": {
    "cases": {
      "1/22/20": "0",
      "1/23/20": "0",
      "1/24/20": "0",
      "1/25/20": "0",
      "1/26/20": "0",
      "1/27/20": "0",
      "1/28/20": "0",
      "1/29/20": "0",
      "1/30/20": "0",
      "1/31/20": "0",
      "2/1/20": "0",
      "2/2/20": "0",
      "2/3/20": "0",
      "2/4/20": "0",
      "2/5/20": "0",
      "2/6/20": "0",
      "2/7/20": "0",
      "2/8/20": "0",
      "2/9/20": "0",
      "2/10/20": "0",
      "2/11/20": "0",
      "2/12/20": "0",
      "2/13/20": "0",
      "2/14/20": "0",
      "2/15/20": "0",
      "2/16/20": "0",
      "2/17/20": "0",
      "2/18/20": "0",
      "2/19/20": "0",
      "2/20/20": "0",
      "2/21/20": "0",
      "2/22/20": "0",
      "2/23/20": "0",
      "2/24/20": "0",
      "2/25/20": "0",
      "2/26/20": "0",
      "2/27/20": "0",
      "2/28/20": "0",
      "2/29/20": "0",
      "3/1/20": "0",
      "3/2/20": "0",
      "3/3/20": "0",
      "3/4/20": "0",
      "3/5/20": "2",
      "3/6/20": "2",
      "3/7/20": "4",
      "3/8/20": "4",
      "3/9/20": "4",
      "3/10/20": "0",
      "3/11/20": "0",
      "3/12/20": "0",
      "3/13/20": "0",
      "3/14/20": "0",
      "3/15/20": "0",
      "3/16/20": "0",
      "3/17/20": "0",
      "3/18/20": "0",
      "3/19/20": "0"

**Comment by dicedtomatoreal** [comment]
Uh will check out this

**Comment by Bam92** [comment]
But I can see that the number is close to the real, worldwide and Italy for example.

My country -DRC- is not listed. Where are data from?

**Comment by MatYRicS** [comment]
Historical data is from here:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by EliteDaMyth** [comment]
the historical data is not yet fully furnished and would not prefer using. you can parse the csv yourself.
