### ISSUE TITLE
endpoints not updating

### ISSUE THREAD

**Issue by smilingchemist** [NovelCOVID/API#640]
Hello, the endpoints have not been updated for the last 2 hours. Thank you!

**Comment by ebwinters** [comment]
🤔which

**Comment by smilingchemist** [comment]
e.g. v2/countries: updated 1588729215256; v2/all: updated 1588729215153

**Comment by abaranovskis-redsamurai** [comment]
This endpoint is also not updated: https://corona.lmao.ninja/v2/historical?lastdays=all

**Comment by mostfunkyduck** [comment]
looks like /v2/jhucsse isn't updating, i see the data on their github, but not in the API

**Comment by puf17640** [comment]
yeah it is already being addressed! 👍 thanks guys!

**Comment by lekhnath** [comment]
Data not updated since past 11 hours. I am using following endpoints of the API:

* https://corona.lmao.ninja/v2/all
* https://corona.lmao.ninja/v2/countries

**Comment by SuperCoderDamian** [comment]
Hi, as noted in our Discord, the API (or related?) is not updating.

**Comment by Shanmugabavan** [comment]
No update for 12 hours.....

**Comment by abaranovskis-redsamurai** [comment]
Any estimate when endpoints could start working again?

**Comment by abaranovskis-redsamurai** [comment]
I can see latest data now from https://corona.lmao.ninja/v2/historical?lastdays=all, thanks !

**Comment by ibrahimwickama** [comment]
Thanks Dev Team, things are update now. Cheers!!!

**Comment by smilingchemist** [comment]
Thank you!! 😊👏🏼👍🏼
