### ISSUE TITLE
config.example.json not founds in project!

### ISSUE THREAD

**Issue by AmenehSadat** [NovelCOVID/API#641]
i can't find config.example.json file in project!

**Comment by puf17640** [comment]
@AmenehSadat I am sorry, the README isn't updated to the newest version yet, I will do this right now! we are now using .env file to read the configuration, please check the README in a few hours! 
Thanks!

**Comment by puf17640** [comment]
Updated! Please check [Installation](https://github.com/NovelCOVID/API#installation)
