### ISSUE TITLE
Incorrect data in some countries: GET Historical Data by Country Name

### ISSUE THREAD

**Issue by acollazog11** [NovelCOVID/API#643]
In the historical endpoint I am getting incorrect values for some countries.
for example: Spain
[https://corona.lmao.ninja/v2/historical/spain](https://corona.lmao.ninja/v2/historical/spain)
```
{
    ...
    "4/23/20": 213024,
    "4/24/20": 202990,
    "4/25/20": 205905,
    ...
}
```
this is a portion of the "cases" object within the "timeline"
so here you can see that the number of cases on day "4/24/20" is less than on day "4/23/20", and this should not happen, the number of cases should increase every day.

Any help would be appreciated. Thank you.

**Comment by ebwinters** [comment]
it's an anomaly in the data reported by JHU, we can't do anything for it.
<img width="1001" alt="Screen Shot 2020-05-06 at 10 26 00 AM" src="https://user-images.githubusercontent.com/4297028/81195893-03c63d80-8f84-11ea-8df8-5876cd13093d.png">
