### ISSUE TITLE
Countries Images Links

### ISSUE THREAD

**Issue by saisk73** [NovelCOVID/API#645]
in the file utils/countryUtils.js the country images links are to the domain corona.ninja.lmao
in line 20 and 34 the link is given as  https://corona.lmao.ninja/assets/img/flags/ . 
ISSUE: I deployed the API in my server but the problem is the images are fetched from the ninja.lmao more load on ninja.lmao API. If there are more custom deployments then it will be a problem.
SOLUTION: Change the link to route /assets/

**Comment by EliteDaMyth** [comment]
This isn't meant for self hosting hence this will not be done. You can edit on your server simply.
