### ISSUE TITLE
Case Count for historical data and countries data is out of sync

### ISSUE THREAD

**Issue by mstrfpts** [NovelCOVID/API#649]
firing a 
https://corona.lmao.ninja/v2/historical/UK
gives you ->
{"country":"UK","province":[ ... ],"timeline":{"cases": ... "5/5/20":196243,"5/6/20":202359,"**5/7/20":207977**}....}

and firing a 
https://corona.lmao.ninja/v2/countries/UK
on 5/8/20 gives you  ->
{"updated":1588932396815,"country":"UK","countryInfo":{"_id":826,"iso2":"GB","iso3":"GBR","lat":54,"long":-2,...},
"**cases":206715**, ...}

Why is case count for 5/7/20 historical data higher than the case count for 5/8/20 country data? 
Ideally, these values should be in sync until the country data is updated to a higher value today.

**Comment by puf17640** [comment]
The data is from different sources.
