### ISSUE TITLE
Add country code key along with country name. 

### ISSUE THREAD

**Issue by sagarkarira** [NovelCOVID/API#65]
It would be great if you could add one more key `countryCode` which would be a standard iso code of a given country.

**Comment by sagarkarira** [comment]
@EliteDaMyth any explanation for closing this?

**Comment by EliteDaMyth** [comment]
you can open a PR if you want to. Might not be easy as the stuff from Worldometers are mixed.

**Comment by ottsch** [comment]
Here's a list with the mapping to two letter codes, hth:

`[
  { "country": "China", "alpha2Code": "CN" },
  { "country": "UK", "alpha2Code": "GB" },
  { "country": "Martinique", "alpha2Code": "MQ" },
  { "country": "Liechtenstein", "alpha2Code": "LI" },
  { "country": "R\u00e9union", "alpha2Code": "RE" },
  { "country": "Ukraine", "alpha2Code": "UA" },
  { "country": "Honduras", "alpha2Code": "HN" },
  { "country": "Afghanistan", "alpha2Code": "AF" },
  { "country": "Bangladesh", "alpha2Code": "BD" },
  { "country": "Macao", "alpha2Code": "MO" },
  { "country": "Bolivia", "alpha2Code": "BO" },
  { "country": "Cuba", "alpha2Code": "CU" },
  { "country": "Netherlands", "alpha2Code": "NL" },
  { "country": "Jamaica", "alpha2Code": "JM" },
  { "country": "French Guiana", "alpha2Code": "GF" },
  { "country": "DRC", "alpha2Code": "CD" },
  { "country": "Cameroon", "alpha2Code": "CM" },
  { "country": "Maldives", "alpha2Code": "MV" },
  { "country": "Montenegro", "alpha2Code": "ME" },
  { "country": "Paraguay", "alpha2Code": "PY" },
  { "country": "Nigeria", "alpha2Code": "NG" },
  { "country": "Guam", "alpha2Code": "GU" },
  { "country": "French Polynesia", "alpha2Code": "PF" },
  { "country": "Austria", "alpha2Code": "AT" },
  { "country": "Ghana", "alpha2Code": "GH" },
  { "country": "Rwanda", "alpha2Code": "RW" },
  { "country": "Monaco", "alpha2Code": "MC" },
  { "country": "Gibraltar", "alpha2Code": "GI" },
  { "country": "Guatemala", "alpha2Code": "GT" },
  { "country": "Ivory Coast", "alpha2Code": "CI" },
  { "country": "Ethiopia", "alpha2Code": "ET" },
  { "country": "Togo", "alpha2Code": "TG" },
  { "country": "Trinidad and Tobago", "alpha2Code": "TT" },
  { "country": "Kenya", "alpha2Code": "KE" },
  { "country": "Belgium", "alpha2Code": "BE" },
  { "country": "Mauritius", "alpha2Code": "MU" },
  { "country": "Equatorial Guinea", "alpha2Code": "GQ" },
  { "country": "Kyrgyzstan", "alpha2Code": "KG" },
  { "country": "Mongolia", "alpha2Code": "MN" },
  { "country": "Puerto Rico", "alpha2Code": "PR" },
  { "country": "Seychelles", "alpha2Code": "SC" },
  { "country": "Tanzania", "alpha2Code": "TZ" },
  { "country": "Guyana", "alpha2Code": "GY" },
  { "country": "Aruba", "alpha2Code": "AW" },
  { "country": "Barbados", "alpha2Code": "BB" },
  { "country": "Norway", "alpha2Code": "NO" },
  { "country": "Mayotte", "alpha2Code": "YT" },
  { "country": "Cayman Islands", "alpha2Code": "KY" },
  { "country": "Cura\u00e7ao", "alpha2Code": "CW" },
  { "country": "Bahamas", "alpha2Code": "BS" },
  { "country": "Congo", "alpha2Code": "CD" },
  { "country": "Gabon", "alpha2Code": "GA" },
  { "country": "Namibia", "alpha2Code": "NA" },
  { "country": "St. Barth", "alpha2Code": "BL" },
  { "country": "Saint Martin", "alpha2Code": "MF" },
  { "country": "U.S. Virgin Islands", "alpha2Code": "VI" },
  { "country": "Sweden", "alpha2Code": "SE" },
  { "country": "Sudan", "alpha2Code": "SD" },
  { "country": "Benin", "alpha2Code": "BJ" },
  { "country": "Bermuda", "alpha2Code": "BM" },
  { "country": "Bhutan", "alpha2Code": "BT" },
  { "country": "CAR", "alpha2Code": "CF" },
  { "country": "Greenland", "alpha2Code": "GL" },
  { "country": "Haiti", "alpha2Code": "HT" },
  { "country": "Liberia", "alpha2Code": "LR" },
  { "country": "Mauritania", "alpha2Code": "MR" },
  { "country": "New Caledonia", "alpha2Code": "NC" },
  { "country": "Denmark", "alpha2Code": "DK" },
  { "country": "Saint Lucia", "alpha2Code": "LC" },
  { "country": "Zambia", "alpha2Code": "ZM" },
  { "country": "Nepal", "alpha2Code": "NP" },
  { "country": "Angola", "alpha2Code": "AO" },
  { "country": "Antigua and Barbuda", "alpha2Code": "AG" },
  { "country": "Cabo Verde", "alpha2Code": "CV" },
  { "country": "Chad", "alpha2Code": "TD" },
  { "country": "Djibouti", "alpha2Code": "DJ" },
  { "country": "El Salvador", "alpha2Code": "SV" },
  { "country": "Fiji", "alpha2Code": "FJ" },
  { "country": "Japan", "alpha2Code": "JP" },
  { "country": "Gambia", "alpha2Code": "GM" },
  { "country": "Guinea", "alpha2Code": "GN" },
  { "country": "Vatican City", "alpha2Code": "VA" },
  { "country": "Isle of Man", "alpha2Code": "IM" },
  { "country": "Montserrat", "alpha2Code": "MS" },
  { "country": "Nicaragua", "alpha2Code": "NI" },
  { "country": "Niger", "alpha2Code": "NE" },
  { "country": "St. Vincent Grenadines", "alpha2Code": "VC" },
  { "country": "Sint Maarten", "alpha2Code": "SX" },
  { "country": "Somalia", "alpha2Code": "SO" },
  { "country": "Malaysia", "alpha2Code": "MY" },
  { "country": "Suriname", "alpha2Code": "SR" },
  { "country": "Eswatini", "alpha2Code": "SZ" },
  { "country": "Australia", "alpha2Code": "AU" },
  { "country": "Italy", "alpha2Code": "IT" },
  { "country": "Canada", "alpha2Code": "CA" },
  { "country": "Portugal", "alpha2Code": "PT" },
  { "country": "Czechia", "alpha2Code": "CZ" },
  { "country": "Israel", "alpha2Code": "IL" },
  { "country": "Brazil", "alpha2Code": "BR" },
  { "country": "Luxembourg", "alpha2Code": "LU" },
  { "country": "Ireland", "alpha2Code": "IE" },
  { "country": "Greece", "alpha2Code": "GR" },
  { "country": "Qatar", "alpha2Code": "QA" },
  { "country": "Pakistan", "alpha2Code": "PK" },
  { "country": "Iran", "alpha2Code": "IR" },
  { "country": "Finland", "alpha2Code": "FI" },
  { "country": "Poland", "alpha2Code": "PL" },
  { "country": "Turkey", "alpha2Code": "TR" },
  { "country": "Singapore", "alpha2Code": "SG" },
  { "country": "Chile", "alpha2Code": "CL" },
  { "country": "Iceland", "alpha2Code": "IS" },
  { "country": "Thailand", "alpha2Code": "TH" },
  { "country": "Slovenia", "alpha2Code": "SI" },
  { "country": "Indonesia", "alpha2Code": "ID" },
  { "country": "Bahrain", "alpha2Code": "BH" },
  { "country": "Spain", "alpha2Code": "ES" },
  { "country": "Romania", "alpha2Code": "RO" },
  { "country": "Saudi Arabia", "alpha2Code": "SA" },
  { "country": "Estonia", "alpha2Code": "EE" },
  { "country": "Ecuador", "alpha2Code": "EC" },
  { "country": "Egypt", "alpha2Code": "EG" },
  { "country": "Peru", "alpha2Code": "PE" },
  { "country": "Philippines", "alpha2Code": "PH" },
  { "country": "Hong Kong", "alpha2Code": "HK" },
  { "country": "India", "alpha2Code": "IN" },
  { "country": "Russia", "alpha2Code": "RU" },
  { "country": "Germany", "alpha2Code": "DE" },
  { "country": "Iraq", "alpha2Code": "IQ" },
  { "country": "Mexico", "alpha2Code": "MX" },
  { "country": "Lebanon", "alpha2Code": "LB" },
  { "country": "South Africa", "alpha2Code": "ZA" },
  { "country": "Kuwait", "alpha2Code": "KW" },
  { "country": "San Marino", "alpha2Code": "SM" },
  { "country": "UAE", "alpha2Code": "AE" },
  { "country": "Panama", "alpha2Code": "PA" },
  { "country": "Armenia", "alpha2Code": "AM" },
  { "country": "Taiwan", "alpha2Code": "TW" },
  { "country": "USA", "alpha2Code": "US" },
  { "country": "Argentina", "alpha2Code": "AR" },
  { "country": "Colombia", "alpha2Code": "CO" },
  { "country": "Slovakia", "alpha2Code": "SK" },
  { "country": "Serbia", "alpha2Code": "RS" },
  { "country": "Croatia", "alpha2Code": "HR" },
  { "country": "Bulgaria", "alpha2Code": "BG" },
  { "country": "Uruguay", "alpha2Code": "UY" },
  { "country": "Algeria", "alpha2Code": "DZ" },
  { "country": "Costa Rica", "alpha2Code": "CR" },
  { "country": "Latvia", "alpha2Code": "LV" },
  { "country": "France", "alpha2Code": "FR" },
  { "country": "Hungary", "alpha2Code": "HU" },
  { "country": "Vietnam", "alpha2Code": "VN" },
  { "country": "Faeroe Islands", "alpha2Code": "FO" },
  { "country": "Andorra", "alpha2Code": "AD" },
  { "country": "Brunei", "alpha2Code": "BN" },
  { "country": "Belarus", "alpha2Code": "BY" },
  { "country": "Jordan", "alpha2Code": "JO" },
  { "country": "Cyprus", "alpha2Code": "CY" },
  { "country": "Sri Lanka", "alpha2Code": "LK" },
  { "country": "Albania", "alpha2Code": "AL" },
  { "country": "S. Korea", "alpha2Code": "KR" },
  { "country": "Bosnia and Herzegovina", "alpha2Code": "BA" },
  { "country": "Morocco", "alpha2Code": "MA" },
  { "country": "Malta", "alpha2Code": "MT" },
  { "country": "North Macedonia", "alpha2Code": "MK" },
  { "country": "Moldova", "alpha2Code": "MD" },
  { "country": "Kazakhstan", "alpha2Code": "KZ" },
  { "country": "Lithuania", "alpha2Code": "LT" },
  { "country": "Oman", "alpha2Code": "OM" },
  { "country": "Cambodia", "alpha2Code": "KH" },
  { "country": "Palestine", "alpha2Code": "PS" },
  { "country": "Switzerland", "alpha2Code": "CH" },
  { "country": "Guadeloupe", "alpha2Code": "GP" },
  { "country": "Azerbaijan", "alpha2Code": "AZ" },
  { "country": "Georgia", "alpha2Code": "GE" },
  { "country": "Venezuela", "alpha2Code": "VE" },
  { "country": "Tunisia", "alpha2Code": "TN" },
  { "country": "New Zealand", "alpha2Code": "NZ" },
  { "country": "Senegal", "alpha2Code": "SN" },
  { "country": "Dominican Republic", "alpha2Code": "DO" },
  { "country": "Burkina Faso", "alpha2Code": "BF" },
  { "country": "Uzbekistan", "alpha2Code": "UZ" }
]
`

**Comment by EliteDaMyth** [comment]
> Here's a list with the mapping to two letter codes, hth:
> 
> `[ { "country": "China", "alpha2Code": "CN" }, { "country": "UK", "alpha2Code": "GB" }, { "country": "Martinique", "alpha2Code": "MQ" }, { "country": "Liechtenstein", "alpha2Code": "LI" }, { "country": "R\u00e9union", "alpha2Code": "RE" }, { "country": "Ukraine", "alpha2Code": "UA" }, { "country": "Honduras", "alpha2Code": "HN" }, { "country": "Afghanistan", "alpha2Code": "AF" }, { "country": "Bangladesh", "alpha2Code": "BD" }, { "country": "Macao", "alpha2Code": "MO" }, { "country": "Bolivia", "alpha2Code": "BO" }, { "country": "Cuba", "alpha2Code": "CU" }, { "country": "Netherlands", "alpha2Code": "NL" }, { "country": "Jamaica", "alpha2Code": "JM" }, { "country": "French Guiana", "alpha2Code": "GF" }, { "country": "DRC", "alpha2Code": "CD" }, { "country": "Cameroon", "alpha2Code": "CM" }, { "country": "Maldives", "alpha2Code": "MV" }, { "country": "Montenegro", "alpha2Code": "ME" }, { "country": "Paraguay", "alpha2Code": "PY" }, { "country": "Nigeria", "alpha2Code": "NG" }, { "country": "Guam", "alpha2Code": "GU" }, { "country": "French Polynesia", "alpha2Code": "PF" }, { "country": "Austria", "alpha2Code": "AT" }, { "country": "Ghana", "alpha2Code": "GH" }, { "country": "Rwanda", "alpha2Code": "RW" }, { "country": "Monaco", "alpha2Code": "MC" }, { "country": "Gibraltar", "alpha2Code": "GI" }, { "country": "Guatemala", "alpha2Code": "GT" }, { "country": "Ivory Coast", "alpha2Code": "CI" }, { "country": "Ethiopia", "alpha2Code": "ET" }, { "country": "Togo", "alpha2Code": "TG" }, { "country": "Trinidad and Tobago", "alpha2Code": "TT" }, { "country": "Kenya", "alpha2Code": "KE" }, { "country": "Belgium", "alpha2Code": "BE" }, { "country": "Mauritius", "alpha2Code": "MU" }, { "country": "Equatorial Guinea", "alpha2Code": "GQ" }, { "country": "Kyrgyzstan", "alpha2Code": "KG" }, { "country": "Mongolia", "alpha2Code": "MN" }, { "country": "Puerto Rico", "alpha2Code": "PR" }, { "country": "Seychelles", "alpha2Code": "SC" }, { "country": "Tanzania", "alpha2Code": "TZ" }, { "country": "Guyana", "alpha2Code": "GY" }, { "country": "Aruba", "alpha2Code": "AW" }, { "country": "Barbados", "alpha2Code": "BB" }, { "country": "Norway", "alpha2Code": "NO" }, { "country": "Mayotte", "alpha2Code": "YT" }, { "country": "Cayman Islands", "alpha2Code": "KY" }, { "country": "Cura\u00e7ao", "alpha2Code": "CW" }, { "country": "Bahamas", "alpha2Code": "BS" }, { "country": "Congo", "alpha2Code": "CD" }, { "country": "Gabon", "alpha2Code": "GA" }, { "country": "Namibia", "alpha2Code": "NA" }, { "country": "St. Barth", "alpha2Code": "BL" }, { "country": "Saint Martin", "alpha2Code": "MF" }, { "country": "U.S. Virgin Islands", "alpha2Code": "VI" }, { "country": "Sweden", "alpha2Code": "SE" }, { "country": "Sudan", "alpha2Code": "SD" }, { "country": "Benin", "alpha2Code": "BJ" }, { "country": "Bermuda", "alpha2Code": "BM" }, { "country": "Bhutan", "alpha2Code": "BT" }, { "country": "CAR", "alpha2Code": "CF" }, { "country": "Greenland", "alpha2Code": "GL" }, { "country": "Haiti", "alpha2Code": "HT" }, { "country": "Liberia", "alpha2Code": "LR" }, { "country": "Mauritania", "alpha2Code": "MR" }, { "country": "New Caledonia", "alpha2Code": "NC" }, { "country": "Denmark", "alpha2Code": "DK" }, { "country": "Saint Lucia", "alpha2Code": "LC" }, { "country": "Zambia", "alpha2Code": "ZM" }, { "country": "Nepal", "alpha2Code": "NP" }, { "country": "Angola", "alpha2Code": "AO" }, { "country": "Antigua and Barbuda", "alpha2Code": "AG" }, { "country": "Cabo Verde", "alpha2Code": "CV" }, { "country": "Chad", "alpha2Code": "TD" }, { "country": "Djibouti", "alpha2Code": "DJ" }, { "country": "El Salvador", "alpha2Code": "SV" }, { "country": "Fiji", "alpha2Code": "FJ" }, { "country": "Japan", "alpha2Code": "JP" }, { "country": "Gambia", "alpha2Code": "GM" }, { "country": "Guinea", "alpha2Code": "GN" }, { "country": "Vatican City", "alpha2Code": "VA" }, { "country": "Isle of Man", "alpha2Code": "IM" }, { "country": "Montserrat", "alpha2Code": "MS" }, { "country": "Nicaragua", "alpha2Code": "NI" }, { "country": "Niger", "alpha2Code": "NE" }, { "country": "St. Vincent Grenadines", "alpha2Code": "VC" }, { "country": "Sint Maarten", "alpha2Code": "SX" }, { "country": "Somalia", "alpha2Code": "SO" }, { "country": "Malaysia", "alpha2Code": "MY" }, { "country": "Suriname", "alpha2Code": "SR" }, { "country": "Eswatini", "alpha2Code": "SZ" }, { "country": "Australia", "alpha2Code": "AU" }, { "country": "Italy", "alpha2Code": "IT" }, { "country": "Canada", "alpha2Code": "CA" }, { "country": "Portugal", "alpha2Code": "PT" }, { "country": "Czechia", "alpha2Code": "CZ" }, { "country": "Israel", "alpha2Code": "IL" }, { "country": "Brazil", "alpha2Code": "BR" }, { "country": "Luxembourg", "alpha2Code": "LU" }, { "country": "Ireland", "alpha2Code": "IE" }, { "country": "Greece", "alpha2Code": "GR" }, { "country": "Qatar", "alpha2Code": "QA" }, { "country": "Pakistan", "alpha2Code": "PK" }, { "country": "Iran", "alpha2Code": "IR" }, { "country": "Finland", "alpha2Code": "FI" }, { "country": "Poland", "alpha2Code": "PL" }, { "country": "Turkey", "alpha2Code": "TR" }, { "country": "Singapore", "alpha2Code": "SG" }, { "country": "Chile", "alpha2Code": "CL" }, { "country": "Iceland", "alpha2Code": "IS" }, { "country": "Thailand", "alpha2Code": "TH" }, { "country": "Slovenia", "alpha2Code": "SI" }, { "country": "Indonesia", "alpha2Code": "ID" }, { "country": "Bahrain", "alpha2Code": "BH" }, { "country": "Spain", "alpha2Code": "ES" }, { "country": "Romania", "alpha2Code": "RO" }, { "country": "Saudi Arabia", "alpha2Code": "SA" }, { "country": "Estonia", "alpha2Code": "EE" }, { "country": "Ecuador", "alpha2Code": "EC" }, { "country": "Egypt", "alpha2Code": "EG" }, { "country": "Peru", "alpha2Code": "PE" }, { "country": "Philippines", "alpha2Code": "PH" }, { "country": "Hong Kong", "alpha2Code": "HK" }, { "country": "India", "alpha2Code": "IN" }, { "country": "Russia", "alpha2Code": "RU" }, { "country": "Germany", "alpha2Code": "DE" }, { "country": "Iraq", "alpha2Code": "IQ" }, { "country": "Mexico", "alpha2Code": "MX" }, { "country": "Lebanon", "alpha2Code": "LB" }, { "country": "South Africa", "alpha2Code": "ZA" }, { "country": "Kuwait", "alpha2Code": "KW" }, { "country": "San Marino", "alpha2Code": "SM" }, { "country": "UAE", "alpha2Code": "AE" }, { "country": "Panama", "alpha2Code": "PA" }, { "country": "Armenia", "alpha2Code": "AM" }, { "country": "Taiwan", "alpha2Code": "TW" }, { "country": "USA", "alpha2Code": "US" }, { "country": "Argentina", "alpha2Code": "AR" }, { "country": "Colombia", "alpha2Code": "CO" }, { "country": "Slovakia", "alpha2Code": "SK" }, { "country": "Serbia", "alpha2Code": "RS" }, { "country": "Croatia", "alpha2Code": "HR" }, { "country": "Bulgaria", "alpha2Code": "BG" }, { "country": "Uruguay", "alpha2Code": "UY" }, { "country": "Algeria", "alpha2Code": "DZ" }, { "country": "Costa Rica", "alpha2Code": "CR" }, { "country": "Latvia", "alpha2Code": "LV" }, { "country": "France", "alpha2Code": "FR" }, { "country": "Hungary", "alpha2Code": "HU" }, { "country": "Vietnam", "alpha2Code": "VN" }, { "country": "Faeroe Islands", "alpha2Code": "FO" }, { "country": "Andorra", "alpha2Code": "AD" }, { "country": "Brunei", "alpha2Code": "BN" }, { "country": "Belarus", "alpha2Code": "BY" }, { "country": "Jordan", "alpha2Code": "JO" }, { "country": "Cyprus", "alpha2Code": "CY" }, { "country": "Sri Lanka", "alpha2Code": "LK" }, { "country": "Albania", "alpha2Code": "AL" }, { "country": "S. Korea", "alpha2Code": "KR" }, { "country": "Bosnia and Herzegovina", "alpha2Code": "BA" }, { "country": "Morocco", "alpha2Code": "MA" }, { "country": "Malta", "alpha2Code": "MT" }, { "country": "North Macedonia", "alpha2Code": "MK" }, { "country": "Moldova", "alpha2Code": "MD" }, { "country": "Kazakhstan", "alpha2Code": "KZ" }, { "country": "Lithuania", "alpha2Code": "LT" }, { "country": "Oman", "alpha2Code": "OM" }, { "country": "Cambodia", "alpha2Code": "KH" }, { "country": "Palestine", "alpha2Code": "PS" }, { "country": "Switzerland", "alpha2Code": "CH" }, { "country": "Guadeloupe", "alpha2Code": "GP" }, { "country": "Azerbaijan", "alpha2Code": "AZ" }, { "country": "Georgia", "alpha2Code": "GE" }, { "country": "Venezuela", "alpha2Code": "VE" }, { "country": "Tunisia", "alpha2Code": "TN" }, { "country": "New Zealand", "alpha2Code": "NZ" }, { "country": "Senegal", "alpha2Code": "SN" }, { "country": "Dominican Republic", "alpha2Code": "DO" }, { "country": "Burkina Faso", "alpha2Code": "BF" }, { "country": "Uzbekistan", "alpha2Code": "UZ" } ] `

does it include all countries?

**Comment by ottsch** [comment]
Yes, except Diamond Princess and Channel Islands

**Comment by sagarkarira** [comment]
Thanks @ottsch.
