### ISSUE TITLE
Incorrect historical case data from Spain

### ISSUE THREAD

**Issue by hreyeslo** [NovelCOVID/API#652]
For a few days I have observed that the historical data does not seem consistent. Could it be a bug?

![Anotación 2020-05-09 174219](https://user-images.githubusercontent.com/12648589/81478361-2cb52f80-921d-11ea-89e9-ab7975fc0f9e.png)
![Anotación 2020-05-09 174321](https://user-images.githubusercontent.com/12648589/81478363-2d4dc600-921d-11ea-877f-c3bb9a4dff8f.png)
![Anotación 2020-05-09 174349](https://user-images.githubusercontent.com/12648589/81478365-2d4dc600-921d-11ea-8fd1-464db39dce60.png)

Thanks for the enormous work.

**Comment by puf17640** [comment]
This is neither a bug nor a inconsistency in the dataset. 
This is due to different datasources being used for the different endpoints, so /v2/countries is using data from Worldometers while /v2/historical is using data from JHUCSSE
