### ISSUE TITLE
Work requested

### ISSUE THREAD

**Issue by kibertoad** [NovelCOVID/API#66]
I'm a Node.js developer and I'd like to help. Could I get some tasks that I could work on without overlapping with effort that is already being put?

**Comment by sagarkarira** [comment]
@kibertoad I made this coronavirus tracker cli app. https://github.com/sagarkarira/coronavirus-tracker-cli
I have some issues opened here if you like to help. :)

**Comment by kibertoad** [comment]
@sagarkarira Sounds great, thank you! What is the current way of marking tasks to be "In Progress" to avoid others taking them up? Also what communication channel is preferable for discussing development-related stuff?

**Comment by sagarkarira** [comment]
@kibertoad Right now I am working on adding new real-time API preferably from one from this repo. So I think I will be doing that tomorrow when I wake up. There were couple of features I wanted to add that I am not working on right now

1. adding historical graph/chart in cli (there are some good modules for that) 
2. adding twitter news updates or updates from Reddit (partially done, need better text arrangement)
3. You can also introduce any new feature, look at the code. 

For a communication channel, we can discuss over an issue in my repo. 

Thanks @kibertoad :)

**Comment by kibertoad** [comment]
@sagarkarira Thanks, I'll give it a shot tomorrow!

**Comment by EliteDaMyth** [comment]
@sagarkarira dont try to advertise your stuff all over here.

**Comment by kibertoad** [comment]
@EliteDaMyth What about the original question? Is there anything I could help with?

**Comment by EliteDaMyth** [comment]
what do you mean by "tasks"

**Comment by kibertoad** [comment]
@EliteDaMyth There are no open issues in repo, so I don't even know where to start if I wanted to contribute something useful to this project. If there is a communication channel I could use to discuss it and get something I could work on, that would be great.

**Comment by EliteDaMyth** [comment]
we have a discord server https://discord.gg/EvbMshU

**Comment by kibertoad** [comment]
@EliteDaMyth Are the non-core-team messages even visible to actual team members? I get an impression that messages from outsiders are simply ignored there 😅

**Comment by EliteDaMyth** [comment]
whats your discord username?

**Comment by kibertoad** [comment]
@EliteDaMyth Same. kibertoad
