### ISSUE TITLE
I have developed an android application using this api : got Suspended !!

### ISSUE THREAD

**Issue by Shiba-Kar** [NovelCOVID/API#660]
Additional verification is required to publish this app
--
Pursuant to Section 8.3 of the Developer Distribution Agreement and the Enforcement policy, apps referencing COVID-19, or related terms, in any form will only be approved for distribution on Google Play if they are published, commissioned, or authorized by official government entities or public health organizations. Google reserves the discretion to remove apps from Google Play based on a number of factors including a high risk of abuse.

**Is there any way to publish this app without renaming my app?**
[Link To My App](https://github.com/Shiba-Kar/covid-19_tracker)

**Comment by tbnritzdoge** [comment]
Well obviously not, this isn’t a government sanctioned API so you can’t have it on the App Store or the Android Play Store.

**Comment by Nekiono** [comment]
We're not any official source and don't claim to be.
Google is better off safe than sorry by doing this, and quite frankly the market is oversaturated anyways.
