### ISSUE TITLE
Enhancement: Fetch latest updates too from worldometers info page. 

### ISSUE THREAD

**Issue by sagarkarira** [NovelCOVID/API#67]
I plan on adding / updates API to track the latest news/updates on coronavirus for my cli tracker: https://github.com/sagarkarira/coronavirus-tracker-cli

I am currently fetching the data from Reddit.

It would be great if you could add that.

**Comment by EliteDaMyth** [comment]
you can simply scrape from reddit. this data is not for news just statistics
