### ISSUE TITLE
continents countries field not being set

### ISSUE THREAD

**Issue by ebwinters** [NovelCOVID/API#674]
`/v2/continents/` does not set property `countries` and tests fail because of this. Oh and worldometer added a `population` field and removed `continent` field
@puf17640

**Comment by itsbohara** [comment]
> `/v2/continents/` does not set property `countries` and tests fail because of this. Oh and worldometer added a `population` field and removed `continent` field
> @puf17640
Hey @ebwinters , I have fixed it. Check out my pull request.
