### ISSUE TITLE
Mathematical model for predicting the development of the COVID-19 by countries

### ISSUE THREAD

**Issue by edmitr** [NovelCOVID/API#685]
Hello! I have a mathematical model for predicting the development of the COVID-19 epidemic by countries (estimated date to reach the maximum of the epidemic, end date of the epidemic, estimated number of deaths, load of the health care system, estimated number of severe disease and critical). Prognosis will automatically changes dependig on the real situation. Would it be interesting to add such kind of forecast in the NovelCOVID API project? 
The adequacy of the prognostic model was confirmed by archival data from China, Iceland and Russia.

**Comment by puf17640** [comment]
Can we talk about this with the core-team on Discord?
Please either join our server and give us a notice it's you or dm me `Julian Pufler#0420`

**Comment by Nekiono** [comment]
Discord server is at https://disease.sh/discord btw :)
