### ISSUE TITLE
Consistent Gov data

### ISSUE THREAD

**Issue by MaxSpane** [NovelCOVID/API#695]
Could the gov data have some sort of consistency to their keys and the way they are accessed?
In my app I was going to frequently fetch the list of countries with available gov data so as to not have the user update the app when the new gov data is available.
But I realized the response for each gov data is very different so I wouldn't be able to avoid the issue.
I was thinking while scraping you parsed the data in a way that all the common data is in the same place and have the same key. Data such as name of regions, number of cases, number of deaths, number of recovered.
I noticed some of the responses are just arrays of the objects and some have regions in an array object with different keys alongside other data. 
May I propose you have an array for all the regions in an array object with the and then they have the cases number and the rest inside them using the same keys across gov data.

**Comment by ebwinters** [comment]
Can you elaborate on your proposal more. I'm not trying to be rude but it's difficult to understand what you're trying to say at the end of your post.

**Comment by MaxSpane** [comment]
It's fine. I'll be happy to elaborate.
The data structure I'm proposing is this.
```
{
  "regions": [
    {
      "region": The name of the region/province/state e.t.c,
      "cases": The total number of cases,
      "deaths": The total number of deaths,
      "recovered": The total number of recovered if available,
      "updated": when the data was last updated,
      ... All other data the government site provides about the region can be added
}
],
  ... Any other data that the government provides that is not region-specific can be added here
}
```
I hope what I'm proposing is clearer now. This way the general or rather the most commonly expected data is always available at the same position for all the government data so It'll be easier on the client-side to add any new government data without having to update the code.

**Comment by puf17640** [comment]
I understand you, it's a good idea. Me and Ethan probably both did an equal half on the endpoints and I also initially thought about having them a bit more standardized than it really was in the end. We will discuss on how this could be done the easiest way!

**Comment by ebwinters** [comment]
This is something that would be great to have, but since we already have the data formatted this way, it would be a breaking change to suddenly re-format. People who have apps using our API will have their apps broken. 
Instead, this is something to add to our V3 release. I will add it there
