### ISSUE TITLE
Add CONTRIBUTION guideline

### ISSUE THREAD

**Issue by egbakou** [NovelCOVID/API#698]
Add CONTRIBUTION guideline for improved collaboration in the open source project. It enables a self-onboarding concept for developers.

**Comment by puf17640** [comment]
Yes I have been wanting to do this quite some time now, will work on it but I have to look at example Contribution Guidelines because I don't really know what should be included there

**Comment by puf17640** [comment]
oops

**Comment by egbakou** [comment]
Okay.
I can make a PR for it if you want.

**Comment by puf17640** [comment]
yes please, i will look over it and change some stuff but that would be really helpful

**Comment by puf17640** [comment]
@egbakou are you gonna do a pr?

**Comment by egbakou** [comment]
Hi @puf17640 
Yes i work on it like that.
I will make the PR soon.

**Comment by egbakou** [comment]
PR submitted !
