### ISSUE TITLE
casesPerOneMillion not work corectly

### ISSUE THREAD

**Issue by satsis** [NovelCOVID/API#71]
country | "Ukraine"
cases | 41
todayCases | 0
deaths | 3
todayDeaths | 0
recovered | 1
active | 37
critical | 0
casesPerOneMillion | **0**

Need casesPerOneMillion **0.9**

**Comment by EliteDaMyth** [comment]
the data is from worldometers. casesperonemillions seems to be the amount of people that have the disease/total pupulation * 1m
if les speople have the disease the number is very close to 0

**Comment by satsis** [comment]
Let the one who needs it, he himself will scold or not use these values
