### ISSUE TITLE
Endpoint v2/continents: today's and yesterday's data mixed up

### ISSUE THREAD

**Issue by smilingchemist** [NovelCOVID/API#711]
Hi,
endpoint v2/continents shows yesterday's data for ?yesterday=false and today's data for ?yesterday=true.

**Comment by puf17640** [comment]
this seems to be true, im investigating

**Comment by ebwinters** [comment]
Seems to be working fine for me:
https://disease.sh/v2/continents/europe
https://disease.sh/v2/continents/europe?yesterday=true

**Comment by smilingchemist** [comment]
If you do not chose a continent it is mixed up.

**Comment by puf17640** [comment]
im too smashed to fix this currently but i think its true, ethan?

**Comment by ebwinters** [comment]
Nope, it works. See Asia's entry in JSON returned from the links below
https://disease.sh/v2/continents
https://disease.sh/v2/continents?yesterday=true

**Comment by smilingchemist** [comment]
No, see e.g. Australia: Today: 8722 cases, yesterday 8726 cases.

**Comment by ebwinters** [comment]
u rite
![](https://i.giphy.com/media/hzrvwvnbgIV6E/giphy.gif)

**Comment by puf17640** [comment]
told ya
