### ISSUE TITLE
v2/countries response body changed/mixed up?[BUG]

### ISSUE THREAD

**Issue by jmtblei** [NovelCOVID/API#719]
1. Response body appears to be mixed up for some fields. Continents used to return a string for a specific region e.g. "Asia", "Europe", "North America", etc; now returns a number string for what appears to be the country's population. 

2. ~~todayCases and todayDeaths return only 0 for both true/false yesterday queries.~~

3. Population, tests, testsPerOneMilion, recoveredPerOneMillion also do not seem correct; there may be additional fields that are incorrect.

4. There is a new field name undefined returning an integer in the response body that wasn't there previously.

**Comment by ebwinters** [comment]
Thanks for notifying us. We are looking at a fix - our source changed their format
