### ISSUE TITLE
"Critical" cases is always the same value with "Active" cases

### ISSUE THREAD

**Issue by ivan0071** [NovelCOVID/API#720]
From this endpoint: [https://disease.sh/v2/countries](https://disease.sh/v2/countries) I can see that the number of "critical" case is always the same with the number of "active" cases, which does not seems right.

![critical](https://user-images.githubusercontent.com/4018803/83225504-38db3f80-a180-11ea-8f64-1a1420e07f7c.png)

The same applies for all the countries.

**Comment by ebwinters** [comment]
fix coming in 5 min
