### ISSUE TITLE
[BUG] Missing Countries

### ISSUE THREAD

**Issue by mkusche** [NovelCOVID/API#729]
**Describe the bug**
In the Worldometer Data the following Countries are missing: 
- Kosovo
- Gaza 

**To Reproduce**
The following Requests don't show any data:
curl -X GET "https://disease.sh/v2/countries/Kosovo" -H  "accept: application/json"
curl -X GET "https://disease.sh/v2/countries/Gaza" -H  "accept: application/json"

**Expected behavior**
Both Requests show the expected data.

**Comment by ebwinters** [comment]
Are those countries listed on the worldometers website?

**Comment by mkusche** [comment]
Sorry, I hadn't have a look at Worldometer before. I guess there is nothing you can do about it.

**Comment by puf17640** [comment]
> Sorry, I hadn't have a look at Worldometer before. I guess there is nothing you can do about it.

well, there kinda is, do you have any official sources of these countries? I would be happy to add those to our government endpoints!

**Comment by mkusche** [comment]
In the historical API I can find them. When I do an get rquest from  https://disease.sh/v2/historical?lastdays=30, there is Kosovo and Westbank and Gaza listed with daily data.

**Comment by ebwinters** [comment]
It’s a separate source.
