### ISSUE TITLE
[BUG] Accumulative recovered cases

### ISSUE THREAD

**Issue by lbalmaceda** [NovelCOVID/API#732]
**Describe the bug**
The accumulative "recovered" cases value is lower than the previous day

**To Reproduce**
Make a request to https://corona.lmao.ninja/v2/historical/all?lastdays=3

**Expected behavior**
The accumulative "recovered" cases value for each day is equal or greater than the previous day.

**Screenshots**
![image](https://user-images.githubusercontent.com/3900123/83948194-0ff72200-a7f2-11ea-961d-58f1bce318a0.png)

**Additional context**
I'm using this approach of doing `today cases - yesterday cases` to calculate the "new cases for today", as suggested in one of the issues I found in the repo. Doing that for the recovered cases for today results in `-198987`.

**Comment by jzhao62** [comment]
Hi, under which country do you see this behavior ?

**Comment by jzhao62** [comment]
Looks like your problem has been fixed, they probably just upload wrong data. 
`{
    "cases": {
        "6/3/20": 6508635,
        "6/4/20": 6632985,
        "6/5/20": 6764918
    },
    "deaths": {
        "6/3/20": 385947,
        "6/4/20": 391136,
        "6/5/20": 395880
    },
    "recovered": {
        "6/3/20": 2822619,
        "6/4/20": 2892105,
        "6/5/20": 2960058
    }
}`

**Comment by EliteDaMyth** [comment]
We use the JHU CSSE repo data for historical cases. They sometime have somewhat inaccurate data but fix it later on. This issue is not related to this repository as we just scrape their data!
