### ISSUE TITLE
Incorrect data for USA (June 13th)

### ISSUE THREAD

**Issue by ivan0071** [NovelCOVID/API#744]
Data which was returned for USA for June 13th does not seems correct (this was updated on June 14th, calling the [https://disease.sh/v2/countries?yesterday=true](https://disease.sh/v2/countries?yesterday=true) endpoint). I am not sure which results were returned during the day June 13th itself.

...
"countryName": "USA",
"cases": 2117027,
**"todayCases": 105,**
"deaths": 116831,
**"todayDeaths": 6,**
...

**Comment by EliteDaMyth** [comment]
https://disease.sh/v2/countries/USA?yesterday=true
seems to be the correct values and matches worldometers.
We are scraping from Worldometers so the data matches there.

**Comment by EliteDaMyth** [comment]
Let me know if further help is needed @ivan0071
