### ISSUE TITLE
Access to XMLHttpRequest at 'https://disease.sh/v2/' from origin  has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Slimani-Ibrahim** [NovelCOVID/API#746]
The endpoints are not accessible owing to CORS policy issue
[](url)
<img width="935" alt="Sans titre" src="https://user-images.githubusercontent.com/36894964/84677747-13dc2000-af27-11ea-86d8-96864d13d75f.png">

**Comment by ebwinters** [comment]
This should be fixed now. Reopen if still issues.
