### ISSUE TITLE
Great Job & A Question

### ISSUE THREAD

**Issue by ahmadawais** [NovelCOVID/API#75]
Hi folks!

Great job building and keeping up this thing. I've built a CLI on top of this API that everyone is super appreciative of. 

I wanted to ask, where are you hosting this API. Are the stats open? How are you caching the API? I think these are all very interesting problems I'd love to more on — what scale this API has.

**Comment by apollyon600** [comment]
The api is open sourced, I believe you can view how we obtain the info in one of these files.

**Comment by ahmadawais** [comment]
Oh I do. I'm more interested in finding out where it's hosted, number of requests you are getting, how you are scaling, and the cost.

**Comment by EliteDaMyth** [comment]
Google cloud. 20million requests/day through cloudflare

**Comment by ahmadawais** [comment]
Is that Serverless or container based?
That's a lot of load. May I ask what the cost looks like?

**Comment by EliteDaMyth** [comment]
container based. the api is usually idling at ~4GB
