### ISSUE TITLE
Inconsistent Country Names

### ISSUE THREAD

**Issue by denizy97** [NovelCOVID/API#83]
Country names are different for historical data. For example for UK the country name for historical data is "United Kingdom" but for the current data it is "UK". For USA it is "us" for historical data but "USA" for current data. There might be more.

"https://corona.lmao.ninja/countries/uk" works, "https://corona.lmao.ninja/countries/united%20kingdom" doesn't.
"https://corona.lmao.ninja/historical/united%20kingdom" works, "https://corona.lmao.ninja/historical/uk" doesn't.

Is the historical data from another source?

**Comment by RyanHarlow** [comment]
Yes it looks like that data for the /countries endpoint is from
https://www.worldometers.info/coronavirus/

and the data for the historical endpoint is from
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by EliteDaMyth** [comment]
The sources are different as suggested by above comment.
