### ISSUE TITLE
Historical data from worldometers

### ISSUE THREAD

**Issue by Krato** [NovelCOVID/API#86]
Hello! First again thanks for the api.

I'm having some problems when I try to get historical data. 

In countries endpoint we are getting the data from worldometers. But in the historical data from JHU. That means different values, so for the users can result as an untrusted service.

For example China.

From countries cases: 81054
From yersterday historical: 81305

Will be great to save the info from worldometers as historical. If possible.

What do you think? 

Thanks!

**Comment by EliteDaMyth** [comment]
we dont really save the data from worldometers. If you would like to save it from our api go ahead
