### ISSUE TITLE
Plz Add Closed Cases and Active Cases

### ISSUE THREAD

**Issue by varundeva** [NovelCOVID/API#88]
Add Closed Cases and Active Cases

**Comment by EliteDaMyth** [comment]
easy to do on client side

**Comment by varundeva** [comment]
There is no data for active and closed case.
Scrap from Worldometer.
Rest of all good. Very quick response

**Comment by varundeva** [comment]
Include active and closed in Global data
/All

**Comment by EliteDaMyth** [comment]
@varundeva you can map through the data in countries endpoint and add yourself. its simpler.

**Comment by varundeva** [comment]
Ok
