### ISSUE TITLE
Country sort not working

### ISSUE THREAD

**Issue by gabrielcosi** [NovelCOVID/API#89]
https://corona.lmao.ninja/countries?sort=country

**Comment by EliteDaMyth** [comment]
fixed

**Comment by gabrielcosi** [comment]
Isn't it suppossed to be alphabetical order? Because it's inverted (Z-A)

**Comment by EliteDaMyth** [comment]
its meant to be for numbers. descending order. Letters will be ofc inverted

**Comment by gabrielcosi** [comment]
Could you please add country sort with alphabetical order as an endpoint or something? Thanks in advance
