### ISSUE TITLE
there is no historical data for usa

### ISSUE THREAD

**Issue by kw2019ltd** [NovelCOVID/API#91]
{"country":"usa","timeline":{"cases":{},"deaths":{},"recovered":{}}}

**Comment by RyanHarlow** [comment]
I believe you have to use us instead of usa try this link https://corona.lmao.ninja/historical/us

**Comment by ebwinters** [comment]
Should we make a manually mapping with all possible names lol

**Comment by RyanHarlow** [comment]
well and then there is naming inconsistency's between the two data sources aswell. UK vs United Kingdom. so it might be a good idea to somehow either standardize or find all possible names

**Comment by ebwinters** [comment]
I'll look into this later

**Comment by ebwinters** [comment]
Good to close this issue 👍

**Comment by kw2019ltd** [comment]
hi now its working i opened new issue for 

"S. Korea"

**Comment by ebwinters** [comment]
reopen this issue I have a fix

**Comment by ebwinters** [comment]
can close now with #112
