### ISSUE TITLE
the API getting the wrong country

### ISSUE THREAD

**Issue by WWGate** [NovelCOVID/API#92]
Hello,

I'm trying to get Oman country data but the API returns data for Romania, any help please

**Comment by RyanHarlow** [comment]
looks like its a bug. there is line in server.js that retrieves the country
  e => e.country.toLowerCase().includes(req.params.country.toLowerCase())

because rOMANia includes oman its returning romania first

**Comment by EliteDaMyth** [comment]
@RyanHarlow that pr can bream stuff instead can you make it so if there is a request paramenter strict it will search for the exact name. So it doesn't break current projects

**Comment by EliteDaMyth** [comment]
Break*

**Comment by EliteDaMyth** [comment]
Fixed with merging of the pr. Will update soon
