### ISSUE TITLE
Combined data on /all should show all the fields

### ISSUE THREAD

**Issue by CopyMist** [NovelCOVID/API#95]
This should totally be implemented. The combined data on `/all` should show all the fields, same as `/countries/<country>`. Why not add it if Worldometer already has it summed?

There's even a handy class ".total_row" that you can use to extract the values.

![2020-03-22_235405](https://user-images.githubusercontent.com/51974641/77260407-db66d600-6c98-11ea-891a-7054e7dff10b.png)

_Originally posted by @CopyMist in https://github.com/NovelCOVID/API/issues/48#issuecomment-602271989_

**Comment by EliteDaMyth** [comment]
Will take a look later

**Comment by CopyMist** [comment]
@EliteDaMyth Just FYI, if you gonna look at something later, you don't need to close the issue.
It should stay and be closed only if the code is merged and issue is resolved.
